---
# Configuration for https://pre-commit.com
# To use: pre-commit run -a
# Or to run every time you commit: pre-commit install
# To update this file: pre-commit autoupdate

repos:

  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: requirements-txt-fixer

  # Check for spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "larg"]
        exclude: >
            (?x)^(
                .*\.txt|
                .*\.ipynb
            )$

  # Clang format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.3
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]

  # CMake format
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: ["--line-width=90"]
      - id: cmake-lint
        args: ["--line-width=90"]

  # Ruff, the Python auto-correcting linter/formatter written in Rust
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes", "--exclude=__init__.py"]
      - id: ruff-format

  # Black format Python and notebooks
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black-jupyter
...
