---
# Configuration for https://pre-commit.com
# To use: pre-commit run -a
# Or to run every time you commit: pre-commit install
# To update this file: pre-commit autoupdate

repos:

  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: requirements-txt-fixer

  # Check for spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ["-L", "larg"]
        exclude: >
            (?x)^(
                .*\.txt|
                .*\.ipynb
            )$

  # Clang format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.5
    hooks:
      - id: clang-format

  # CMake format
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: ["--line-width=90"]
      - id: cmake-lint
        args: ["--line-width=90"]

  # Upgrade old Python syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  # Autoremoves unused imports
  - repo: https://github.com/hadialqattan/pycln
    rev: "v2.4.0"
    hooks:
      - id: pycln
        stages: [manual]

  # Sort includes
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Black format Python and notebooks
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black-jupyter

  # Check Python with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=95
          - --exclude=__init__.py
          - --ignore=E203
        additional_dependencies: [flake8-bugbear, pep8-naming]
...
