XCSF: act_neural.h File Reference
act_neural.h File Reference
Neural network action functions.
#include "action.h"
#include "neural.h"
#include "neural_activations.h"
#include "neural_layer.h"
#include "xcsf.h"
Data Structures
struct ActNeural
Neural network action data structure.
Functions
bool act_neural_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Dummy function since crossover is not performed on neural actions.
bool act_neural_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Dummy function since neural actions do not generalise another.
bool act_neural_mutate (const struct XCSF *xcsf, const struct Cl *c)
Mutates a neural network action.
int act_neural_compute (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Computes the current neural network action using the input.
void act_neural_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies a neural network action from one classifier to another.
void act_neural_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x, const int action)
Generates a neural network that covers the specified input:action.
void act_neural_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by a neural network action.
void act_neural_init (const struct XCSF *xcsf, struct Cl *c)
Creates and initialises an action neural network.
void act_neural_print (const struct XCSF *xcsf, const struct Cl *c)
Prints a neural network action.
void act_neural_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Dummy function since neural network actions are not updated.
size_t act_neural_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes a neural network action to a file.
size_t act_neural_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads a neural network action from a file.
Variables
static struct ActVtbl const act_neural_vtbl
neural action implemented functions.
Detailed Description
Neural network action functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2020.
Definition in file act_neural.h.
Function Documentation
act_neural_compute()
int act_neural_compute (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Computes the current neural network action using the input.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier calculating the action.
[in] x The input state.
Returns
The neural action.
Definition at line 107 of file act_neural.c.
References Cl::act, XCSF::explore, max_index(), XCSF::n_actions, ActNeural::net, neural_outputs(), and neural_propagate().
Referenced by act_neural_cover().
act_neural_copy()
void act_neural_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Copies a neural network action from one classifier to another.
Parameters
[in] xcsf The XCSF data structure.
[in] dest The destination classifier.
[in] src The source classifier.
Definition at line 122 of file act_neural.c.
References Cl::act, ActNeural::net, and neural_copy().
act_neural_cover()
void act_neural_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x, const int action)
Generates a neural network that covers the specified input:action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is being covered.
[in] x The input state to cover.
[in] action The action to cover.
Definition at line 152 of file act_neural.c.
References Cl::act, act_neural_compute(), ActNeural::net, and neural_rand().
act_neural_crossover()
bool act_neural_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Dummy function since crossover is not performed on neural actions.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The first classifier whose action is being crossed.
[in] c2 The second classifier whose action is being crossed.
Returns
False.
Definition at line 59 of file act_neural.c.
act_neural_free()
void act_neural_free (const struct XCSF * xcsf, const struct Cl * c)
Frees the memory used by a neural network action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be freed.
Definition at line 167 of file act_neural.c.
References Cl::act, ActNeural::net, and neural_free().
act_neural_general()
bool act_neural_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Dummy function since neural actions do not generalise another.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The classifier whose action is tested to be more general.
[in] c2 The classifier whose action is tested to be more specific.
Returns
False.
Definition at line 76 of file act_neural.c.
act_neural_init()
void act_neural_init (const struct XCSF * xcsf, struct Cl * c)
Creates and initialises an action neural network.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be initialised.
Definition at line 44 of file act_neural.c.
References Cl::act, XCSF::act, ArgsAct::largs, and neural_create().
act_neural_load()
size_t act_neural_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Reads a neural network action from a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 216 of file act_neural.c.
References Cl::act, and neural_load().
act_neural_mutate()
bool act_neural_mutate (const struct XCSF * xcsf, const struct Cl * c)
Mutates a neural network action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is being mutated.
Returns
Whether any alterations were made.
Definition at line 92 of file act_neural.c.
References Cl::act, ActNeural::net, and neural_mutate().
act_neural_print()
void act_neural_print (const struct XCSF * xcsf, const struct Cl * c)
Prints a neural network action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be printed.
Definition at line 137 of file act_neural.c.
References Cl::act, ActNeural::net, and neural_print().
act_neural_save()
size_t act_neural_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Writes a neural network action to a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 200 of file act_neural.c.
References Cl::act, ActNeural::net, and neural_save().
act_neural_update()
void act_neural_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Dummy function since neural network actions are not updated.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be updated.
[in] x The input state.
[in] y The payoff value.
Definition at line 183 of file act_neural.c.
Variable Documentation
act_neural_vtbl
struct ActVtbl const act_neural_vtbl static
Initial value:
= {
    &act_neural_general, &act_neural_crossover, &act_neural_mutate,
    &act_neural_compute, &act_neural_copy,      &act_neural_cover,
    &act_neural_free,    &act_neural_init,      &act_neural_print,
    &act_neural_update,  &act_neural_save,      &act_neural_load
}
neural action implemented functions.
Definition at line 83 of file act_neural.h.
Referenced by action_set().