XCSF: act_integer.h File Reference
act_integer.h File Reference
integer action functions.
#include "action.h"
#include "xcsf.h"
Data Structures
struct ActInteger
Integer action data structure.
Functions
bool act_integer_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Dummy function since integer actions do not perform crossover.
bool act_integer_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Returns whether the action of classifier c1 is more general than c2.
bool act_integer_mutate (const struct XCSF *xcsf, const struct Cl *c)
Mutates an integer action.
int act_integer_compute (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Returns a classifier's integer action.
void act_integer_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies an integer action from one classifier to another.
void act_integer_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x, const int action)
Sets an integer action to a specified value.
void act_integer_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by an integer action.
void act_integer_init (const struct XCSF *xcsf, struct Cl *c)
Initialises an integer action.
void act_integer_print (const struct XCSF *xcsf, const struct Cl *c)
Prints an integer action.
void act_integer_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Dummy function since integer actions are not updated.
size_t act_integer_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes an integer action to a file.
size_t act_integer_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads an integer action from a file.
char * act_integer_json_export (const struct XCSF *xcsf, const struct Cl *c)
Returns a json formatted string representation of an integer action.
void act_integer_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Creates an integer action from a cJSON object.
Variables
static struct ActVtbl const act_integer_vtbl
Integer action implemented functions.
Detailed Description
integer action functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2021.
Definition in file act_integer.h.
Function Documentation
act_integer_compute()
int act_integer_compute (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Returns a classifier's integer action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action to return.
[in] x The input state.
Returns
The classifier's action.
Definition at line 101 of file act_integer.c.
References Cl::act, and ActInteger::action.
act_integer_copy()
void act_integer_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Copies an integer action from one classifier to another.
Parameters
[in] xcsf The XCSF data structure.
[in] dest The destination classifier.
[in] src The source classifier.
Definition at line 117 of file act_integer.c.
References Cl::act, ActInteger::action, ActInteger::mu, and N_MU.
act_integer_cover()
void act_integer_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x, const int action)
Sets an integer action to a specified value.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is being covered.
[in] x The input state to cover.
[in] action The action to cover.
Definition at line 149 of file act_integer.c.
References Cl::act, and ActInteger::action.
act_integer_crossover()
bool act_integer_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Dummy function since integer actions do not perform crossover.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The first classifier whose action is being crossed.
[in] c2 The second classifier whose action is being crossed.
Returns
False.
Definition at line 43 of file act_integer.c.
act_integer_free()
void act_integer_free (const struct XCSF * xcsf, const struct Cl * c)
Frees the memory used by an integer action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be freed.
Definition at line 164 of file act_integer.c.
References Cl::act, and ActInteger::mu.
act_integer_general()
bool act_integer_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Returns whether the action of classifier c1 is more general than c2.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The classifier whose action is tested to be more general.
[in] c2 The classifier whose action is tested to be more specific.
Returns
Whether the action of c1 is more general than c2.
Definition at line 60 of file act_integer.c.
References Cl::act, and ActInteger::action.
act_integer_init()
void act_integer_init (const struct XCSF * xcsf, struct Cl * c)
Initialises an integer action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be initialised.
Definition at line 178 of file act_integer.c.
References Cl::act, MU_TYPE, N_MU, rand_uniform_int(), and sam_init().
act_integer_json_export()
char* act_integer_json_export (const struct XCSF * xcsf, const struct Cl * c)
Returns a json formatted string representation of an integer action.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose action is to be returned.
Returns
String encoded in json format.
Definition at line 249 of file act_integer.c.
References Cl::act, ActInteger::action, ActInteger::mu, and N_MU.
Referenced by act_integer_print().
act_integer_json_import()
void act_integer_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json)
Creates an integer action from a cJSON object.
Parameters
[in] xcsf The XCSF data structure.
[in,out] c The classifier to initialise.
[in] json cJSON object.
Definition at line 270 of file act_integer.c.
References Cl::act, ActInteger::action, ActInteger::mu, N_MU, and sam_json_import().
act_integer_load()
size_t act_integer_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Reads an integer action from a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 230 of file act_integer.c.
References Cl::act, and N_MU.
act_integer_mutate()
bool act_integer_mutate (const struct XCSF * xcsf, const struct Cl * c)
Mutates an integer action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is being mutated.
Returns
Whether any alterations were made.
Definition at line 79 of file act_integer.c.
References Cl::act, ActInteger::action, ActInteger::mu, MU_TYPE, N_MU, rand_uniform(), rand_uniform_int(), and sam_adapt().
act_integer_print()
void act_integer_print (const struct XCSF * xcsf, const struct Cl * c)
Prints an integer action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be printed.
Definition at line 134 of file act_integer.c.
References act_integer_json_export().
act_integer_save()
size_t act_integer_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Writes an integer action to a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 212 of file act_integer.c.
References Cl::act, ActInteger::action, ActInteger::mu, and N_MU.
act_integer_update()
void act_integer_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Dummy function since integer actions are not updated.
Parameters
[in] xcsf The XCSF data structure.
[in] c A classifier data structure.
[in] x The input state.
[in] y The payoff value.
Definition at line 195 of file act_integer.c.
Variable Documentation
act_integer_vtbl
struct ActVtbl const act_integer_vtbl static
Initial value:
= {
    &act_integer_general,     &act_integer_crossover,  &act_integer_mutate,
    &act_integer_compute,     &act_integer_copy,       &act_integer_cover,
    &act_integer_free,        &act_integer_init,       &act_integer_print,
    &act_integer_update,      &act_integer_save,       &act_integer_load,
    &act_integer_json_export, &act_integer_json_import
}
Integer action implemented functions.
Definition at line 83 of file act_integer.h.
Referenced by action_set().