XCSF: action.c File Reference
action.c File Reference
Interface for classifier actions.
#include "action.h"
#include "act_integer.h"
#include "act_neural.h"
#include "utils.h"
Functions
void action_set (const struct XCSF *xcsf, struct Cl *c)
Sets a classifier's action functions to the implementations.
const char * action_type_as_string (const int type)
Returns a string representation of an action type from an integer.
int action_type_as_int (const char *type)
Returns the integer representation of an action type given a name.
static void action_param_defaults_neural (struct XCSF *xcsf)
Initialises default neural action parameters.
void action_param_defaults (struct XCSF *xcsf)
Initialises default action parameters.
const char * action_param_json_export (const struct XCSF *xcsf)
Returns a json formatted string of the action parameters.
size_t action_param_save (const struct XCSF *xcsf, FILE *fp)
Saves action parameters.
size_t action_param_load (struct XCSF *xcsf, FILE *fp)
Loads action parameters.
void action_param_free (struct XCSF *xcsf)
Frees action parameters.
void action_param_set_type_string (struct XCSF *xcsf, const char *a)
void action_param_set_type (struct XCSF *xcsf, const int a)
Detailed Description
Interface for classifier actions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2021.
Definition in file action.c.
Function Documentation
action_param_defaults()
void action_param_defaults (struct XCSF * xcsf)
Initialises default action parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 125 of file action.c.
References ACT_TYPE_NEURAL, action_param_defaults_neural(), and action_param_set_type().
Referenced by param_init().
action_param_defaults_neural()
static void action_param_defaults_neural (struct XCSF * xcsf) static
Initialises default neural action parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 92 of file action.c.
References XCSF::act, CONNECTED, ArgsLayer::evolve_connect, ArgsLayer::evolve_neurons, ArgsLayer::evolve_weights, ArgsLayer::function, ArgsAct::largs, layer_args_copy(), layer_args_init(), LINEAR, LOGISTIC, ArgsLayer::max_neuron_grow, XCSF::n_actions, ArgsLayer::n_init, ArgsLayer::n_inputs, ArgsLayer::n_max, ArgsLayer::next, ArgsLayer::scale, SOFTMAX, ArgsLayer::type, and XCSF::x_dim.
Referenced by action_param_defaults().
action_param_free()
void action_param_free (struct XCSF * xcsf)
Frees action parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 191 of file action.c.
References XCSF::act, ArgsAct::largs, and layer_args_free().
Referenced by param_free().
action_param_json_export()
const char* action_param_json_export (const struct XCSF * xcsf)
Returns a json formatted string of the action parameters.
Parameters
[in] xcsf XCSF data structure.
Returns
String encoded in json format.
Definition at line 137 of file action.c.
References XCSF::act, ACT_TYPE_NEURAL, action_type_as_string(), ArgsAct::largs, layer_args_json_export(), and ArgsAct::type.
Referenced by param_json_export().
action_param_load()
size_t action_param_load (struct XCSF * xcsf, FILE * fp)
Loads action parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 177 of file action.c.
References XCSF::act, ArgsAct::largs, layer_args_load(), and ArgsAct::type.
Referenced by param_load().
action_param_save()
size_t action_param_save (const struct XCSF * xcsf, FILE * fp)
Saves action parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 161 of file action.c.
References XCSF::act, ArgsAct::largs, layer_args_save(), and ArgsAct::type.
Referenced by param_save().
action_param_set_type()
void action_param_set_type (struct XCSF * xcsf, const int a)
Definition at line 205 of file action.c.
References XCSF::act, and ArgsAct::type.
Referenced by action_param_defaults().
action_param_set_type_string()
void action_param_set_type_string (struct XCSF * xcsf, const char * a)
Definition at line 199 of file action.c.
References XCSF::act, action_type_as_int(), and ArgsAct::type.
Referenced by config_cl_act(), and XCS::set_action().
action_set()
void action_set (const struct XCSF * xcsf, struct Cl * c)
Sets a classifier's action functions to the implementations.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier to set.
Definition at line 35 of file action.c.
References XCSF::act, act_integer_vtbl, act_neural_vtbl, ACT_TYPE_INTEGER, ACT_TYPE_NEURAL, Cl::act_vptr, and ArgsAct::type.
Referenced by cl_load(), and cl_rand().
action_type_as_int()
int action_type_as_int (const char * type)
Returns the integer representation of an action type given a name.
Parameters
[in] type String representation of a condition type.
Returns
Integer representing the action type.
Definition at line 75 of file action.c.
References ACT_STRING_INTEGER, ACT_STRING_NEURAL, ACT_TYPE_INTEGER, and ACT_TYPE_NEURAL.
Referenced by action_param_set_type_string().
action_type_as_string()
const char* action_type_as_string (const int type)
Returns a string representation of an action type from an integer.
Parameters
[in] type Integer representation of an action type.
Returns
String representing the name of the action type.
Definition at line 56 of file action.c.
References ACT_STRING_INTEGER, ACT_STRING_NEURAL, ACT_TYPE_INTEGER, and ACT_TYPE_NEURAL.
Referenced by action_param_json_export().