XCSF: action.h File Reference
action.h File Reference
Interface for classifier actions.
#include "xcsf.h"
Data Structures
struct ArgsAct
Parameters for initialising and operating actions.
struct ActVtbl
Action interface data structure.
Macros
#define ACT_TYPE_INVALID (-1)
Error code for invalid actions.
#define ACT_TYPE_INTEGER (0)
Action type integer.
#define ACT_TYPE_NEURAL (1)
Action type neural network.
#define ACT_STRING_INTEGER ("integer\0")
Integer.
#define ACT_STRING_NEURAL ("neural\0")
Neural.
#define ACT_TYPE_OPTIONS "integer, neural"
Functions
void action_set (const struct XCSF *xcsf, struct Cl *c)
Sets a classifier's action functions to the implementations.
const char * action_type_as_string (const int type)
Returns a string representation of an action type from an integer.
int action_type_as_int (const char *type)
Returns the integer representation of an action type given a name.
void action_param_defaults (struct XCSF *xcsf)
Initialises default action parameters.
void action_param_free (struct XCSF *xcsf)
Frees action parameters.
char * action_param_json_import (struct XCSF *xcsf, cJSON *json)
Sets the action parameters from a cJSON object.
char * action_param_json_export (const struct XCSF *xcsf)
Returns a json formatted string of the action parameters.
size_t action_param_save (const struct XCSF *xcsf, FILE *fp)
Saves action parameters.
size_t action_param_load (struct XCSF *xcsf, FILE *fp)
Loads action parameters.
static size_t act_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes the action to a file.
static size_t act_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads the action from a file.
static bool act_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Returns whether the action of classifier c1 is more general than c2.
static bool act_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Performs classifier action crossover.
static bool act_mutate (const struct XCSF *xcsf, const struct Cl *c)
Performs classifier action mutation.
static int act_compute (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Computes the current classifier action using the input.
static void act_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies the action from one classifier to another.
static void act_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x, const int action)
Generates an action that matches the specified value.
static void act_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by the classifier action.
static void act_init (const struct XCSF *xcsf, struct Cl *c)
Initialises a classifier's action.
static void act_print (const struct XCSF *xcsf, const struct Cl *c)
Prints the classifier action.
static void act_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Updates the classifier's action.
static char * act_json_export (const struct XCSF *xcsf, const struct Cl *c)
Returns a json formatted string representation of an action .
static void act_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Creates an action from a cJSON object.
int action_param_set_type_string (struct XCSF *xcsf, const char *a)
void action_param_set_type (struct XCSF *xcsf, const int a)
Detailed Description
Interface for classifier actions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2022.
Definition in file action.h.
Macro Definition Documentation
ACT_STRING_INTEGER
#define ACT_STRING_INTEGER ("integer\0")
Integer.
Definition at line 32 of file action.h.
ACT_STRING_NEURAL
#define ACT_STRING_NEURAL ("neural\0")
Neural.
Definition at line 33 of file action.h.
ACT_TYPE_INTEGER
#define ACT_TYPE_INTEGER (0)
Action type integer.
Definition at line 29 of file action.h.
ACT_TYPE_INVALID
#define ACT_TYPE_INVALID (-1)
Error code for invalid actions.
Definition at line 28 of file action.h.
ACT_TYPE_NEURAL
#define ACT_TYPE_NEURAL (1)
Action type neural network.
Definition at line 30 of file action.h.
ACT_TYPE_OPTIONS
#define ACT_TYPE_OPTIONS "integer, neural"
Definition at line 35 of file action.h.
Function Documentation
act_compute()
static int act_compute (const struct XCSF * xcsf, const struct Cl * c, const double * x) static
Computes the current classifier action using the input.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier calculating the action.
[in] x The input state.
Returns
The classifier's action.
Definition at line 173 of file action.h.
References ActVtbl::act_impl_compute, and Cl::act_vptr.
Referenced by cl_action().
act_copy()
static void act_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src) static
Copies the action from one classifier to another.
Parameters
[in] xcsf The XCSF data structure.
[in] dest The destination classifier.
[in] src The source classifier.
Definition at line 185 of file action.h.
References ActVtbl::act_impl_copy, and Cl::act_vptr.
Referenced by cl_copy(), and cl_init_copy().
act_cover()
static void act_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x, const int action) static
Generates an action that matches the specified value.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is being covered.
[in] x The input state to cover.
[in] action The action to cover.
Definition at line 198 of file action.h.
References ActVtbl::act_impl_cover, Cl::act_vptr, and Cl::action.
Referenced by cl_cover().
act_crossover()
static bool act_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2) static
Performs classifier action crossover.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The first classifier whose action is being crossed.
[in] c2 The second classifier whose action is being crossed.
Returns
Whether any alterations were made.
Definition at line 148 of file action.h.
References ActVtbl::act_impl_crossover, and Cl::act_vptr.
Referenced by cl_crossover().
act_free()
static void act_free (const struct XCSF * xcsf, const struct Cl * c) static
Frees the memory used by the classifier action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be freed.
Definition at line 210 of file action.h.
References ActVtbl::act_impl_free, and Cl::act_vptr.
Referenced by cl_free().
act_general()
static bool act_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2) static
Returns whether the action of classifier c1 is more general than c2.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The classifier whose action is tested to be more general.
[in] c2 The classifier whose action is tested to be more specific.
Returns
Whether the action of c1 is more general than c2.
Definition at line 135 of file action.h.
References ActVtbl::act_impl_general, and Cl::act_vptr.
Referenced by cl_general().
act_init()
static void act_init (const struct XCSF * xcsf, struct Cl * c) static
Initialises a classifier's action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be initialised.
Definition at line 221 of file action.h.
References ActVtbl::act_impl_init, and Cl::act_vptr.
Referenced by cl_rand().
act_json_export()
static char * act_json_export (const struct XCSF * xcsf, const struct Cl * c) static
Returns a json formatted string representation of an action .
Parameters
[in] xcsf The XCSF data structure.
[in] c Classifier whose action is to be returned.
Returns
String encoded in json format.
Definition at line 258 of file action.h.
References ActVtbl::act_impl_json_export, and Cl::act_vptr.
Referenced by cl_json_export().
act_json_import()
static void act_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json) static
Creates an action from a cJSON object.
Parameters
[in] xcsf The XCSF data structure.
[in,out] c The classifier whose action is to be initialised.
[in] json cJSON object.
Definition at line 270 of file action.h.
References ActVtbl::act_impl_json_import, Cl::act_vptr, action_type_as_int(), and action_type_as_string().
Referenced by cl_json_import().
act_load()
static size_t act_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp) static
Reads the action from a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 122 of file action.h.
References ActVtbl::act_impl_load, and Cl::act_vptr.
Referenced by cl_load().
act_mutate()
static bool act_mutate (const struct XCSF * xcsf, const struct Cl * c) static
Performs classifier action mutation.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is being mutated.
Returns
Whether any alterations were made.
Definition at line 160 of file action.h.
References ActVtbl::act_impl_mutate, and Cl::act_vptr.
Referenced by cl_mutate().
act_print()
static void act_print (const struct XCSF * xcsf, const struct Cl * c) static
Prints the classifier action.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be printed.
Definition at line 232 of file action.h.
References ActVtbl::act_impl_print, and Cl::act_vptr.
act_save()
static size_t act_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp) static
Writes the action to a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose action is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 109 of file action.h.
References ActVtbl::act_impl_save, and Cl::act_vptr.
Referenced by cl_save().
act_update()
static void act_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y) static
Updates the classifier's action.
Parameters
[in] xcsf The XCSF data structure.
[in] c Classifier whose action is to be updated.
[in] x Input state.
[in] y Truth/payoff value.
Definition at line 245 of file action.h.
References ActVtbl::act_impl_update, and Cl::act_vptr.
Referenced by cl_update().
action_param_defaults()
void action_param_defaults (struct XCSF * xcsf)
Initialises default action parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 91 of file action.c.
References act_neural_param_defaults(), ACT_TYPE_INTEGER, and action_param_set_type().
Referenced by param_init().
action_param_free()
void action_param_free (struct XCSF * xcsf)
Frees action parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 184 of file action.c.
References layer_args_free().
Referenced by param_free().
action_param_json_export()
char * action_param_json_export (const struct XCSF * xcsf)
Returns a json formatted string of the action parameters.
Parameters
[in] xcsf XCSF data structure.
Returns
String encoded in json format.
Definition at line 103 of file action.c.
References ACT_TYPE_NEURAL, action_type_as_string(), layer_args_json_export(), and ArgsAct::type.
Referenced by param_json_export().
action_param_json_import()
char * action_param_json_import (struct XCSF * xcsf, cJSON * json)
Sets the action parameters from a cJSON object.
Parameters
[in,out] xcsf XCSF data structure.
[in] json cJSON object.
Returns
NULL if successful; or the name of parameter if not found.
Definition at line 131 of file action.c.
References act_neural_param_json_import(), ACT_TYPE_INTEGER, and ACT_TYPE_NEURAL.
Referenced by param_json_import_action().
action_param_load()
size_t action_param_load (struct XCSF * xcsf, FILE * fp)
Loads action parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 170 of file action.c.
References ArgsAct::largs, layer_args_load(), and ArgsAct::type.
Referenced by param_load().
action_param_save()
size_t action_param_save (const struct XCSF * xcsf, FILE * fp)
Saves action parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 154 of file action.c.
References ArgsAct::largs, layer_args_save(), and ArgsAct::type.
Referenced by param_save().
action_param_set_type()
void action_param_set_type (struct XCSF * xcsf, const int a)
Definition at line 202 of file action.c.
Referenced by action_param_defaults().
action_param_set_type_string()
int action_param_set_type_string (struct XCSF * xcsf, const char * a)
Definition at line 192 of file action.c.
References ACT_TYPE_INVALID, action_type_as_int(), and ArgsAct::type.
Referenced by param_json_import_action().
action_set()
void action_set (const struct XCSF * xcsf, struct Cl * c)
Sets a classifier's action functions to the implementations.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier to set.
Definition at line 35 of file action.c.
References act_integer_vtbl, act_neural_vtbl, ACT_TYPE_INTEGER, ACT_TYPE_NEURAL, and Cl::act_vptr.
Referenced by cl_load(), and cl_rand().
action_type_as_int()
int action_type_as_int (const char * type)
Returns the integer representation of an action type given a name.
Parameters
[in] type String representation of a condition type.
Returns
Integer representing the action type.
Definition at line 75 of file action.c.
References ACT_STRING_INTEGER, ACT_STRING_NEURAL, ACT_TYPE_INTEGER, ACT_TYPE_INVALID, and ACT_TYPE_NEURAL.
Referenced by act_json_import(), and action_param_set_type_string().
action_type_as_string()
const char * action_type_as_string (const int type)
Returns a string representation of an action type from an integer.
Parameters
[in] type Integer representation of an action type.
Returns
String representing the name of the action type.
Definition at line 56 of file action.c.
References ACT_STRING_INTEGER, ACT_STRING_NEURAL, ACT_TYPE_INTEGER, and ACT_TYPE_NEURAL.
Referenced by act_json_import(), and action_param_json_export().