XCSF: XCS Class Reference
XCS Class Reference
Python XCSF class data structure.
Public Member Functions
XCS (const int x_dim, const int y_dim, const int n_actions)
Constructor with default config.
XCS (const int x_dim, const int y_dim, const int n_actions, const char *filename)
Constructor with a specified config.
int version_major (void)
Returns the XCSF major version number.
int version_minor (void)
Returns the XCSF minor version number.
int version_build (void)
Returns the XCSF build version number.
size_t save (const char *filename)
Writes the entire current state of XCSF to a file.
size_t load (const char *filename)
Reads the entire current state of XCSF from a file.
void store (void)
Stores the current population in memory for later retrieval.
void retrieve (void)
Retrieves the stored population, setting it as current.
void print_params (void)
Prints the XCSF parameters and their current values.
void pred_expand (void)
Inserts a new hidden layer before the output layer within all prediction neural networks in the population.
void ae_to_classifier (const int y_dim, const int n_del)
Switches from autoencoding to classification.
void print_pset (const bool print_cond, const bool print_act, const bool print_pred)
Prints the current population.
double fit (const py::array_t< double > input, const int action, const double reward)
Creates/updates an action set for a given (state, action, reward).
void init_trial (void)
Initialises a reinforcement learning trial.
void end_trial (void)
Frees memory used by a reinforcement learning trial.
void init_step (void)
Initialises a step in a reinforcement learning trial.
void end_step (void)
Ends a step in a reinforcement learning trial.
int decision (const py::array_t< double > input, const bool explore)
Selects an action to perform in a reinforcement learning problem.
void update (const double reward, const bool done)
Creates the action set using the previously selected action, updates the classifiers, and runs the EA on explore steps.
double error (const double reward, const bool done, const double max_p)
Returns the reinforcement learning system prediction error.
double fit (const py::array_t< double > train_X, const py::array_t< double > train_Y, const bool shuffle)
Executes MAX_TRIALS number of XCSF learning iterations using the provided training data.
double fit (const py::array_t< double > train_X, const py::array_t< double > train_Y, const py::array_t< double > test_X, const py::array_t< double > test_Y, const bool shuffle)
Executes MAX_TRIALS number of XCSF learning iterations using the provided training data and test iterations using the test data.
py::array_t< double > predict (const py::array_t< double > x)
Returns the XCSF prediction array for the provided input.
double score (const py::array_t< double > test_X, const py::array_t< double > test_Y)
Returns the error over one sequential pass of the provided data.
double score (const py::array_t< double > test_X, const py::array_t< double > test_Y, const int N)
Returns the error using N random samples from the provided data.
double error (void)
Returns the current system error.
int get_omp_num_threads (void)
bool get_pop_init (void)
int get_max_trials (void)
int get_perf_trials (void)
int get_pop_max_size (void)
const char * get_loss_func (void)
double get_huber_delta (void)
double get_alpha (void)
double get_beta (void)
double get_delta (void)
double get_e0 (void)
double get_init_error (void)
double get_init_fitness (void)
double get_nu (void)
int get_m_probation (void)
bool get_stateful (void)
bool get_compaction (void)
int get_theta_del (void)
int get_theta_sub (void)
bool get_set_subsumption (void)
int get_pset_size (void)
int get_pset_num (void)
int get_time (void)
double get_x_dim (void)
double get_y_dim (void)
double get_n_actions (void)
double get_pset_mean_cond_size (void)
double get_pset_mean_pred_size (void)
double get_pset_mean_pred_eta (const int layer)
double get_pset_mean_pred_neurons (const int layer)
double get_pset_mean_pred_connections (const int layer)
double get_pset_mean_pred_layers (void)
double get_pset_mean_cond_connections (const int layer)
double get_pset_mean_cond_neurons (const int layer)
double get_pset_mean_cond_layers (void)
double get_mset_size (void)
double get_aset_size (void)
double get_mfrac (void)
int get_teletransportation (void)
double get_gamma (void)
double get_p_explore (void)
int get_ea_select_type (void)
double get_ea_select_size (void)
double get_theta_ea (void)
int get_lambda (void)
double get_p_crossover (void)
double get_err_reduc (void)
double get_fit_reduc (void)
bool get_ea_subsumption (void)
bool get_ea_pred_reset (void)
void set_condition (const std::string &type)
Sets the condition type.
void set_action (const std::string &type)
Sets the action type.
void set_prediction (const std::string &type)
Sets the prediction type.
void set_condition (const std::string &type, const py::dict &args)
Sets the condition type and initialisation arguments.
void unpack_cond_csr (const py::dict &args)
Sets parameters used by center-spread conditions.
void unpack_cond_gp (const py::dict &args)
Sets parameters used by tree-GP conditions.
void unpack_cond_dgp (const py::dict &args)
Sets parameters used by dynamical GP graph conditions.
void unpack_cond_ternary (const py::dict &args)
Sets parameters used by ternary conditions.
void unpack_cond_neural (const py::dict &args)
Sets parameters used by neural network conditions.
void unpack_layer_params (struct ArgsLayer *larg, const py::dict &args)
Sets parameters used by a neural network layer.
void set_action (const std::string &type, const py::dict &args)
Sets the action type and initialisation arguments.
void unpack_act_neural (const py::dict &args)
Sets parameters used by neural network actions.
void set_prediction (const std::string &type, const py::dict &args)
Sets the prediction type and initialisation arguments.
void unpack_pred_neural (const py::dict &args)
Sets parameters used by neural network predictions.
void unpack_pred_nlms (const py::dict &args)
Sets parameters used by least mean squares predictions.
void unpack_pred_rls (const py::dict &args)
Sets parameters used by recursive least mean squares predictions.
void set_omp_num_threads (const int a)
void set_pop_init (const bool a)
void set_max_trials (const int a)
void set_perf_trials (const int a)
void set_pop_max_size (const int a)
void set_loss_func (const char *a)
void set_huber_delta (const double a)
void set_alpha (const double a)
void set_beta (const double a)
void set_delta (const double a)
void set_e0 (const double a)
void set_init_error (const double a)
void set_init_fitness (const double a)
void set_nu (const double a)
void set_m_probation (const int a)
void set_theta_del (const int a)
void set_theta_sub (const int a)
void set_set_subsumption (const bool a)
void set_teletransportation (const int a)
void set_stateful (const bool a)
void set_compaction (const bool a)
void set_gamma (const double a)
void set_p_explore (const double a)
void set_ea_select_type (const char *a)
void set_ea_select_size (const double a)
void set_theta_ea (const double a)
void set_lambda (const int a)
void set_p_crossover (const double a)
void set_err_reduc (const double a)
void set_fit_reduc (const double a)
void set_ea_subsumption (const bool a)
void set_ea_pred_reset (const bool a)
void seed (const uint32_t seed)
Private Attributes
struct XCSF xcs
XCSF data structure.
double * state
Current input state for RL.
int action
Current action for RL.
double payoff
Current reward for RL.
struct Input * train_data
Training data for supervised learning.
struct Input * test_data
Test data for supervised learning.
Detailed Description
Python XCSF class data structure.
Definition at line 58 of file pybind_wrapper.cpp.
Constructor & Destructor Documentation
XCS() [1/2]
XCS::XCS (const int x_dim, const int y_dim, const int n_actions) inline
Constructor with default config.
Parameters
[in] x_dim The dimensionality of the input variables.
[in] y_dim The dimensionality of the prediction variables.
[in] n_actions The total number of possible actions.
Definition at line 75 of file pybind_wrapper.cpp.
XCS() [2/2]
XCS::XCS (const int x_dim, const int y_dim, const int n_actions, const char * filename) inline
Constructor with a specified config.
Parameters
[in] x_dim The dimensionality of the input variables.
[in] y_dim The dimensionality of the prediction variables.
[in] n_actions The total number of possible actions.
[in] filename The name of a parameter configuration file.
Definition at line 87 of file pybind_wrapper.cpp.
References action, config_read(), Input::n_samples, pa_init(), param_init(), payoff, state, test_data, train_data, Input::x, Input::x_dim, xcs, xcsf_init(), Input::y, and Input::y_dim.
Member Function Documentation
ae_to_classifier()
void XCS::ae_to_classifier (const int y_dim, const int n_del) inline
Switches from autoencoding to classification.
Parameters
[in] y_dim The output dimension (i.e., the number of classes).
[in] n_del The number of hidden layers to remove.
Definition at line 206 of file pybind_wrapper.cpp.
References xcs, xcsf_ae_to_classifier(), and Input::y_dim.
Referenced by pybind11_init_wrapper().
decision()
int XCS::decision (const py::array_t< double > input, const bool explore) inline
Selects an action to perform in a reinforcement learning problem.
Constructs the match set and selects an action to perform.
Parameters
[in] input The input state.
[in] explore Whether this is an exploration step.
Returns
The selected action.
Definition at line 288 of file pybind_wrapper.cpp.
References action, param_set_explore(), state, xcs, and xcs_rl_decision().
Referenced by pybind11_init_wrapper().
end_step()
void XCS::end_step (void) inline
Ends a step in a reinforcement learning trial.
Definition at line 275 of file pybind_wrapper.cpp.
References action, payoff, state, xcs, and xcs_rl_end_step().
Referenced by pybind11_init_wrapper().
end_trial()
void XCS::end_trial (void) inline
Frees memory used by a reinforcement learning trial.
Definition at line 257 of file pybind_wrapper.cpp.
References xcs, and xcs_rl_end_trial().
Referenced by pybind11_init_wrapper().
error() [1/2]
double XCS::error (const double reward, const bool done, const double max_p) inline
Returns the reinforcement learning system prediction error.
Parameters
[in] reward The current reward.
[in] done Whether the environment is in a terminal state.
[in] max_p The maximum payoff in the environment.
Returns
The prediction error.
Definition at line 318 of file pybind_wrapper.cpp.
References action, payoff, xcs, and xcs_rl_error().
error() [2/2]
double XCS::error (void) inline
Returns the current system error.
Returns
Moving average of the system error, updated with step size BETA.
Definition at line 481 of file pybind_wrapper.cpp.
References XCSF::error, and xcs.
Referenced by pybind11_init_wrapper().
fit() [1/3]
double XCS::fit (const py::array_t< double > input, const int action, const double reward) inline
Creates/updates an action set for a given (state, action, reward).
Parameters
[in] input The input state to match.
[in] action The selected action.
[in] reward The reward for having performed the action.
Returns
The prediction error.
Definition at line 234 of file pybind_wrapper.cpp.
References action, state, xcs, and xcs_rl_fit().
Referenced by pybind11_init_wrapper().
fit() [2/3]
double XCS::fit (const py::array_t< double > train_X, const py::array_t< double > train_Y, const bool shuffle) inline
Executes MAX_TRIALS number of XCSF learning iterations using the provided training data.
Parameters
[in] train_X The input values to use for training.
[in] train_Y The true output values to use for training.
[in] shuffle Whether to randomise the instances during training.
Returns
The average XCSF training error using the loss function.
Definition at line 335 of file pybind_wrapper.cpp.
References clset_pset_init(), Input::n_samples, XCSF::time, train_data, Input::x, Input::x_dim, xcs, xcs_supervised_fit(), Input::y, and Input::y_dim.
fit() [3/3]
double XCS::fit (const py::array_t< double > train_X, const py::array_t< double > train_Y, const py::array_t< double > test_X, const py::array_t< double > test_Y, const bool shuffle) inline
Executes MAX_TRIALS number of XCSF learning iterations using the provided training data and test iterations using the test data.
Parameters
[in] train_X The input values to use for training.
[in] train_Y The true output values to use for training.
[in] test_X The input values to use for testing.
[in] test_Y The true output values to use for testing.
[in] shuffle Whether to randomise the instances during training.
Returns
The average XCSF training error using the loss function.
Definition at line 369 of file pybind_wrapper.cpp.
References clset_pset_init(), Input::n_samples, test_data, XCSF::time, train_data, Input::x, Input::x_dim, xcs, xcs_supervised_fit(), Input::y, and Input::y_dim.
get_alpha()
double XCS::get_alpha (void) inline
Definition at line 529 of file pybind_wrapper.cpp.
References XCSF::ALPHA, and xcs.
Referenced by pybind11_init_wrapper().
get_aset_size()
double XCS::get_aset_size (void) inline
Definition at line 703 of file pybind_wrapper.cpp.
References XCSF::aset_size, and xcs.
Referenced by pybind11_init_wrapper().
get_beta()
double XCS::get_beta (void) inline
Definition at line 535 of file pybind_wrapper.cpp.
References XCSF::BETA, and xcs.
Referenced by pybind11_init_wrapper().
get_compaction()
bool XCS::get_compaction (void) inline
Definition at line 583 of file pybind_wrapper.cpp.
References XCSF::COMPACTION, and xcs.
Referenced by pybind11_init_wrapper().
get_delta()
double XCS::get_delta (void) inline
Definition at line 541 of file pybind_wrapper.cpp.
References XCSF::DELTA, and xcs.
Referenced by pybind11_init_wrapper().
get_e0()
double XCS::get_e0 (void) inline
Definition at line 547 of file pybind_wrapper.cpp.
References XCSF::E0, and xcs.
Referenced by pybind11_init_wrapper().
get_ea_pred_reset()
bool XCS::get_ea_pred_reset (void) inline
Definition at line 781 of file pybind_wrapper.cpp.
References XCSF::ea, ArgsEA::pred_reset, and xcs.
Referenced by pybind11_init_wrapper().
get_ea_select_size()
double XCS::get_ea_select_size (void) inline
Definition at line 739 of file pybind_wrapper.cpp.
References XCSF::ea, ArgsEA::select_size, and xcs.
Referenced by pybind11_init_wrapper().
get_ea_select_type()
int XCS::get_ea_select_type (void) inline
Definition at line 733 of file pybind_wrapper.cpp.
References XCSF::ea, ArgsEA::select_type, and xcs.
Referenced by pybind11_init_wrapper().
get_ea_subsumption()
bool XCS::get_ea_subsumption (void) inline
Definition at line 775 of file pybind_wrapper.cpp.
References XCSF::ea, ArgsEA::subsumption, and xcs.
Referenced by pybind11_init_wrapper().
get_err_reduc()
double XCS::get_err_reduc (void) inline
Definition at line 763 of file pybind_wrapper.cpp.
References XCSF::ea, ArgsEA::err_reduc, and xcs.
Referenced by pybind11_init_wrapper().
get_fit_reduc()
double XCS::get_fit_reduc (void) inline
Definition at line 769 of file pybind_wrapper.cpp.
References XCSF::ea, ArgsEA::fit_reduc, and xcs.
Referenced by pybind11_init_wrapper().
get_gamma()
double XCS::get_gamma (void) inline
Definition at line 721 of file pybind_wrapper.cpp.
References XCSF::GAMMA, and xcs.
Referenced by pybind11_init_wrapper().
get_huber_delta()
double XCS::get_huber_delta (void) inline
Definition at line 523 of file pybind_wrapper.cpp.
References XCSF::HUBER_DELTA, and xcs.
Referenced by pybind11_init_wrapper().
get_init_error()
double XCS::get_init_error (void) inline
Definition at line 553 of file pybind_wrapper.cpp.
References XCSF::INIT_ERROR, and xcs.
Referenced by pybind11_init_wrapper().
get_init_fitness()
double XCS::get_init_fitness (void) inline
Definition at line 559 of file pybind_wrapper.cpp.
References XCSF::INIT_FITNESS, and xcs.
Referenced by pybind11_init_wrapper().
get_lambda()
int XCS::get_lambda (void) inline
Definition at line 751 of file pybind_wrapper.cpp.
References XCSF::ea, ArgsEA::lambda, and xcs.
Referenced by pybind11_init_wrapper().
get_loss_func()
const char* XCS::get_loss_func (void) inline
Definition at line 517 of file pybind_wrapper.cpp.
References XCSF::LOSS_FUNC, loss_type_as_string(), and xcs.
Referenced by pybind11_init_wrapper().
get_m_probation()
int XCS::get_m_probation (void) inline
Definition at line 571 of file pybind_wrapper.cpp.
References XCSF::M_PROBATION, and xcs.
Referenced by pybind11_init_wrapper().
get_max_trials()
int XCS::get_max_trials (void) inline
Definition at line 499 of file pybind_wrapper.cpp.
References XCSF::MAX_TRIALS, and xcs.
Referenced by pybind11_init_wrapper().
get_mfrac()
double XCS::get_mfrac (void) inline
Definition at line 709 of file pybind_wrapper.cpp.
References XCSF::mfrac, and xcs.
Referenced by pybind11_init_wrapper().
get_mset_size()
double XCS::get_mset_size (void) inline
Definition at line 697 of file pybind_wrapper.cpp.
References XCSF::mset_size, and xcs.
Referenced by pybind11_init_wrapper().
get_n_actions()
double XCS::get_n_actions (void) inline
Definition at line 637 of file pybind_wrapper.cpp.
References XCSF::n_actions, and xcs.
Referenced by pybind11_init_wrapper().
get_nu()
double XCS::get_nu (void) inline
Definition at line 565 of file pybind_wrapper.cpp.
References XCSF::NU, and xcs.
Referenced by pybind11_init_wrapper().
get_omp_num_threads()
int XCS::get_omp_num_threads (void) inline
Definition at line 487 of file pybind_wrapper.cpp.
References XCSF::OMP_NUM_THREADS, and xcs.
Referenced by pybind11_init_wrapper().
get_p_crossover()
double XCS::get_p_crossover (void) inline
Definition at line 757 of file pybind_wrapper.cpp.
References XCSF::ea, ArgsEA::p_crossover, and xcs.
Referenced by pybind11_init_wrapper().
get_p_explore()
double XCS::get_p_explore (void) inline
Definition at line 727 of file pybind_wrapper.cpp.
References XCSF::P_EXPLORE, and xcs.
Referenced by pybind11_init_wrapper().
get_perf_trials()
int XCS::get_perf_trials (void) inline
Definition at line 505 of file pybind_wrapper.cpp.
References XCSF::PERF_TRIALS, and xcs.
Referenced by pybind11_init_wrapper().
get_pop_init()
bool XCS::get_pop_init (void) inline
Definition at line 493 of file pybind_wrapper.cpp.
References XCSF::POP_INIT, and xcs.
Referenced by pybind11_init_wrapper().
get_pop_max_size()
int XCS::get_pop_max_size (void) inline
Definition at line 511 of file pybind_wrapper.cpp.
References XCSF::POP_SIZE, and xcs.
Referenced by pybind11_init_wrapper().
get_pset_mean_cond_connections()
double XCS::get_pset_mean_cond_connections (const int layer) inline
Definition at line 679 of file pybind_wrapper.cpp.
References clset_mean_cond_connections(), XCSF::pset, and xcs.
Referenced by pybind11_init_wrapper().
get_pset_mean_cond_layers()
double XCS::get_pset_mean_cond_layers (void) inline
Definition at line 691 of file pybind_wrapper.cpp.
References clset_mean_cond_layers(), XCSF::pset, and xcs.
Referenced by pybind11_init_wrapper().
get_pset_mean_cond_neurons()
double XCS::get_pset_mean_cond_neurons (const int layer) inline
Definition at line 685 of file pybind_wrapper.cpp.
References clset_mean_cond_neurons(), XCSF::pset, and xcs.
Referenced by pybind11_init_wrapper().
get_pset_mean_cond_size()
double XCS::get_pset_mean_cond_size (void) inline
Definition at line 643 of file pybind_wrapper.cpp.
References clset_mean_cond_size(), XCSF::pset, and xcs.
Referenced by pybind11_init_wrapper().
get_pset_mean_pred_connections()
double XCS::get_pset_mean_pred_connections (const int layer) inline
Definition at line 667 of file pybind_wrapper.cpp.
References clset_mean_pred_connections(), XCSF::pset, and xcs.
Referenced by pybind11_init_wrapper().
get_pset_mean_pred_eta()
double XCS::get_pset_mean_pred_eta (const int layer) inline
Definition at line 655 of file pybind_wrapper.cpp.
References clset_mean_pred_eta(), XCSF::pset, and xcs.
Referenced by pybind11_init_wrapper().
get_pset_mean_pred_layers()
double XCS::get_pset_mean_pred_layers (void) inline
Definition at line 673 of file pybind_wrapper.cpp.
References clset_mean_pred_layers(), XCSF::pset, and xcs.
Referenced by pybind11_init_wrapper().
get_pset_mean_pred_neurons()
double XCS::get_pset_mean_pred_neurons (const int layer) inline
Definition at line 661 of file pybind_wrapper.cpp.
References clset_mean_pred_neurons(), XCSF::pset, and xcs.
Referenced by pybind11_init_wrapper().
get_pset_mean_pred_size()
double XCS::get_pset_mean_pred_size (void) inline
Definition at line 649 of file pybind_wrapper.cpp.
References clset_mean_pred_size(), XCSF::pset, and xcs.
Referenced by pybind11_init_wrapper().
get_pset_num()
int XCS::get_pset_num (void) inline
Definition at line 613 of file pybind_wrapper.cpp.
References Set::num, XCSF::pset, and xcs.
Referenced by pybind11_init_wrapper().
get_pset_size()
int XCS::get_pset_size (void) inline
Definition at line 607 of file pybind_wrapper.cpp.
References XCSF::pset, Set::size, and xcs.
Referenced by pybind11_init_wrapper().
get_set_subsumption()
bool XCS::get_set_subsumption (void) inline
Definition at line 601 of file pybind_wrapper.cpp.
References XCSF::SET_SUBSUMPTION, and xcs.
Referenced by pybind11_init_wrapper().
get_stateful()
bool XCS::get_stateful (void) inline
Definition at line 577 of file pybind_wrapper.cpp.
References XCSF::STATEFUL, and xcs.
Referenced by pybind11_init_wrapper().
get_teletransportation()
int XCS::get_teletransportation (void) inline
Definition at line 715 of file pybind_wrapper.cpp.
References XCSF::TELETRANSPORTATION, and xcs.
Referenced by pybind11_init_wrapper().
get_theta_del()
int XCS::get_theta_del (void) inline
Definition at line 589 of file pybind_wrapper.cpp.
References XCSF::THETA_DEL, and xcs.
Referenced by pybind11_init_wrapper().
get_theta_ea()
double XCS::get_theta_ea (void) inline
Definition at line 745 of file pybind_wrapper.cpp.
References XCSF::ea, ArgsEA::theta, and xcs.
Referenced by pybind11_init_wrapper().
get_theta_sub()
int XCS::get_theta_sub (void) inline
Definition at line 595 of file pybind_wrapper.cpp.
References XCSF::THETA_SUB, and xcs.
Referenced by pybind11_init_wrapper().
get_time()
int XCS::get_time (void) inline
Definition at line 619 of file pybind_wrapper.cpp.
References XCSF::time, and xcs.
Referenced by pybind11_init_wrapper().
get_x_dim()
double XCS::get_x_dim (void) inline
Definition at line 625 of file pybind_wrapper.cpp.
References XCSF::x_dim, and xcs.
Referenced by pybind11_init_wrapper().
get_y_dim()
double XCS::get_y_dim (void) inline
Definition at line 631 of file pybind_wrapper.cpp.
References xcs, and XCSF::y_dim.
Referenced by pybind11_init_wrapper().
init_step()
void XCS::init_step (void) inline
Initialises a step in a reinforcement learning trial.
Definition at line 266 of file pybind_wrapper.cpp.
References xcs, and xcs_rl_init_step().
Referenced by pybind11_init_wrapper().
init_trial()
void XCS::init_trial (void) inline
Initialises a reinforcement learning trial.
Definition at line 245 of file pybind_wrapper.cpp.
References clset_pset_init(), XCSF::time, xcs, and xcs_rl_init_trial().
Referenced by pybind11_init_wrapper().
load()
size_t XCS::load (const char * filename) inline
Reads the entire current state of XCSF from a file.
Parameters
[in] filename String containing the name of the input file.
Returns
The total number of elements read.
Definition at line 158 of file pybind_wrapper.cpp.
References xcs, and xcsf_load().
Referenced by pybind11_init_wrapper().
pred_expand()
void XCS::pred_expand (void) inline
Inserts a new hidden layer before the output layer within all prediction neural networks in the population.
Definition at line 195 of file pybind_wrapper.cpp.
References xcs, and xcsf_pred_expand().
Referenced by pybind11_init_wrapper().
predict()
py::array_t<double> XCS::predict (const py::array_t< double > x) inline
Returns the XCSF prediction array for the provided input.
Parameters
[in] x The input variables.
Returns
The prediction array values.
Definition at line 419 of file pybind_wrapper.cpp.
References Input::n_samples, XCSF::pa_size, Input::x, xcs, and xcs_supervised_predict().
Referenced by pybind11_init_wrapper().
print_params()
void XCS::print_params (void) inline
Prints the XCSF parameters and their current values.
Definition at line 185 of file pybind_wrapper.cpp.
References param_print(), and xcs.
Referenced by pybind11_init_wrapper().
print_pset()
void XCS::print_pset (const bool print_cond, const bool print_act, const bool print_pred) inline
Prints the current population.
Parameters
[in] print_cond Whether to print the condition.
[in] print_act Whether to print the action.
[in] print_pred Whether to print the prediction.
Definition at line 218 of file pybind_wrapper.cpp.
References xcs, and xcsf_print_pset().
Referenced by pybind11_init_wrapper().
retrieve()
void XCS::retrieve (void) inline
Retrieves the stored population, setting it as current.
Definition at line 176 of file pybind_wrapper.cpp.
References xcs, and xcsf_retrieve_pset().
Referenced by pybind11_init_wrapper().
save()
size_t XCS::save (const char * filename) inline
Writes the entire current state of XCSF to a file.
Parameters
[in] filename String containing the name of the output file.
Returns
The total number of elements written.
Definition at line 147 of file pybind_wrapper.cpp.
References xcs, and xcsf_save().
Referenced by pybind11_init_wrapper().
score() [1/2]
double XCS::score (const py::array_t< double > test_X, const py::array_t< double > test_Y) inline
Returns the error over one sequential pass of the provided data.
Parameters
[in] test_X The input values to use for scoring.
[in] test_Y The true output values to use for scoring.
Returns
The average XCSF error using the loss function.
Definition at line 441 of file pybind_wrapper.cpp.
Referenced by pybind11_init_wrapper().
score() [2/2]
double XCS::score (const py::array_t< double > test_X, const py::array_t< double > test_Y, const int N) inline
Returns the error using N random samples from the provided data.
Parameters
[in] test_X The input values to use for scoring.
[in] test_Y The true output values to use for scoring.
[in] N The maximum number of samples to draw randomly for scoring.
Returns
The average XCSF error using the loss function.
Definition at line 454 of file pybind_wrapper.cpp.
References Input::n_samples, test_data, Input::x, Input::x_dim, xcs, xcs_supervised_score(), xcs_supervised_score_n(), Input::y, and Input::y_dim.
seed()
void XCS::seed (const uint32_t seed) inline
Definition at line 1378 of file pybind_wrapper.cpp.
References rand_init_seed().
Referenced by pybind11_init_wrapper().
set_action() [1/2]
void XCS::set_action (const std::string & type) inline
Sets the action type.
Parameters
[in] type String representing a name of an action type.
Definition at line 803 of file pybind_wrapper.cpp.
References action_param_set_type_string(), and xcs.
Referenced by pybind11_init_wrapper().
set_action() [2/2]
void XCS::set_action (const std::string & type, const py::dict & args) inline
Sets the action type and initialisation arguments.
Parameters
[in] type String representing a name of a condition type.
[in] args Python dictionary of argument name:value pairs.
Definition at line 1053 of file pybind_wrapper.cpp.
References XCSF::act, ACT_TYPE_NEURAL, action_param_set_type_string(), ArgsLayer::type, ArgsAct::type, unpack_act_neural(), and xcs.
set_alpha()
void XCS::set_alpha (const double a) inline
Definition at line 1228 of file pybind_wrapper.cpp.
References param_set_alpha(), and xcs.
Referenced by pybind11_init_wrapper().
set_beta()
void XCS::set_beta (const double a) inline
Definition at line 1234 of file pybind_wrapper.cpp.
References param_set_beta(), and xcs.
Referenced by pybind11_init_wrapper().
set_compaction()
void XCS::set_compaction (const bool a) inline
Definition at line 1306 of file pybind_wrapper.cpp.
References param_set_compaction(), and xcs.
Referenced by pybind11_init_wrapper().
set_condition() [1/2]
void XCS::set_condition (const std::string & type) inline
Sets the condition type.
Parameters
[in] type String representing a name of a condition type.
Definition at line 793 of file pybind_wrapper.cpp.
References cond_param_set_type_string(), and xcs.
Referenced by pybind11_init_wrapper().
set_condition() [2/2]
void XCS::set_condition (const std::string & type, const py::dict & args) inline
Sets the condition type and initialisation arguments.
Parameters
[in] type String representing a name of a condition type.
[in] args Python dictionary of argument name:value pairs.
Definition at line 824 of file pybind_wrapper.cpp.
References XCSF::cond, cond_param_set_type_string(), COND_TYPE_DGP, COND_TYPE_GP, COND_TYPE_HYPERELLIPSOID, COND_TYPE_HYPERRECTANGLE, COND_TYPE_NEURAL, COND_TYPE_TERNARY, RULE_TYPE_DGP, RULE_TYPE_NETWORK, RULE_TYPE_NEURAL, ArgsCond::type, unpack_cond_csr(), unpack_cond_dgp(), unpack_cond_gp(), unpack_cond_neural(), unpack_cond_ternary(), and xcs.
set_delta()
void XCS::set_delta (const double a) inline
Definition at line 1240 of file pybind_wrapper.cpp.
References param_set_delta(), and xcs.
Referenced by pybind11_init_wrapper().
set_e0()
void XCS::set_e0 (const double a) inline
Definition at line 1246 of file pybind_wrapper.cpp.
References param_set_e0(), and xcs.
Referenced by pybind11_init_wrapper().
set_ea_pred_reset()
void XCS::set_ea_pred_reset (const bool a) inline
Definition at line 1372 of file pybind_wrapper.cpp.
References ea_param_set_pred_reset(), and xcs.
Referenced by pybind11_init_wrapper().
set_ea_select_size()
void XCS::set_ea_select_size (const double a) inline
Definition at line 1330 of file pybind_wrapper.cpp.
References ea_param_set_select_size(), and xcs.
Referenced by pybind11_init_wrapper().
set_ea_select_type()
void XCS::set_ea_select_type (const char * a) inline
Definition at line 1324 of file pybind_wrapper.cpp.
References ea_param_set_type_string(), and xcs.
Referenced by pybind11_init_wrapper().
set_ea_subsumption()
void XCS::set_ea_subsumption (const bool a) inline
Definition at line 1366 of file pybind_wrapper.cpp.
References ea_param_set_subsumption(), and xcs.
Referenced by pybind11_init_wrapper().
set_err_reduc()
void XCS::set_err_reduc (const double a) inline
Definition at line 1354 of file pybind_wrapper.cpp.
References ea_param_set_err_reduc(), and xcs.
Referenced by pybind11_init_wrapper().
set_fit_reduc()
void XCS::set_fit_reduc (const double a) inline
Definition at line 1360 of file pybind_wrapper.cpp.
References ea_param_set_fit_reduc(), and xcs.
Referenced by pybind11_init_wrapper().
set_gamma()
void XCS::set_gamma (const double a) inline
Definition at line 1312 of file pybind_wrapper.cpp.
References param_set_gamma(), and xcs.
Referenced by pybind11_init_wrapper().
set_huber_delta()
void XCS::set_huber_delta (const double a) inline
Definition at line 1222 of file pybind_wrapper.cpp.
References param_set_huber_delta(), and xcs.
Referenced by pybind11_init_wrapper().
set_init_error()
void XCS::set_init_error (const double a) inline
Definition at line 1252 of file pybind_wrapper.cpp.
References param_set_init_error(), and xcs.
Referenced by pybind11_init_wrapper().
set_init_fitness()
void XCS::set_init_fitness (const double a) inline
Definition at line 1258 of file pybind_wrapper.cpp.
References param_set_init_fitness(), and xcs.
Referenced by pybind11_init_wrapper().
set_lambda()
void XCS::set_lambda (const int a) inline
Definition at line 1342 of file pybind_wrapper.cpp.
References ea_param_set_lambda(), and xcs.
Referenced by pybind11_init_wrapper().
set_loss_func()
void XCS::set_loss_func (const char * a) inline
Definition at line 1216 of file pybind_wrapper.cpp.
References param_set_loss_func_string(), and xcs.
Referenced by pybind11_init_wrapper().
set_m_probation()
void XCS::set_m_probation (const int a) inline
Definition at line 1270 of file pybind_wrapper.cpp.
References param_set_m_probation(), and xcs.
Referenced by pybind11_init_wrapper().
set_max_trials()
void XCS::set_max_trials (const int a) inline
Definition at line 1198 of file pybind_wrapper.cpp.
References param_set_max_trials(), and xcs.
Referenced by pybind11_init_wrapper().
set_nu()
void XCS::set_nu (const double a) inline
Definition at line 1264 of file pybind_wrapper.cpp.
References param_set_nu(), and xcs.
Referenced by pybind11_init_wrapper().
set_omp_num_threads()
void XCS::set_omp_num_threads (const int a) inline
Definition at line 1186 of file pybind_wrapper.cpp.
References param_set_omp_num_threads(), and xcs.
Referenced by pybind11_init_wrapper().
set_p_crossover()
void XCS::set_p_crossover (const double a) inline
Definition at line 1348 of file pybind_wrapper.cpp.
References ea_param_set_p_crossover(), and xcs.
Referenced by pybind11_init_wrapper().
set_p_explore()
void XCS::set_p_explore (const double a) inline
Definition at line 1318 of file pybind_wrapper.cpp.
References param_set_p_explore(), and xcs.
Referenced by pybind11_init_wrapper().
set_perf_trials()
void XCS::set_perf_trials (const int a) inline
Definition at line 1204 of file pybind_wrapper.cpp.
References param_set_perf_trials(), and xcs.
Referenced by pybind11_init_wrapper().
set_pop_init()
void XCS::set_pop_init (const bool a) inline
Definition at line 1192 of file pybind_wrapper.cpp.
References param_set_pop_init(), and xcs.
Referenced by pybind11_init_wrapper().
set_pop_max_size()
void XCS::set_pop_max_size (const int a) inline
Definition at line 1210 of file pybind_wrapper.cpp.
References param_set_pop_size(), and xcs.
Referenced by pybind11_init_wrapper().
set_prediction() [1/2]
void XCS::set_prediction (const std::string & type) inline
Sets the prediction type.
Parameters
[in] type String representing a name of a prediction type.
Definition at line 813 of file pybind_wrapper.cpp.
References pred_param_set_type_string(), and xcs.
Referenced by pybind11_init_wrapper().
set_prediction() [2/2]
void XCS::set_prediction (const std::string & type, const py::dict & args) inline
Sets the prediction type and initialisation arguments.
Parameters
[in] type String representing a name of a condition type.
[in] args Python dictionary of argument name:value pairs.
Definition at line 1093 of file pybind_wrapper.cpp.
References XCSF::pred, pred_param_set_type_string(), PRED_TYPE_NEURAL, PRED_TYPE_NLMS_LINEAR, PRED_TYPE_NLMS_QUADRATIC, PRED_TYPE_RLS_LINEAR, PRED_TYPE_RLS_QUADRATIC, ArgsLayer::type, ArgsPred::type, unpack_pred_neural(), unpack_pred_nlms(), unpack_pred_rls(), and xcs.
set_set_subsumption()
void XCS::set_set_subsumption (const bool a) inline
Definition at line 1288 of file pybind_wrapper.cpp.
References param_set_set_subsumption(), and xcs.
Referenced by pybind11_init_wrapper().
set_stateful()
void XCS::set_stateful (const bool a) inline
Definition at line 1300 of file pybind_wrapper.cpp.
References param_set_stateful(), and xcs.
Referenced by pybind11_init_wrapper().
set_teletransportation()
void XCS::set_teletransportation (const int a) inline
Definition at line 1294 of file pybind_wrapper.cpp.
References param_set_teletransportation(), and xcs.
Referenced by pybind11_init_wrapper().
set_theta_del()
void XCS::set_theta_del (const int a) inline
Definition at line 1276 of file pybind_wrapper.cpp.
References param_set_theta_del(), and xcs.
Referenced by pybind11_init_wrapper().
set_theta_ea()
void XCS::set_theta_ea (const double a) inline
Definition at line 1336 of file pybind_wrapper.cpp.
References ea_param_set_theta(), and xcs.
Referenced by pybind11_init_wrapper().
set_theta_sub()
void XCS::set_theta_sub (const int a) inline
Definition at line 1282 of file pybind_wrapper.cpp.
References param_set_theta_sub(), and xcs.
Referenced by pybind11_init_wrapper().
store()
void XCS::store (void) inline
Stores the current population in memory for later retrieval.
Definition at line 167 of file pybind_wrapper.cpp.
References xcs, and xcsf_store_pset().
Referenced by pybind11_init_wrapper().
unpack_act_neural()
void XCS::unpack_act_neural (const py::dict & args) inline
Sets parameters used by neural network actions.
Parameters
[in] args Python dictionary of argument name:value pairs.
Definition at line 1066 of file pybind_wrapper.cpp.
References XCSF::act, ArgsAct::largs, layer_args_free(), layer_args_init(), layer_args_validate(), ArgsLayer::next, unpack_layer_params(), and xcs.
Referenced by set_action().
unpack_cond_csr()
void XCS::unpack_cond_csr (const py::dict & args) inline
Sets parameters used by center-spread conditions.
Parameters
[in] args Python dictionary of argument name:value pairs.
Definition at line 857 of file pybind_wrapper.cpp.
References cond_param_set_eta(), cond_param_set_max(), cond_param_set_min(), cond_param_set_spread_min(), and xcs.
Referenced by set_condition().
unpack_cond_dgp()
void XCS::unpack_cond_dgp (const py::dict & args) inline
Sets parameters used by dynamical GP graph conditions.
Parameters
[in] args Python dictionary of argument name:value pairs.
Definition at line 910 of file pybind_wrapper.cpp.
References XCSF::cond, ArgsCond::dargs, graph_param_set_evolve_cycles(), graph_param_set_max_k(), graph_param_set_max_t(), graph_param_set_n(), graph_param_set_n_inputs(), XCSF::x_dim, and xcs.
Referenced by set_condition().
unpack_cond_gp()
void XCS::unpack_cond_gp (const py::dict & args) inline
Sets parameters used by tree-GP conditions.
Parameters
[in] args Python dictionary of argument name:value pairs.
Definition at line 881 of file pybind_wrapper.cpp.
References XCSF::cond, ArgsCond::targs, tree_args_init_constants(), tree_param_set_init_depth(), tree_param_set_max(), tree_param_set_max_len(), tree_param_set_min(), tree_param_set_n_constants(), tree_param_set_n_inputs(), XCSF::x_dim, and xcs.
Referenced by set_condition().
unpack_cond_neural()
void XCS::unpack_cond_neural (const py::dict & args) inline
Sets parameters used by neural network conditions.
Parameters
[in] args Python dictionary of argument name:value pairs.
Definition at line 956 of file pybind_wrapper.cpp.
References XCSF::cond, ArgsCond::largs, layer_args_free(), layer_args_init(), layer_args_validate(), ArgsLayer::next, unpack_layer_params(), and xcs.
Referenced by set_condition().
unpack_cond_ternary()
void XCS::unpack_cond_ternary (const py::dict & args) inline
Sets parameters used by ternary conditions.
Parameters
[in] args Python dictionary of argument name:value pairs.
Definition at line 936 of file pybind_wrapper.cpp.
References cond_param_set_bits(), cond_param_set_p_dontcare(), and xcs.
Referenced by set_condition().
unpack_layer_params()
void XCS::unpack_layer_params (struct ArgsLayer * larg, const py::dict & args) inline
Sets parameters used by a neural network layer.
Parameters
[in] larg Layer parameter structure to set.
[in] args Python dictionary of argument name:value pairs.
Definition at line 983 of file pybind_wrapper.cpp.
References ArgsLayer::channels, ArgsLayer::decay, ArgsLayer::eta, ArgsLayer::eta_min, ArgsLayer::evolve_connect, ArgsLayer::evolve_eta, ArgsLayer::evolve_functions, ArgsLayer::evolve_neurons, ArgsLayer::evolve_weights, ArgsLayer::function, ArgsLayer::height, layer_type_as_int(), ArgsLayer::max_neuron_grow, ArgsLayer::momentum, ArgsLayer::n_init, ArgsLayer::n_inputs, ArgsLayer::n_max, neural_activation_as_int(), ArgsLayer::pad, ArgsLayer::probability, ArgsLayer::recurrent_function, ArgsLayer::scale, ArgsLayer::sgd_weights, ArgsLayer::size, ArgsLayer::stride, ArgsLayer::type, ArgsLayer::width, XCSF::x_dim, and xcs.
Referenced by unpack_act_neural(), unpack_cond_neural(), and unpack_pred_neural().
unpack_pred_neural()
void XCS::unpack_pred_neural (const py::dict & args) inline
Sets parameters used by neural network predictions.
Parameters
[in] args Python dictionary of argument name:value pairs.
Definition at line 1118 of file pybind_wrapper.cpp.
References ArgsPred::largs, layer_args_free(), layer_args_init(), layer_args_validate(), ArgsLayer::next, XCSF::pred, unpack_layer_params(), and xcs.
Referenced by set_prediction().
unpack_pred_nlms()
void XCS::unpack_pred_nlms (const py::dict & args) inline
Sets parameters used by least mean squares predictions.
Parameters
[in] args Python dictionary of argument name:value pairs.
Definition at line 1144 of file pybind_wrapper.cpp.
References pred_param_set_eta(), pred_param_set_eta_min(), pred_param_set_evolve_eta(), pred_param_set_x0(), and xcs.
Referenced by set_prediction().
unpack_pred_rls()
void XCS::unpack_pred_rls (const py::dict & args) inline
Sets parameters used by recursive least mean squares predictions.
Parameters
[in] args Python dictionary of argument name:value pairs.
Definition at line 1168 of file pybind_wrapper.cpp.
References pred_param_set_lambda(), pred_param_set_scale_factor(), pred_param_set_x0(), and xcs.
Referenced by set_prediction().
update()
void XCS::update (const double reward, const bool done) inline
Creates the action set using the previously selected action, updates the classifiers, and runs the EA on explore steps.
Parameters
[in] reward The reward from performing the action.
[in] done Whether the environment is in a terminal state.
Definition at line 304 of file pybind_wrapper.cpp.
References action, payoff, state, xcs, and xcs_rl_update().
Referenced by pybind11_init_wrapper().
version_build()
int XCS::version_build (void) inline
Returns the XCSF build version number.
Returns
Build version number.
Definition at line 136 of file pybind_wrapper.cpp.
References VERSION_BUILD.
Referenced by pybind11_init_wrapper().
version_major()
int XCS::version_major (void) inline
Returns the XCSF major version number.
Returns
Major version number.
Definition at line 116 of file pybind_wrapper.cpp.
References VERSION_MAJOR.
Referenced by pybind11_init_wrapper().
version_minor()
int XCS::version_minor (void) inline
Returns the XCSF minor version number.
Returns
Minor version number.
Definition at line 126 of file pybind_wrapper.cpp.
References VERSION_MINOR.
Referenced by pybind11_init_wrapper().
Field Documentation
action
int XCS::action private
Current action for RL.
Definition at line 63 of file pybind_wrapper.cpp.
Referenced by decision(), end_step(), error(), fit(), update(), and XCS().
payoff
double XCS::payoff private
Current reward for RL.
Definition at line 64 of file pybind_wrapper.cpp.
Referenced by end_step(), error(), update(), and XCS().
state
double* XCS::state private
Current input state for RL.
Definition at line 62 of file pybind_wrapper.cpp.
Referenced by decision(), end_step(), fit(), update(), and XCS().
test_data
struct Input* XCS::test_data private
Test data for supervised learning.
Definition at line 66 of file pybind_wrapper.cpp.
Referenced by fit(), score(), and XCS().
train_data
struct Input* XCS::train_data private
Training data for supervised learning.
Definition at line 65 of file pybind_wrapper.cpp.
Referenced by fit(), and XCS().
xcs
struct XCSF XCS::xcs private
XCSF data structure.
Definition at line 61 of file pybind_wrapper.cpp.
Referenced by ae_to_classifier(), decision(), end_step(), end_trial(), error(), fit(), get_alpha(), get_aset_size(), get_beta(), get_compaction(), get_delta(), get_e0(), get_ea_pred_reset(), get_ea_select_size(), get_ea_select_type(), get_ea_subsumption(), get_err_reduc(), get_fit_reduc(), get_gamma(), get_huber_delta(), get_init_error(), get_init_fitness(), get_lambda(), get_loss_func(), get_m_probation(), get_max_trials(), get_mfrac(), get_mset_size(), get_n_actions(), get_nu(), get_omp_num_threads(), get_p_crossover(), get_p_explore(), get_perf_trials(), get_pop_init(), get_pop_max_size(), get_pset_mean_cond_connections(), get_pset_mean_cond_layers(), get_pset_mean_cond_neurons(), get_pset_mean_cond_size(), get_pset_mean_pred_connections(), get_pset_mean_pred_eta(), get_pset_mean_pred_layers(), get_pset_mean_pred_neurons(), get_pset_mean_pred_size(), get_pset_num(), get_pset_size(), get_set_subsumption(), get_stateful(), get_teletransportation(), get_theta_del(), get_theta_ea(), get_theta_sub(), get_time(), get_x_dim(), get_y_dim(), init_step(), init_trial(), load(), pred_expand(), predict(), print_params(), print_pset(), retrieve(), save(), score(), set_action(), set_alpha(), set_beta(), set_compaction(), set_condition(), set_delta(), set_e0(), set_ea_pred_reset(), set_ea_select_size(), set_ea_select_type(), set_ea_subsumption(), set_err_reduc(), set_fit_reduc(), set_gamma(), set_huber_delta(), set_init_error(), set_init_fitness(), set_lambda(), set_loss_func(), set_m_probation(), set_max_trials(), set_nu(), set_omp_num_threads(), set_p_crossover(), set_p_explore(), set_perf_trials(), set_pop_init(), set_pop_max_size(), set_prediction(), set_set_subsumption(), set_stateful(), set_teletransportation(), set_theta_del(), set_theta_ea(), set_theta_sub(), store(), unpack_act_neural(), unpack_cond_csr(), unpack_cond_dgp(), unpack_cond_gp(), unpack_cond_neural(), unpack_cond_ternary(), unpack_layer_params(), unpack_pred_neural(), unpack_pred_nlms(), unpack_pred_rls(), update(), and XCS().
The documentation for this class was generated from the following file:
pybind_wrapper.cpp