XCSF: clset.c File Reference
clset.c File Reference
Functions operating on sets of classifiers.
#include "clset.h"
#include "cl.h"
#include "utils.h"
Macros
#define MAX_COVER (1000000)
Maximum number of covering attempts.
Functions
static void clset_pset_never_match (const struct XCSF *xcsf, struct Clist **del, struct Clist **delprev)
Finds a rule in the population that never matches an input.
static void clset_pset_roulette (const struct XCSF *xcsf, struct Clist **del, struct Clist **delprev)
Selects a classifier from the population for deletion via roulette.
static void clset_pset_del (struct XCSF *xcsf)
Deletes a single classifier from the population set.
static bool clset_action_coverage (const struct XCSF *xcsf, bool *act_covered)
Checks whether each action is covered by the match set.
static void clset_cover (struct XCSF *xcsf, const double *x)
Ensures all possible actions are covered by the match set.
static void clset_update_fit (const struct XCSF *xcsf, const struct Set *set)
Updates the fitness of classifiers in the set.
static void clset_subsumption (struct XCSF *xcsf, struct Set *set)
Performs set subsumption.
static double clset_total_time (const struct Set *set)
Calculates the total time stamps of classifiers in the set.
void clset_pset_init (struct XCSF *xcsf)
Initialises a new population of random classifiers.
void clset_init (struct Set *set)
Initialises a new set.
void clset_pset_enforce_limit (struct XCSF *xcsf)
Enforces the maximum population size limit.
void clset_match (struct XCSF *xcsf, const double *x)
Constructs the match set - forward propagates conditions and actions.
void clset_action (struct XCSF *xcsf, const int action)
Constructs the action set from the match set.
void clset_add (struct Set *set, struct Cl *c)
Adds a classifier to the set.
void clset_update (struct XCSF *xcsf, struct Set *set, const double *x, const double *y, const bool cur)
Provides reinforcement to the set and performs set subsumption.
void clset_validate (struct Set *set)
Removes classifiers with 0 numerosity from the set.
void clset_print (const struct XCSF *xcsf, const struct Set *set, const bool print_cond, const bool print_act, const bool print_pred)
Prints the classifiers in the set.
void clset_set_times (const struct XCSF *xcsf, const struct Set *set)
Sets the time stamps for classifiers in the set.
double clset_total_fit (const struct Set *set)
Calculates the total fitness of classifiers in the set.
double clset_mean_time (const struct Set *set)
Calculates the mean time stamp of classifiers in the set.
void clset_free (struct Set *set)
Frees the set, but not the classifiers.
void clset_kill (const struct XCSF *xcsf, struct Set *set)
Frees the set and the classifiers.
size_t clset_pset_save (const struct XCSF *xcsf, FILE *fp)
Writes the population set to a file.
size_t clset_pset_load (struct XCSF *xcsf, FILE *fp)
Reads the population set from a file.
double clset_mean_cond_size (const struct XCSF *xcsf, const struct Set *set)
Calculates the mean condition size of classifiers in the set.
double clset_mean_pred_size (const struct XCSF *xcsf, const struct Set *set)
Calculates the mean prediction size of classifiers in the set.
double clset_mfrac (const struct XCSF *xcsf)
Returns the fraction of inputs matched by the most general rule with error below E0. If no rules below E0, the lowest error rule is used.
char * clset_json_export (const struct XCSF *xcsf, const struct Set *set, const bool return_cond, const bool return_act, const bool return_pred)
Returns a json formatted string representation of a classifier set.
void clset_json_insert (struct XCSF *xcsf, const cJSON *json)
Creates a classifier from cJSON and inserts in the population set.
Detailed Description
Functions operating on sets of classifiers.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2021.
Definition in file clset.c.
Macro Definition Documentation
MAX_COVER
#define MAX_COVER (1000000)
Maximum number of covering attempts.
Definition at line 28 of file clset.c.
Function Documentation
clset_action()
void clset_action (struct XCSF * xcsf, const int action)
Constructs the action set from the match set.
Parameters
[in] xcsf The XCSF data structure.
[in] action The action used to build the set.
Definition at line 378 of file clset.c.
References Cl::action, Clist::cl, clset_add(), and Clist::next.
Referenced by xcs_rl_update().
clset_action_coverage()
static bool clset_action_coverage (const struct XCSF * xcsf, bool * act_covered) static
Checks whether each action is covered by the match set.
Parameters
[in] xcsf The XCSF data structure.
[out] act_covered Vector specifying whether each action is covered.
Returns
Whether all actions are covered.
Definition at line 137 of file clset.c.
References Cl::action, Clist::cl, and Clist::next.
Referenced by clset_cover().
clset_add()
void clset_add (struct Set * set, struct Cl * c)
Adds a classifier to the set.
Parameters
[in] set The set to add the classifier.
[in] c The classifier to add.
Definition at line 397 of file clset.c.
References Clist::cl, Set::list, Clist::next, Cl::num, Set::num, and Set::size.
Referenced by clset_action(), clset_cover(), clset_json_insert(), clset_match(), clset_pset_del(), clset_pset_init(), clset_pset_load(), clset_subsumption(), ea_add(), ea_subsume(), and xcsf_store_pset().
clset_cover()
static void clset_cover (struct XCSF * xcsf, const double * x) static
Ensures all possible actions are covered by the match set.
Parameters
[in] xcsf The XCSF data structure.
[in] x The input state.
Definition at line 159 of file clset.c.
References cl_cover(), cl_init(), clset_action_coverage(), clset_add(), clset_pset_enforce_limit(), clset_validate(), and MAX_COVER.
Referenced by clset_match().
clset_free()
void clset_free (struct Set * set)
Frees the set, but not the classifiers.
Parameters
[in] set The set to free.
Definition at line 546 of file clset.c.
References Set::list, Clist::next, Set::num, and Set::size.
Referenced by xcs_rl_end_step(), xcs_rl_end_trial(), and xcs_supervised_trial().
clset_init()
void clset_init (struct Set * set)
Initialises a new set.
Parameters
[in] set The set to be initialised.
Definition at line 302 of file clset.c.
References Set::list, Set::num, and Set::size.
Referenced by clset_pset_load(), xcs_rl_init_step(), xcs_rl_init_trial(), xcs_supervised_trial(), xcsf_init(), xcsf_load(), and xcsf_retrieve_pset().
clset_json_export()
char* clset_json_export (const struct XCSF * xcsf, const struct Set * set, const bool return_cond, const bool return_act, const bool return_pred)
Returns a json formatted string representation of a classifier set.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to be returned.
[in] return_cond Whether to return the condition.
[in] return_act Whether to return the action.
[in] return_pred Whether to return the prediction.
Returns
String encoded in json format.
Definition at line 708 of file clset.c.
References Clist::cl, cl_json_export(), Set::list, and Clist::next.
Referenced by clset_print(), and XCS::json_export().
clset_json_insert()
void clset_json_insert (struct XCSF * xcsf, const cJSON * json)
Creates a classifier from cJSON and inserts in the population set.
Parameters
[in,out] xcsf The XCSF data structure.
[in] json cJSON object.
Definition at line 734 of file clset.c.
References cl_json_import(), clset_add(), and clset_pset_enforce_limit().
Referenced by XCS::json_insert(), and XCS::json_insert_cl().
clset_kill()
void clset_kill (const struct XCSF * xcsf, struct Set * set)
Frees the set and the classifiers.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to free.
Definition at line 564 of file clset.c.
References Clist::cl, cl_free(), Set::list, Clist::next, Set::num, and Set::size.
Referenced by xcs_rl_end_trial(), xcs_supervised_trial(), xcsf_free(), xcsf_load(), xcsf_retrieve_pset(), and xcsf_store_pset().
clset_match()
void clset_match (struct XCSF * xcsf, const double * x)
Constructs the match set - forward propagates conditions and actions.
Processes the matching conditions and actions for each classifier in the population. If a classifier matches, it is added to the match set. Covering is performed if any actions are unrepresented.
Parameters
[in] xcsf The XCSF data structure.
[in] x The input state.
Definition at line 330 of file clset.c.
References Clist::cl, cl_action(), cl_m(), cl_match(), clset_add(), clset_cover(), clset_mfrac(), and Clist::next.
Referenced by xcs_rl_decision(), xcs_rl_fit(), and xcs_supervised_trial().
clset_mean_cond_size()
double clset_mean_cond_size (const struct XCSF * xcsf, const struct Set * set)
Calculates the mean condition size of classifiers in the set.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to calculate the mean condition size.
Returns
The mean condition size of classifiers in the set.
Definition at line 627 of file clset.c.
References Clist::cl, cl_cond_size(), Set::list, and Clist::next.
Referenced by XCS::get_pset_mean_cond_size().
clset_mean_pred_size()
double clset_mean_pred_size (const struct XCSF * xcsf, const struct Set * set)
Calculates the mean prediction size of classifiers in the set.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to calculate the mean prediction size.
Returns
The mean prediction size of classifiers in the set.
Definition at line 647 of file clset.c.
References Clist::cl, cl_pred_size(), Set::list, and Clist::next.
Referenced by XCS::get_pset_mean_pred_size().
clset_mean_time()
double clset_mean_time (const struct Set * set)
Calculates the mean time stamp of classifiers in the set.
Parameters
[in] set The set to calculate the mean time.
Returns
The mean time of classifiers in the set.
Definition at line 536 of file clset.c.
References clset_total_time(), and Set::num.
Referenced by ea().
clset_mfrac()
double clset_mfrac (const struct XCSF * xcsf)
Returns the fraction of inputs matched by the most general rule with error below E0. If no rules below E0, the lowest error rule is used.
Parameters
[in] xcsf The XCSF data structure.
Returns
The fraction of inputs matched.
Definition at line 667 of file clset.c.
References Clist::cl, cl_mfrac(), Cl::err, Cl::exp, and Clist::next.
Referenced by clset_match().
clset_print()
void clset_print (const struct XCSF * xcsf, const struct Set * set, const bool print_cond, const bool print_act, const bool print_pred)
Prints the classifiers in the set.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to print.
[in] print_cond Whether to print the conditions.
[in] print_act Whether to print the actions.
[in] print_pred Whether to print the predictions.
Definition at line 489 of file clset.c.
References clset_json_export().
Referenced by xcsf_print_pset().
clset_pset_del()
static void clset_pset_del (struct XCSF * xcsf) static
Deletes a single classifier from the population set.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 104 of file clset.c.
References Clist::cl, clset_add(), clset_pset_never_match(), clset_pset_roulette(), Clist::next, and Cl::num.
Referenced by clset_pset_enforce_limit().
clset_pset_enforce_limit()
void clset_pset_enforce_limit (struct XCSF * xcsf)
Enforces the maximum population size limit.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 314 of file clset.c.
References clset_pset_del().
Referenced by clset_cover(), clset_json_insert(), and ea().
clset_pset_init()
void clset_pset_init (struct XCSF * xcsf)
Initialises a new population of random classifiers.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 285 of file clset.c.
References cl_init(), cl_rand(), and clset_add().
Referenced by xcs_rl_init_trial(), and xcs_supervised_fit().
clset_pset_load()
size_t clset_pset_load (struct XCSF * xcsf, FILE * fp)
Reads the population set from a file.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 604 of file clset.c.
References cl_load(), clset_add(), and clset_init().
Referenced by xcsf_load().
clset_pset_never_match()
static void clset_pset_never_match (const struct XCSF * xcsf, struct Clist ** del, struct Clist ** delprev) static
Finds a rule in the population that never matches an input.
Parameters
[in] xcsf The XCSF data structure.
[out] del A pointer to the classifier to be deleted, if one is found.
[out] delprev A pointer to the rule previous to the one being deleted.
Definition at line 37 of file clset.c.
References Cl::age, Clist::cl, Cl::mtotal, and Clist::next.
Referenced by clset_pset_del().
clset_pset_roulette()
static void clset_pset_roulette (const struct XCSF * xcsf, struct Clist ** del, struct Clist ** delprev) static
Selects a classifier from the population for deletion via roulette.
If compaction is enabled and the average system error is below E0, two classifiers are selected using roulette wheel selection with the deletion vote and the rule with the largest condition + prediction size is chosen. For fixed-length representations, the effect is the same as one roulete spin.
Parameters
[in] xcsf The XCSF data structure.
[out] del A pointer to the rule to be deleted.
[out] delprev A pointer to the rule previous to the one being deleted.
Definition at line 65 of file clset.c.
References Clist::cl, cl_cond_size(), cl_del_vote(), cl_pred_size(), clset_total_fit(), Clist::next, and rand_uniform().
Referenced by clset_pset_del().
clset_pset_save()
size_t clset_pset_save (const struct XCSF * xcsf, FILE * fp)
Writes the population set to a file.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 584 of file clset.c.
References Clist::cl, cl_save(), and Clist::next.
Referenced by xcsf_save().
clset_set_times()
void clset_set_times (const struct XCSF * xcsf, const struct Set * set)
Sets the time stamps for classifiers in the set.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to update the time stamps.
Definition at line 504 of file clset.c.
References Clist::cl, Set::list, Clist::next, and Cl::time.
Referenced by ea().
clset_subsumption()
static void clset_subsumption (struct XCSF * xcsf, struct Set * set) static
Performs set subsumption.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to perform subsumption.
Definition at line 230 of file clset.c.
References Clist::cl, cl_general(), cl_subsumer(), clset_add(), clset_validate(), Set::list, Clist::next, and Cl::num.
Referenced by clset_update().
clset_total_fit()
double clset_total_fit (const struct Set * set)
Calculates the total fitness of classifiers in the set.
Parameters
[in] set The set to calculate the total fitness.
Returns
The total fitness of classifiers in the set.
Definition at line 519 of file clset.c.
References Clist::cl, Cl::fit, Set::list, and Clist::next.
Referenced by clset_pset_roulette(), and ea_select().
clset_total_time()
static double clset_total_time (const struct Set * set) static
Calculates the total time stamps of classifiers in the set.
Parameters
[in] set The set to calculate the total time.
Returns
The total time of classifiers in the set.
Definition at line 269 of file clset.c.
References Clist::cl, Set::list, Clist::next, Cl::num, and Cl::time.
Referenced by clset_mean_time().
clset_update()
void clset_update (struct XCSF * xcsf, struct Set * set, const double * x, const double * y, const bool cur)
Provides reinforcement to the set and performs set subsumption.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to provide reinforcement.
[in] x The input state.
[in] y The payoff from the environment.
[in] cur Whether the update is for the current or previous state.
Definition at line 422 of file clset.c.
References Clist::cl, cl_update(), clset_subsumption(), clset_update_fit(), Set::list, Clist::next, Set::num, and Set::size.
Referenced by xcs_rl_update(), and xcs_supervised_trial().
clset_update_fit()
static void clset_update_fit (const struct XCSF * xcsf, const struct Set * set) static
Updates the fitness of classifiers in the set.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to update.
Definition at line 205 of file clset.c.
References Clist::cl, cl_acc(), cl_update_fit(), Set::list, Clist::next, Cl::num, and Set::size.
Referenced by clset_update().
clset_validate()
void clset_validate (struct Set * set)
Removes classifiers with 0 numerosity from the set.
Parameters
[in] set The set to validate.
Definition at line 454 of file clset.c.
References Clist::cl, Set::list, Clist::next, Cl::num, Set::num, and Set::size.
Referenced by clset_cover(), clset_subsumption(), and xcs_rl_update().