XCSF: clset_neural.h File Reference
clset_neural.h File Reference
Functions operating on sets of neural classifiers.
#include "xcsf.h"
Functions
double clset_mean_cond_connections (const struct XCSF *xcsf, const struct Set *set, const int layer)
Calculates the mean number of condition connections in the set.
double clset_mean_cond_layers (const struct XCSF *xcsf, const struct Set *set)
Calculates the mean number of condition layers in the set.
double clset_mean_cond_neurons (const struct XCSF *xcsf, const struct Set *set, const int layer)
Calculates the mean number of condition neurons for a given layer.
double clset_mean_pred_connections (const struct XCSF *xcsf, const struct Set *set, const int layer)
Calculates the mean number of prediction connections in the set.
double clset_mean_pred_eta (const struct XCSF *xcsf, const struct Set *set, const int layer)
Calculates the mean prediction layer ETA of classifiers in the set.
double clset_mean_pred_layers (const struct XCSF *xcsf, const struct Set *set)
Calculates the mean number of prediction layers in the set.
double clset_mean_pred_neurons (const struct XCSF *xcsf, const struct Set *set, const int layer)
Calculates the mean number of prediction neurons for a given layer.
Detailed Description
Functions operating on sets of neural classifiers.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file clset_neural.h.
Function Documentation
clset_mean_cond_connections()
double clset_mean_cond_connections (const struct XCSF * xcsf, const struct Set * set, const int layer)
Calculates the mean number of condition connections in the set.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to calculate the mean.
[in] layer The position of layer to calculate.
Returns
The mean number of connections in the layer.
Definition at line 93 of file clset_neural.c.
References Clist::cl, cond_neural_connections(), COND_TYPE_NEURAL, Set::list, Clist::next, and RULE_TYPE_NEURAL.
Referenced by XCS::get_pset_mean_cond_connections().
clset_mean_cond_layers()
double clset_mean_cond_layers (const struct XCSF * xcsf, const struct Set * set)
Calculates the mean number of condition layers in the set.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to calculate the mean.
Returns
The mean number of layers.
Definition at line 39 of file clset_neural.c.
References Clist::cl, cond_neural_layers(), COND_TYPE_NEURAL, Set::list, Clist::next, and RULE_TYPE_NEURAL.
Referenced by XCS::get_pset_mean_cond_layers().
clset_mean_cond_neurons()
double clset_mean_cond_neurons (const struct XCSF * xcsf, const struct Set * set, const int layer)
Calculates the mean number of condition neurons for a given layer.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to calculate the mean.
[in] layer The neural network layer position.
Returns
The mean number of neurons in the layer.
Definition at line 65 of file clset_neural.c.
References Clist::cl, cond_neural_neurons(), COND_TYPE_NEURAL, Set::list, Clist::next, and RULE_TYPE_NEURAL.
Referenced by XCS::get_pset_mean_cond_neurons().
clset_mean_pred_connections()
double clset_mean_pred_connections (const struct XCSF * xcsf, const struct Set * set, const int layer)
Calculates the mean number of prediction connections in the set.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to calculate the mean.
[in] layer The position of layer to calculate.
Returns
The mean number of connections in the layer.
Definition at line 200 of file clset_neural.c.
References Clist::cl, Set::list, Clist::next, pred_neural_connections(), and PRED_TYPE_NEURAL.
Referenced by XCS::get_pset_mean_pred_connections().
clset_mean_pred_eta()
double clset_mean_pred_eta (const struct XCSF * xcsf, const struct Set * set, const int layer)
Calculates the mean prediction layer ETA of classifiers in the set.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to calculate the mean.
[in] layer The position of layer to calculate.
Returns
The mean prediction layer ETA of classifiers in the set.
Definition at line 173 of file clset_neural.c.
References Clist::cl, Set::list, Clist::next, pred_neural_eta(), and PRED_TYPE_NEURAL.
Referenced by XCS::get_pset_mean_pred_eta().
clset_mean_pred_layers()
double clset_mean_pred_layers (const struct XCSF * xcsf, const struct Set * set)
Calculates the mean number of prediction layers in the set.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to calculate the mean.
Returns
The mean number of layers.
Definition at line 147 of file clset_neural.c.
References Clist::cl, Set::list, Clist::next, pred_neural_layers(), and PRED_TYPE_NEURAL.
Referenced by XCS::get_pset_mean_pred_layers().
clset_mean_pred_neurons()
double clset_mean_pred_neurons (const struct XCSF * xcsf, const struct Set * set, const int layer)
Calculates the mean number of prediction neurons for a given layer.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to calculate the mean.
[in] layer The neural network layer position.
Returns
The mean number of neurons in the layer.
Definition at line 121 of file clset_neural.c.
References Clist::cl, Set::list, Clist::next, pred_neural_neurons(), and PRED_TYPE_NEURAL.
Referenced by XCS::get_pset_mean_pred_neurons().