XCSF: CMakeLists.txt File Reference
CMakeLists.txt File Reference
Functions
set (XCSF_SOURCES act_integer.c act_neural.c action.c blas.c cl.c clset.c clset_neural.c cond_dgp.c cond_dummy.c cond_ellipsoid.c cond_gp.c cond_neural.c cond_rectangle.c cond_ternary.c condition.c config.c dgp.c ea.c env.c env_csv.c env_maze.c env_mux.c gp.c image.c loss.c neural.c neural_activations.c neural_layer.c neural_layer_avgpool.c neural_layer_connected.c neural_layer_convolutional.c neural_layer_dropout.c neural_layer_lstm.c neural_layer_maxpool.c neural_layer_noise.c neural_layer_recurrent.c neural_layer_softmax.c neural_layer_upsample.c pa.c param.c perf.c pred_constant.c pred_neural.c pred_nlms.c pred_rls.c prediction.c rule_dgp.c rule_neural.c sam.c utils.c xcs_rl.c xcs_supervised.c xcsf.c) set(XCSF_HEADERS act_integer.h act_neural.h action.h blas.h cl.h clset.h clset_neural.h cond_dgp.h cond_dummy.h cond_ellipsoid.h cond_gp.h cond_neural.h cond_rectangle.h cond_ternary.h condition.h config.h dgp.h ea.h env.h env_csv.h env_maze.h env_mux.h gp.h image.h loss.h neural.h neural_activations.h neural_layer.h neural_layer_avgpool.h neural_layer_connected.h neural_layer_convolutional.h neural_layer_dropout.h neural_layer_lstm.h neural_layer_maxpool.h neural_layer_noise.h neural_layer_recurrent.h neural_layer_softmax.h neural_layer_upsample.h pa.h param.h perf.h pred_constant.h pred_neural.h pred_nlms.h pred_rls.h prediction.h rule_dgp.h rule_neural.h sam.h utils.h xcs_rl.h xcs_supervised.h xcsf.h) set(dSFMT_SOURCES $
Function Documentation
set()
set (XCSF_SOURCES act_integer.c act_neural.c action.c blas.c cl.c clset.c clset_neural.c cond_dgp.c cond_dummy.c cond_ellipsoid.c cond_gp.c cond_neural.c cond_rectangle.c cond_ternary.c condition.c config.c dgp.c ea.c env.c env_csv.c env_maze.c env_mux.c gp.c image.c loss.c neural.c neural_activations.c neural_layer.c neural_layer_avgpool.c neural_layer_connected.c neural_layer_convolutional.c neural_layer_dropout.c neural_layer_lstm.c neural_layer_maxpool.c neural_layer_noise.c neural_layer_recurrent.c neural_layer_softmax.c neural_layer_upsample.c pa.c param.c perf.c pred_constant.c pred_neural.c pred_nlms.c pred_rls.c prediction.c rule_dgp.c rule_neural.c sam.c utils.c xcs_rl.c xcs_supervised.c xcsf. c)
Definition at line 18 of file CMakeLists.txt.
Referenced by clset_add(), clset_free(), clset_init(), clset_kill(), clset_mean_cond_connections(), clset_mean_cond_layers(), clset_mean_cond_neurons(), clset_mean_cond_size(), clset_mean_pred_connections(), clset_mean_pred_eta(), clset_mean_pred_layers(), clset_mean_pred_neurons(), clset_mean_pred_size(), clset_mean_time(), clset_print(), clset_set_times(), clset_subsumption(), clset_total_fit(), clset_total_time(), clset_update(), clset_update_fit(), clset_validate(), ea(), ea_add(), ea_select(), ea_select_rw(), ea_select_tournament(), ea_subsume(), and pa_build().