XCSF: cond_ellipsoid.h File Reference
cond_ellipsoid.h File Reference
Hyperellipsoid condition functions.
#include "condition.h"
#include "xcsf.h"
Data Structures
struct CondEllipsoid
Hyperellipsoid condition data structure.
Functions
bool cond_ellipsoid_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Performs uniform crossover with two hyperellipsoid conditions.
bool cond_ellipsoid_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Returns whether classifier c1 has a condition more general than c2.
bool cond_ellipsoid_match (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Calculates whether a hyperellipsoid condition matches an input.
bool cond_ellipsoid_mutate (const struct XCSF *xcsf, const struct Cl *c)
Mutates a hyperellipsoid condition with the self-adaptive rate.
void cond_ellipsoid_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies a hyperellipsoid condition from one classifier to another.
void cond_ellipsoid_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Generates a hyperellipsoid that matches the current input.
void cond_ellipsoid_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by a hyperellipsoid condition.
void cond_ellipsoid_init (const struct XCSF *xcsf, struct Cl *c)
Creates and initialises a hyperellipsoid condition.
void cond_ellipsoid_print (const struct XCSF *xcsf, const struct Cl *c)
Prints a hyperellipsoid condition.
void cond_ellipsoid_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Updates a hyperellipsoid, sliding the centers towards the mean input.
double cond_ellipsoid_size (const struct XCSF *xcsf, const struct Cl *c)
Returns the size of a hyperellipsoid condition.
size_t cond_ellipsoid_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes a hyperellipsoid condition to a file.
size_t cond_ellipsoid_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads a hyperellipsoid condition from a file.
char * cond_ellipsoid_json_export (const struct XCSF *xcsf, const struct Cl *c)
Returns a json formatted string representation of a hyperellipsoid.
void cond_ellipsoid_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Creates a hyperellipsoid from a cJSON object.
Variables
static struct CondVtbl const cond_ellipsoid_vtbl
Hyperellipsoid condition implemented functions.
Detailed Description
Hyperellipsoid condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2021.
Definition in file cond_ellipsoid.h.
Function Documentation
cond_ellipsoid_copy()
void cond_ellipsoid_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Copies a hyperellipsoid condition from one classifier to another.
Parameters
[in] xcsf XCSF data structure.
[in] dest Destination classifier.
[in] src Source classifier.
Definition at line 103 of file cond_ellipsoid.c.
References CondEllipsoid::center, Cl::cond, CondEllipsoid::mu, N_MU, and CondEllipsoid::spread.
cond_ellipsoid_cover()
void cond_ellipsoid_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Generates a hyperellipsoid that matches the current input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is being covered.
[in] x Input state to cover.
Definition at line 124 of file cond_ellipsoid.c.
References CondEllipsoid::center, Cl::cond, rand_uniform(), and CondEllipsoid::spread.
cond_ellipsoid_crossover()
bool cond_ellipsoid_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Performs uniform crossover with two hyperellipsoid conditions.
Parameters
[in] xcsf XCSF data structure.
[in] c1 First classifier whose condition is being crossed.
[in] c2 Second classifier whose condition is being crossed.
Returns
Whether any alterations were made.
Definition at line 177 of file cond_ellipsoid.c.
References CondEllipsoid::center, Cl::cond, rand_uniform(), and CondEllipsoid::spread.
cond_ellipsoid_free()
void cond_ellipsoid_free (const struct XCSF * xcsf, const struct Cl * c)
Frees the memory used by a hyperellipsoid condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be freed.
Definition at line 86 of file cond_ellipsoid.c.
References CondEllipsoid::center, Cl::cond, CondEllipsoid::mu, and CondEllipsoid::spread.
cond_ellipsoid_general()
bool cond_ellipsoid_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Returns whether classifier c1 has a condition more general than c2.
Parameters
[in] xcsf XCSF data structure.
[in] c1 Classifier whose condition is tested to be more general.
[in] c2 Classifier whose condition is tested to be more specific.
Returns
Whether the hyperellipsoid condition of c1 is more general than c2.
Definition at line 241 of file cond_ellipsoid.c.
References CondEllipsoid::center, Cl::cond, cond_ellipsoid_dist(), and CondEllipsoid::spread.
cond_ellipsoid_init()
void cond_ellipsoid_init (const struct XCSF * xcsf, struct Cl * c)
Creates and initialises a hyperellipsoid condition.
Uses the center-spread representation.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be initialised.
Definition at line 65 of file cond_ellipsoid.c.
References Cl::cond, MU_TYPE, N_MU, rand_uniform(), and sam_init().
cond_ellipsoid_json_export()
char* cond_ellipsoid_json_export (const struct XCSF * xcsf, const struct Cl * c)
Returns a json formatted string representation of a hyperellipsoid.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be returned.
Returns
String encoded in json format.
Definition at line 341 of file cond_ellipsoid.c.
References CondEllipsoid::center, Cl::cond, CondEllipsoid::mu, N_MU, and CondEllipsoid::spread.
Referenced by cond_ellipsoid_print().
cond_ellipsoid_json_import()
void cond_ellipsoid_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json)
Creates a hyperellipsoid from a cJSON object.
Parameters
[in] xcsf The XCSF data structure.
[in,out] c The classifier to initialise.
[in] json cJSON object.
Definition at line 364 of file cond_ellipsoid.c.
References CondEllipsoid::center, Cl::cond, CondEllipsoid::mu, N_MU, sam_json_import(), and CondEllipsoid::spread.
cond_ellipsoid_load()
size_t cond_ellipsoid_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Reads a hyperellipsoid condition from a file.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 320 of file cond_ellipsoid.c.
References Cl::cond, and N_MU.
cond_ellipsoid_match()
bool cond_ellipsoid_match (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Calculates whether a hyperellipsoid condition matches an input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition to match.
[in] x Input state.
Returns
Whether the hyperellipsoid condition matches the input.
Definition at line 163 of file cond_ellipsoid.c.
References cond_ellipsoid_dist().
cond_ellipsoid_mutate()
bool cond_ellipsoid_mutate (const struct XCSF * xcsf, const struct Cl * c)
Mutates a hyperellipsoid condition with the self-adaptive rate.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is being mutated.
Returns
Whether any alterations were made.
Definition at line 209 of file cond_ellipsoid.c.
References CondEllipsoid::center, clamp(), Cl::cond, CondEllipsoid::mu, MU_TYPE, N_MU, rand_normal(), sam_adapt(), and CondEllipsoid::spread.
cond_ellipsoid_print()
void cond_ellipsoid_print (const struct XCSF * xcsf, const struct Cl * c)
Prints a hyperellipsoid condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be printed.
Definition at line 274 of file cond_ellipsoid.c.
References cond_ellipsoid_json_export().
cond_ellipsoid_save()
size_t cond_ellipsoid_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Writes a hyperellipsoid condition to a file.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 302 of file cond_ellipsoid.c.
References CondEllipsoid::center, Cl::cond, CondEllipsoid::mu, N_MU, and CondEllipsoid::spread.
cond_ellipsoid_size()
double cond_ellipsoid_size (const struct XCSF * xcsf, const struct Cl * c)
Returns the size of a hyperellipsoid condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition size to return.
Returns
The length of the input dimension.
Definition at line 288 of file cond_ellipsoid.c.
cond_ellipsoid_update()
void cond_ellipsoid_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Updates a hyperellipsoid, sliding the centers towards the mean input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be updated.
[in] x Input state.
[in] y Truth/payoff value.
Definition at line 143 of file cond_ellipsoid.c.
References CondEllipsoid::center, and Cl::cond.
Variable Documentation
cond_ellipsoid_vtbl
struct CondVtbl const cond_ellipsoid_vtbl static
Initial value:
= {
    &cond_ellipsoid_crossover,  &cond_ellipsoid_general,
    &cond_ellipsoid_match,      &cond_ellipsoid_mutate,
    &cond_ellipsoid_copy,       &cond_ellipsoid_cover,
    &cond_ellipsoid_free,       &cond_ellipsoid_init,
    &cond_ellipsoid_print,      &cond_ellipsoid_update,
    &cond_ellipsoid_size,       &cond_ellipsoid_save,
    &cond_ellipsoid_load,       &cond_ellipsoid_json_export,
    &cond_ellipsoid_json_import
}
Hyperellipsoid condition implemented functions.
Definition at line 87 of file cond_ellipsoid.h.
Referenced by condition_set().