XCSF: cond_ternary.c File Reference
cond_ternary.c File Reference
Ternary condition functions.
#include "cond_ternary.h"
#include "ea.h"
#include "sam.h"
#include "utils.h"
Macros
#define DONT_CARE ('#')
Don't care symbol.
#define N_MU (1)
Number of ternary mutation rates.
Functions
static void cond_ternary_rand (const struct XCSF *xcsf, const struct Cl *c)
Randomises a ternary condition.
void cond_ternary_init (const struct XCSF *xcsf, struct Cl *c)
Creates and initialises a ternary bitstring condition.
void cond_ternary_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by a ternary condition.
void cond_ternary_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies a ternary condition from one classifier to another.
void cond_ternary_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Generates a ternary condition that matches the current input.
void cond_ternary_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Dummy update function.
bool cond_ternary_match (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Calculates whether a ternary condition matches an input.
bool cond_ternary_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Performs uniform crossover with two ternary conditions.
bool cond_ternary_mutate (const struct XCSF *xcsf, const struct Cl *c)
Mutates a ternary condition.
bool cond_ternary_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Returns whether classifier c1 has a condition more general than c2.
void cond_ternary_print (const struct XCSF *xcsf, const struct Cl *c)
Prints a ternary condition.
double cond_ternary_size (const struct XCSF *xcsf, const struct Cl *c)
Returns the size of a ternary condition.
size_t cond_ternary_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes a ternary condition to a file.
size_t cond_ternary_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads a ternary condition from a file.
char * cond_ternary_json_export (const struct XCSF *xcsf, const struct Cl *c)
Returns a json formatted string representation of a ternary condition.
void cond_ternary_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Creates a ternary condition from a cJSON object.
char * cond_ternary_param_json_export (const struct XCSF *xcsf)
Returns a json formatted string of the ternary parameters.
char * cond_ternary_param_json_import (struct XCSF *xcsf, cJSON *json)
Sets the ternary parameters from a cJSON object.
void cond_ternary_param_defaults (struct XCSF *xcsf)
Initialises default ternary condition parameters.
Variables
static const int MU_TYPE [(1)] = { (0) }
Self-adaptation method for mutating ternary conditions.
Detailed Description
Ternary condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2022.
Binarises inputs.
Definition in file cond_ternary.c.
Macro Definition Documentation
DONT_CARE
#define DONT_CARE ('#')
Don't care symbol.
Definition at line 30 of file cond_ternary.c.
N_MU
#define N_MU (1)
Number of ternary mutation rates.
Definition at line 31 of file cond_ternary.c.
Function Documentation
cond_ternary_copy()
void cond_ternary_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Copies a ternary condition from one classifier to another.
Parameters
[in] xcsf The XCSF data structure.
[in] dest The destination classifier.
[in] src The source classifier.
Definition at line 99 of file cond_ternary.c.
References Cl::cond, CondTernary::length, CondTernary::mu, N_MU, and CondTernary::string.
cond_ternary_cover()
void cond_ternary_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Generates a ternary condition that matches the current input.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is being covered.
[in] x The input state to cover.
Definition at line 120 of file cond_ternary.c.
References Cl::cond, DONT_CARE, float_to_binary(), rand_uniform(), CondTernary::string, and CondTernary::tmp_input.
cond_ternary_crossover()
bool cond_ternary_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Performs uniform crossover with two ternary conditions.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The first classifier whose condition is being crossed.
[in] c2 The second classifier whose condition is being crossed.
Returns
Whether any alterations were made.
Definition at line 185 of file cond_ternary.c.
References Cl::cond, CondTernary::length, rand_uniform(), and CondTernary::string.
cond_ternary_free()
void cond_ternary_free (const struct XCSF * xcsf, const struct Cl * c)
Frees the memory used by a ternary condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be freed.
Definition at line 82 of file cond_ternary.c.
References Cl::cond, CondTernary::mu, CondTernary::string, and CondTernary::tmp_input.
cond_ternary_general()
bool cond_ternary_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Returns whether classifier c1 has a condition more general than c2.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The classifier whose condition is tested to be more general.
[in] c2 The classifier whose condition is tested to be more specific.
Returns
Whether the condition of c1 is more general than c2.
Definition at line 238 of file cond_ternary.c.
References Cl::cond, DONT_CARE, CondTernary::length, and CondTernary::string.
cond_ternary_init()
void cond_ternary_init (const struct XCSF * xcsf, struct Cl * c)
Creates and initialises a ternary bitstring condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be initialised.
Definition at line 64 of file cond_ternary.c.
References Cl::cond, cond_ternary_rand(), MU_TYPE, N_MU, and sam_init().
cond_ternary_json_export()
char* cond_ternary_json_export (const struct XCSF * xcsf, const struct Cl * c)
Returns a json formatted string representation of a ternary condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be returned.
Returns
String encoded in json format.
Definition at line 338 of file cond_ternary.c.
References Cl::cond, CondTernary::length, CondTernary::mu, N_MU, and CondTernary::string.
Referenced by cond_ternary_print().
cond_ternary_json_import()
void cond_ternary_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json)
Creates a ternary condition from a cJSON object.
Parameters
[in] xcsf The XCSF data structure.
[in,out] c The classifier to initialise.
[in] json cJSON object.
Definition at line 362 of file cond_ternary.c.
References Cl::cond, CondTernary::length, CondTernary::mu, N_MU, sam_json_import(), and CondTernary::string.
cond_ternary_load()
size_t cond_ternary_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Reads a ternary condition from a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 311 of file cond_ternary.c.
References Cl::cond, and N_MU.
cond_ternary_match()
bool cond_ternary_match (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Calculates whether a ternary condition matches an input.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition to match.
[in] x The input state.
Returns
Whether the condition matches the input.
Definition at line 161 of file cond_ternary.c.
References Cl::cond, DONT_CARE, float_to_binary(), CondTernary::string, and CondTernary::tmp_input.
cond_ternary_mutate()
bool cond_ternary_mutate (const struct XCSF * xcsf, const struct Cl * c)
Mutates a ternary condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is being mutated.
Returns
Whether any alterations were made.
Definition at line 211 of file cond_ternary.c.
References Cl::cond, DONT_CARE, CondTernary::length, CondTernary::mu, MU_TYPE, N_MU, rand_uniform(), sam_adapt(), and CondTernary::string.
cond_ternary_param_defaults()
void cond_ternary_param_defaults (struct XCSF * xcsf)
Initialises default ternary condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 426 of file cond_ternary.c.
References cond_param_set_bits(), and cond_param_set_p_dontcare().
Referenced by cond_param_defaults().
cond_ternary_param_json_export()
char* cond_ternary_param_json_export (const struct XCSF * xcsf)
Returns a json formatted string of the ternary parameters.
Parameters
[in] xcsf The XCSF data structure.
Returns
String encoded in json format.
Definition at line 387 of file cond_ternary.c.
References ArgsCond::bits, and ArgsCond::p_dontcare.
Referenced by cond_param_json_export().
cond_ternary_param_json_import()
char* cond_ternary_param_json_import (struct XCSF * xcsf, cJSON * json)
Sets the ternary parameters from a cJSON object.
Parameters
[in,out] xcsf The XCSF data structure.
[in] json cJSON object.
Returns
NULL if successful; or the name of parameter if not found.
Definition at line 405 of file cond_ternary.c.
References cond_param_set_bits(), and cond_param_set_p_dontcare().
Referenced by cond_param_json_import().
cond_ternary_print()
void cond_ternary_print (const struct XCSF * xcsf, const struct Cl * c)
Prints a ternary condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be printed.
Definition at line 263 of file cond_ternary.c.
References cond_ternary_json_export().
cond_ternary_rand()
static void cond_ternary_rand (const struct XCSF * xcsf, const struct Cl * c) static
Randomises a ternary condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be initialised.
Definition at line 44 of file cond_ternary.c.
References Cl::cond, DONT_CARE, CondTernary::length, rand_uniform(), and CondTernary::string.
Referenced by cond_ternary_init().
cond_ternary_save()
size_t cond_ternary_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Writes a ternary condition to a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 292 of file cond_ternary.c.
References Cl::cond, CondTernary::length, CondTernary::mu, N_MU, and CondTernary::string.
cond_ternary_size()
double cond_ternary_size (const struct XCSF * xcsf, const struct Cl * c)
Returns the size of a ternary condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition size to return.
Returns
The size of the condition.
Definition at line 277 of file cond_ternary.c.
References Cl::cond, and CondTernary::length.
cond_ternary_update()
void cond_ternary_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Dummy update function.
Parameters
[in] xcsf The XCSF data structure.
[in] c Classifier whose condition is to be updated.
[in] x Input state.
[in] y Truth/payoff value.
Definition at line 144 of file cond_ternary.c.
Variable Documentation
MU_TYPE
const int MU_TYPE[(1)] = { (0) } static
Self-adaptation method for mutating ternary conditions.
Definition at line 36 of file cond_ternary.c.
Referenced by cond_ternary_init(), and cond_ternary_mutate().