XCSF: cond_dgp.h File Reference
cond_dgp.h File Reference
Dynamical GP graph condition functions.
#include "condition.h"
#include "dgp.h"
#include "xcsf.h"
Data Structures
struct CondDGP
Dynamical GP graph condition data structure.
Functions
char * cond_dgp_param_json_export (const struct XCSF *xcsf)
Returns a json formatted string of the DGP parameters.
char * cond_dgp_param_json_import (struct XCSF *xcsf, cJSON *json)
Sets the DGP parameters from a cJSON object.
void cond_dgp_param_defaults (struct XCSF *xcsf)
Initialises default DGP condition parameters.
bool cond_dgp_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Dummy crossover function.
bool cond_dgp_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Dummy general function.
bool cond_dgp_match (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Calculates whether a dynamical GP graph condition matches an input.
bool cond_dgp_mutate (const struct XCSF *xcsf, const struct Cl *c)
Mutates a dynamical GP graph condition with the self-adaptive rates.
void cond_dgp_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies a dynamical GP graph condition from one classifier to another.
void cond_dgp_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Generates a dynamical GP graph that matches the current input.
void cond_dgp_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by a dynamical GP graph condition.
void cond_dgp_init (const struct XCSF *xcsf, struct Cl *c)
Creates and initialises a dynamical GP graph condition.
void cond_dgp_print (const struct XCSF *xcsf, const struct Cl *c)
Prints a dynamical GP graph condition.
void cond_dgp_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Dummy update function.
double cond_dgp_size (const struct XCSF *xcsf, const struct Cl *c)
Returns the size of a dynamical GP graph condition.
size_t cond_dgp_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes a dynamical GP graph condition to a file.
size_t cond_dgp_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads a dynamical GP graph condition from a file.
char * cond_dgp_json_export (const struct XCSF *xcsf, const struct Cl *c)
Returns a json formatted string representation of a DGP condition.
void cond_dgp_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Creates a DGP condition from a cJSON object.
Variables
static struct CondVtbl const cond_dgp_vtbl
Dynamical GP graph condition implemented functions.
Detailed Description
Dynamical GP graph condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2022.
Definition in file cond_dgp.h.
Function Documentation
cond_dgp_copy()
void cond_dgp_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Copies a dynamical GP graph condition from one classifier to another.
Parameters
[in] xcsf XCSF data structure.
[in] dest Destination classifier.
[in] src Source classifier.
Definition at line 63 of file cond_dgp.c.
References Cl::cond, CondDGP::dgp, graph_copy(), and graph_init().
cond_dgp_cover()
void cond_dgp_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Generates a dynamical GP graph that matches the current input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is being covered.
[in] x Input state to cover.
Definition at line 79 of file cond_dgp.c.
References Cl::cond, cond_dgp_match(), CondDGP::dgp, and graph_rand().
cond_dgp_crossover()
bool cond_dgp_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Dummy crossover function.
Parameters
[in] xcsf XCSF data structure.
[in] c1 First classifier whose condition is being crossed.
[in] c2 Second classifier whose condition is being crossed.
Returns
False.
Definition at line 145 of file cond_dgp.c.
cond_dgp_free()
void cond_dgp_free (const struct XCSF * xcsf, const struct Cl * c)
Frees the memory used by a dynamical GP graph condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be freed.
Definition at line 48 of file cond_dgp.c.
References Cl::cond, CondDGP::dgp, and graph_free().
cond_dgp_general()
bool cond_dgp_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Dummy general function.
Parameters
[in] xcsf XCSF data structure.
[in] c1 Classifier whose condition is tested to be more general.
[in] c2 Classifier whose condition is tested to be more specific.
Returns
False.
Definition at line 162 of file cond_dgp.c.
cond_dgp_init()
void cond_dgp_init (const struct XCSF * xcsf, struct Cl * c)
Creates and initialises a dynamical GP graph condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be initialised.
Definition at line 34 of file cond_dgp.c.
References Cl::cond, graph_init(), and graph_rand().
cond_dgp_json_export()
char* cond_dgp_json_export (const struct XCSF * xcsf, const struct Cl * c)
Returns a json formatted string representation of a DGP condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be returned.
Returns
String encoded in json format.
Definition at line 238 of file cond_dgp.c.
References Cl::cond, CondDGP::dgp, and graph_json_export().
Referenced by cond_dgp_print().
cond_dgp_json_import()
void cond_dgp_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json)
Creates a DGP condition from a cJSON object.
Parameters
[in] xcsf The XCSF data structure.
[in,out] c The classifier to initialise.
[in] json cJSON object.
Definition at line 258 of file cond_dgp.c.
References Cl::cond, CondDGP::dgp, graph_free(), and graph_json_import().
cond_dgp_load()
size_t cond_dgp_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Reads a dynamical GP graph condition from a file.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 222 of file cond_dgp.c.
References Cl::cond, and graph_load().
cond_dgp_match()
bool cond_dgp_match (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Calculates whether a dynamical GP graph condition matches an input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition to match.
[in] x Input state.
Returns
Whether the dynamical GP graph condition matches the input.
Definition at line 113 of file cond_dgp.c.
References Cl::cond, CondDGP::dgp, graph_output(), and graph_update().
Referenced by cond_dgp_cover().
cond_dgp_mutate()
bool cond_dgp_mutate (const struct XCSF * xcsf, const struct Cl * c)
Mutates a dynamical GP graph condition with the self-adaptive rates.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is being mutated.
Returns
Whether any alterations were made.
Definition at line 130 of file cond_dgp.c.
References Cl::cond, CondDGP::dgp, and graph_mutate().
cond_dgp_param_defaults()
void cond_dgp_param_defaults (struct XCSF * xcsf)
Initialises default DGP condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 298 of file cond_dgp.c.
References graph_args_init(), graph_param_set_evolve_cycles(), graph_param_set_max_k(), graph_param_set_max_t(), graph_param_set_n(), and graph_param_set_n_inputs().
Referenced by cond_param_defaults().
cond_dgp_param_json_export()
char* cond_dgp_param_json_export (const struct XCSF * xcsf)
Returns a json formatted string of the DGP parameters.
Parameters
[in] xcsf The XCSF data structure.
Returns
String encoded in json format.
Definition at line 276 of file cond_dgp.c.
References graph_args_json_export().
Referenced by cond_param_json_export().
cond_dgp_param_json_import()
char* cond_dgp_param_json_import (struct XCSF * xcsf, cJSON * json)
Sets the DGP parameters from a cJSON object.
Parameters
[in,out] xcsf The XCSF data structure.
[in] json cJSON object.
Returns
NULL if successful; or the name of parameter if not found.
Definition at line 288 of file cond_dgp.c.
References graph_args_json_import().
Referenced by cond_param_json_import().
cond_dgp_print()
void cond_dgp_print (const struct XCSF * xcsf, const struct Cl * c)
Prints a dynamical GP graph condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be printed.
Definition at line 177 of file cond_dgp.c.
References cond_dgp_json_export().
cond_dgp_save()
size_t cond_dgp_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Writes a dynamical GP graph condition to a file.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 206 of file cond_dgp.c.
References Cl::cond, CondDGP::dgp, and graph_save().
cond_dgp_size()
double cond_dgp_size (const struct XCSF * xcsf, const struct Cl * c)
Returns the size of a dynamical GP graph condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition size to return.
Returns
The number of nodes in the graph.
Definition at line 191 of file cond_dgp.c.
References Cl::cond, CondDGP::dgp, and Graph::n.
cond_dgp_update()
void cond_dgp_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Dummy update function.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be updated.
[in] x Input state.
[in] y Truth/payoff value.
Definition at line 96 of file cond_dgp.c.
Variable Documentation
cond_dgp_vtbl
struct CondVtbl const cond_dgp_vtbl static
Initial value:
= {
    &cond_dgp_crossover, &cond_dgp_general,     &cond_dgp_match,
    &cond_dgp_mutate,    &cond_dgp_copy,        &cond_dgp_cover,
    &cond_dgp_free,      &cond_dgp_init,        &cond_dgp_print,
    &cond_dgp_update,    &cond_dgp_size,        &cond_dgp_save,
    &cond_dgp_load,      &cond_dgp_json_export, &cond_dgp_json_import
}
Dynamical GP graph condition implemented functions.
Definition at line 92 of file cond_dgp.h.
Referenced by condition_set().