XCSF: cond_gp.h File Reference
cond_gp.h File Reference
Tree GP condition functions.
#include "condition.h"
#include "gp.h"
#include "xcsf.h"
Data Structures
struct CondGP
Tree GP condition data structure.
Functions
void cond_gp_param_defaults (struct XCSF *xcsf)
Initialises default tree GP condition parameters.
char * cond_gp_param_json_export (const struct XCSF *xcsf)
Returns a json formatted string of the tree GP parameters.
char * cond_gp_param_json_import (struct XCSF *xcsf, cJSON *json)
Sets the tree GP parameters from a cJSON object.
bool cond_gp_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Performs sub-tree crossover with two tree-GP conditions.
bool cond_gp_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Dummy general function.
bool cond_gp_match (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Calculates whether a GP tree condition matches an input.
bool cond_gp_mutate (const struct XCSF *xcsf, const struct Cl *c)
Mutates a tree-GP condition with the self-adaptive rate.
void cond_gp_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies a tree-GP condition from one classifier to another.
void cond_gp_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Generates a GP tree that matches the current input.
void cond_gp_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by a tree-GP condition.
void cond_gp_init (const struct XCSF *xcsf, struct Cl *c)
Creates and initialises a tree-GP condition.
void cond_gp_print (const struct XCSF *xcsf, const struct Cl *c)
Prints a tree-GP condition.
void cond_gp_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Dummy update function.
double cond_gp_size (const struct XCSF *xcsf, const struct Cl *c)
Returns the size of a tree-GP condition.
size_t cond_gp_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes a tree-GP condition to a file.
size_t cond_gp_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads a tree-GP condition from a file.
char * cond_gp_json_export (const struct XCSF *xcsf, const struct Cl *c)
Returns a json formatted string representation of a tree-GP condition.
void cond_gp_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Creates a tree GP condition from a cJSON object.
Variables
static struct CondVtbl const cond_gp_vtbl
Tree GP condition implemented functions.
Detailed Description
Tree GP condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2022.
Definition in file cond_gp.h.
Function Documentation
cond_gp_copy()
void cond_gp_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Copies a tree-GP condition from one classifier to another.
Parameters
[in] xcsf XCSF data structure.
[in] dest Destination classifier.
[in] src Source classifier.
Definition at line 63 of file cond_gp.c.
References Cl::cond, CondGP::gp, and tree_copy().
cond_gp_cover()
void cond_gp_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Generates a GP tree that matches the current input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is being covered.
[in] x Input state to cover.
Definition at line 79 of file cond_gp.c.
References Cl::cond, cond_gp_match(), CondGP::gp, tree_free(), and tree_rand().
cond_gp_crossover()
bool cond_gp_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Performs sub-tree crossover with two tree-GP conditions.
Parameters
[in] xcsf XCSF data structure.
[in] c1 First classifier whose condition is being crossed.
[in] c2 Second classifier whose condition is being crossed.
Returns
Whether any alterations were made.
Definition at line 145 of file cond_gp.c.
References Cl::cond, CondGP::gp, rand_uniform(), and tree_crossover().
cond_gp_free()
void cond_gp_free (const struct XCSF * xcsf, const struct Cl * c)
Frees the memory used by a tree-GP condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be freed.
Definition at line 48 of file cond_gp.c.
References Cl::cond, CondGP::gp, and tree_free().
cond_gp_general()
bool cond_gp_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Dummy general function.
Parameters
[in] xcsf XCSF data structure.
[in] c1 Classifier whose condition is tested to be more general.
[in] c2 Classifier whose condition is tested to be more specific.
Returns
False
Definition at line 166 of file cond_gp.c.
cond_gp_init()
void cond_gp_init (const struct XCSF * xcsf, struct Cl * c)
Creates and initialises a tree-GP condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be initialised.
Definition at line 35 of file cond_gp.c.
References Cl::cond, and tree_rand().
cond_gp_json_export()
char* cond_gp_json_export (const struct XCSF * xcsf, const struct Cl * c)
Returns a json formatted string representation of a tree-GP condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be returned.
Returns
String encoded in json format.
Definition at line 242 of file cond_gp.c.
References Cl::cond, CondGP::gp, and tree_json_export().
Referenced by cond_gp_print().
cond_gp_json_import()
void cond_gp_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json)
Creates a tree GP condition from a cJSON object.
Parameters
[in] xcsf The XCSF data structure.
[in,out] c The classifier to initialise.
[in] json cJSON object.
Definition at line 307 of file cond_gp.c.
References Cl::cond, CondGP::gp, and tree_json_import().
cond_gp_load()
size_t cond_gp_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Reads a tree-GP condition from a file.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 226 of file cond_gp.c.
References Cl::cond, and tree_load().
cond_gp_match()
bool cond_gp_match (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Calculates whether a GP tree condition matches an input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition to match.
[in] x Input state.
Returns
Whether the hyperrectangle condition matches the input.
Definition at line 113 of file cond_gp.c.
References Cl::cond, CondGP::gp, GPTree::pos, and tree_eval().
Referenced by cond_gp_cover().
cond_gp_mutate()
bool cond_gp_mutate (const struct XCSF * xcsf, const struct Cl * c)
Mutates a tree-GP condition with the self-adaptive rate.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is being mutated.
Returns
Whether any alterations were made.
Definition at line 130 of file cond_gp.c.
References Cl::cond, CondGP::gp, and tree_mutate().
cond_gp_param_defaults()
void cond_gp_param_defaults (struct XCSF * xcsf)
Initialises default tree GP condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 286 of file cond_gp.c.
References tree_args_init(), tree_args_init_constants(), tree_param_set_init_depth(), tree_param_set_max(), tree_param_set_max_len(), tree_param_set_min(), tree_param_set_n_constants(), and tree_param_set_n_inputs().
Referenced by cond_param_defaults().
cond_gp_param_json_export()
char* cond_gp_param_json_export (const struct XCSF * xcsf)
Returns a json formatted string of the tree GP parameters.
Parameters
[in] xcsf The XCSF data structure.
Returns
String encoded in json format.
Definition at line 262 of file cond_gp.c.
References tree_args_json_export().
Referenced by cond_param_json_export().
cond_gp_param_json_import()
char* cond_gp_param_json_import (struct XCSF * xcsf, cJSON * json)
Sets the tree GP parameters from a cJSON object.
Parameters
[in,out] xcsf The XCSF data structure.
[in] json cJSON object.
Returns
NULL if successful; or the name of parameter if not found.
Definition at line 274 of file cond_gp.c.
References tree_args_init_constants(), and tree_args_json_import().
Referenced by cond_param_json_import().
cond_gp_print()
void cond_gp_print (const struct XCSF * xcsf, const struct Cl * c)
Prints a tree-GP condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be printed.
Definition at line 181 of file cond_gp.c.
References cond_gp_json_export().
cond_gp_save()
size_t cond_gp_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Writes a tree-GP condition to a file.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 210 of file cond_gp.c.
References Cl::cond, CondGP::gp, and tree_save().
cond_gp_size()
double cond_gp_size (const struct XCSF * xcsf, const struct Cl * c)
Returns the size of a tree-GP condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition size to return.
Returns
The length of the tree.
Definition at line 195 of file cond_gp.c.
References Cl::cond, CondGP::gp, and GPTree::len.
cond_gp_update()
void cond_gp_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Dummy update function.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be updated.
[in] x Input state.
[in] y Truth/payoff value.
Definition at line 96 of file cond_gp.c.
Variable Documentation
cond_gp_vtbl
struct CondVtbl const cond_gp_vtbl static
Initial value:
= {
    &cond_gp_crossover, &cond_gp_general,     &cond_gp_match,
    &cond_gp_mutate,    &cond_gp_copy,        &cond_gp_cover,
    &cond_gp_free,      &cond_gp_init,        &cond_gp_print,
    &cond_gp_update,    &cond_gp_size,        &cond_gp_save,
    &cond_gp_load,      &cond_gp_json_export, &cond_gp_json_import
}
Tree GP condition implemented functions.
Definition at line 92 of file cond_gp.h.
Referenced by condition_set().