XCSF: cond_neural.c File Reference
cond_neural.c File Reference
Multi-layer perceptron neural network condition functions.
#include "cond_neural.h"
#include "neural_activations.h"
#include "neural_layer_connected.h"
#include "neural_layer_convolutional.h"
#include "neural_layer_dropout.h"
#include "neural_layer_lstm.h"
#include "neural_layer_maxpool.h"
#include "neural_layer_noise.h"
#include "neural_layer_recurrent.h"
#include "neural_layer_softmax.h"
#include "utils.h"
Functions
void cond_neural_init (const struct XCSF *xcsf, struct Cl *c)
Creates and initialises a neural network condition.
void cond_neural_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by a neural network condition.
void cond_neural_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies a neural network condition from one classifier to another.
void cond_neural_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Generates a neural network that matches the current input.
void cond_neural_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Dummy update function.
bool cond_neural_match (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Generates a neural network that matches the current input.
bool cond_neural_mutate (const struct XCSF *xcsf, const struct Cl *c)
Mutates a neural network condition with the self-adaptive rates.
bool cond_neural_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Dummy crossover function.
bool cond_neural_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Dummy general function.
void cond_neural_print (const struct XCSF *xcsf, const struct Cl *c)
Prints a neural network condition.
double cond_neural_size (const struct XCSF *xcsf, const struct Cl *c)
Returns the size of a neural network condition.
size_t cond_neural_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes a neural network condition to a file.
size_t cond_neural_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads a neural network condition from a file.
int cond_neural_neurons (const struct XCSF *xcsf, const struct Cl *c, int layer)
Returns the number of neurons in a neural condition layer.
int cond_neural_connections (const struct XCSF *xcsf, const struct Cl *c, int layer)
Returns the number of active connections in a neural condition layer.
int cond_neural_layers (const struct XCSF *xcsf, const struct Cl *c)
Returns the number of layers within a neural network condition.
char * cond_neural_json_export (const struct XCSF *xcsf, const struct Cl *c)
Returns a json formatted string representation of a neural condition.
void cond_neural_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Creates a neural condition from a cJSON object.
char * cond_neural_param_json_import (struct XCSF *xcsf, cJSON *json)
Sets the neural network parameters from a cJSON object.
void cond_neural_param_defaults (struct XCSF *xcsf)
Initialises default neural condition parameters.
Detailed Description
Multi-layer perceptron neural network condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2022.
Definition in file cond_neural.c.
Function Documentation
cond_neural_connections()
int cond_neural_connections (const struct XCSF * xcsf, const struct Cl * c, int layer)
Returns the number of active connections in a neural condition layer.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier maintaining a neural network condition.
[in] layer Position of a layer in the network.
Returns
The current number of active connections in a layer.
Definition at line 273 of file cond_neural.c.
References Cl::cond, Llist::layer, Layer::n_active, CondNeural::net, Llist::prev, and Net::tail.
Referenced by clset_mean_cond_connections().
cond_neural_copy()
void cond_neural_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Copies a neural network condition from one classifier to another.
Parameters
[in] xcsf XCSF data structure.
[in] dest Destination classifier.
[in] src Source classifier.
Definition at line 70 of file cond_neural.c.
References Cl::cond, CondNeural::net, and neural_copy().
cond_neural_cover()
void cond_neural_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Generates a neural network that matches the current input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is being covered.
[in] x Input state to cover.
Definition at line 86 of file cond_neural.c.
References Cl::cond, cond_neural_match(), CondNeural::net, and neural_rand().
cond_neural_crossover()
bool cond_neural_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Dummy crossover function.
Parameters
[in] xcsf XCSF data structure.
[in] c1 First classifier whose condition is being crossed.
[in] c2 Second classifier whose condition is being crossed.
Returns
False
Definition at line 150 of file cond_neural.c.
cond_neural_free()
void cond_neural_free (const struct XCSF * xcsf, const struct Cl * c)
Frees the memory used by a neural network condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be freed.
Definition at line 55 of file cond_neural.c.
References Cl::cond, CondNeural::net, and neural_free().
cond_neural_general()
bool cond_neural_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Dummy general function.
Parameters
[in] xcsf XCSF data structure.
[in] c1 Classifier whose condition is tested to be more general.
[in] c2 Classifier whose condition is tested to be more specific.
Returns
False.
Definition at line 167 of file cond_neural.c.
cond_neural_init()
void cond_neural_init (const struct XCSF * xcsf, struct Cl * c)
Creates and initialises a neural network condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be initialised.
Definition at line 42 of file cond_neural.c.
References Cl::cond, and neural_create().
cond_neural_json_export()
char* cond_neural_json_export (const struct XCSF * xcsf, const struct Cl * c)
Returns a json formatted string representation of a neural condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be returned.
Returns
String encoded in json format.
Definition at line 312 of file cond_neural.c.
References Cl::cond, CondNeural::net, and neural_json_export().
Referenced by cond_neural_print().
cond_neural_json_import()
void cond_neural_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json)
Creates a neural condition from a cJSON object.
Parameters
[in] xcsf The XCSF data structure.
[in,out] c The classifier to initialise.
[in] json cJSON object.
Definition at line 334 of file cond_neural.c.
References Cl::cond, CondNeural::net, and neural_json_import().
cond_neural_layers()
int cond_neural_layers (const struct XCSF * xcsf, const struct Cl * c)
Returns the number of layers within a neural network condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier maintaining a neural network condition.
Returns
The number of layers.
Definition at line 297 of file cond_neural.c.
References Cl::cond, Net::n_layers, and CondNeural::net.
Referenced by clset_mean_cond_layers().
cond_neural_load()
size_t cond_neural_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Reads a neural network condition from a file.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 228 of file cond_neural.c.
References Cl::cond, and neural_load().
cond_neural_match()
bool cond_neural_match (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Generates a neural network that matches the current input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is being covered.
[in] x Input state to cover.
Definition at line 118 of file cond_neural.c.
References Cl::cond, CondNeural::net, neural_output(), and neural_propagate().
Referenced by cond_neural_cover().
cond_neural_mutate()
bool cond_neural_mutate (const struct XCSF * xcsf, const struct Cl * c)
Mutates a neural network condition with the self-adaptive rates.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is being mutated.
Returns
Whether any alterations were made.
Definition at line 135 of file cond_neural.c.
References Cl::cond, CondNeural::net, and neural_mutate().
cond_neural_neurons()
int cond_neural_neurons (const struct XCSF * xcsf, const struct Cl * c, int layer)
Returns the number of neurons in a neural condition layer.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier maintaining a neural network prediction.
[in] layer Position of a layer in the network.
Returns
The current number of neurons in a layer.
Definition at line 245 of file cond_neural.c.
References Cl::cond, CONVOLUTIONAL, Llist::layer, Layer::n_filters, Layer::n_outputs, CondNeural::net, Llist::prev, Net::tail, and Layer::type.
Referenced by clset_mean_cond_neurons().
cond_neural_param_defaults()
void cond_neural_param_defaults (struct XCSF * xcsf)
Initialises default neural condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 383 of file cond_neural.c.
References CONNECTED, ArgsLayer::evolve_connect, ArgsLayer::evolve_neurons, ArgsLayer::evolve_weights, ArgsLayer::function, layer_args_copy(), layer_args_init(), LINEAR, LOGISTIC, ArgsLayer::max_neuron_grow, ArgsLayer::n_init, ArgsLayer::n_inputs, ArgsLayer::n_max, ArgsLayer::next, and ArgsLayer::type.
Referenced by cond_param_defaults().
cond_neural_param_json_import()
char* cond_neural_param_json_import (struct XCSF * xcsf, cJSON * json)
Sets the neural network parameters from a cJSON object.
Parameters
[in,out] xcsf The XCSF data structure.
[in] json cJSON object.
Returns
NULL if successful; or the name of parameter if not found.
Definition at line 353 of file cond_neural.c.
References layer_args_free(), layer_args_init(), layer_args_json_import(), layer_args_validate(), ArgsLayer::n_inputs, and ArgsLayer::next.
Referenced by cond_param_json_import().
cond_neural_print()
void cond_neural_print (const struct XCSF * xcsf, const struct Cl * c)
Prints a neural network condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be printed.
Definition at line 182 of file cond_neural.c.
References cond_neural_json_export().
cond_neural_save()
size_t cond_neural_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Writes a neural network condition to a file.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 212 of file cond_neural.c.
References Cl::cond, CondNeural::net, and neural_save().
cond_neural_size()
double cond_neural_size (const struct XCSF * xcsf, const struct Cl * c)
Returns the size of a neural network condition.
See also
neural_size()
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition size to return.
Returns
The network size.
Definition at line 197 of file cond_neural.c.
References Cl::cond, CondNeural::net, and neural_size().
cond_neural_update()
void cond_neural_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Dummy update function.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be updated.
[in] x Input state.
[in] y Truth/payoff value.
Definition at line 102 of file cond_neural.c.