XCSF: condition.c File Reference
condition.c File Reference
Interface for classifier conditions.
#include "cond_dgp.h"
#include "cond_dummy.h"
#include "cond_ellipsoid.h"
#include "cond_gp.h"
#include "cond_neural.h"
#include "cond_rectangle.h"
#include "cond_ternary.h"
#include "rule_dgp.h"
#include "rule_neural.h"
Functions
void condition_set (const struct XCSF *xcsf, struct Cl *c)
Sets a classifier's condition functions to the implementations.
const char * condition_type_as_string (const int type)
Returns a string representation of a condition type from an integer.
int condition_type_as_int (const char *type)
Returns the integer representation of a condition type given a name.
static void cond_param_defaults_gp (struct XCSF *xcsf)
Initialises default tree GP condition parameters.
static void cond_param_defaults_dgp (struct XCSF *xcsf)
Initialises default DGP condition parameters.
static void cond_param_defaults_neural (struct XCSF *xcsf)
Initialises default neural condition parameters.
void cond_param_defaults (struct XCSF *xcsf)
Initialises default condition parameters.
static void cond_param_print_ternary (const struct XCSF *xcsf)
Prints ternary condition parameters.
static void cond_param_print_csr (const struct XCSF *xcsf)
Prints center-spread representation condition parameters.
static void cond_param_print_gp (const struct XCSF *xcsf)
Prints Tree GP condition parameters.
static void cond_param_print_dgp (const struct XCSF *xcsf)
Prints DGP graph condition parameters.
static void cond_param_print_neural (const struct XCSF *xcsf)
Prints neural network condition parameters.
void cond_param_print (const struct XCSF *xcsf)
Prints condition parameters.
size_t cond_param_save (const struct XCSF *xcsf, FILE *fp)
Saves condition parameters.
size_t cond_param_load (struct XCSF *xcsf, FILE *fp)
Loads condition parameters.
void cond_param_free (struct XCSF *xcsf)
Frees condition parameters.
void cond_param_set_eta (struct XCSF *xcsf, const double a)
void cond_param_set_min (struct XCSF *xcsf, const double a)
void cond_param_set_max (struct XCSF *xcsf, const double a)
void cond_param_set_p_dontcare (struct XCSF *xcsf, const double a)
void cond_param_set_spread_min (struct XCSF *xcsf, const double a)
void cond_param_set_bits (struct XCSF *xcsf, const int a)
void cond_param_set_type_string (struct XCSF *xcsf, const char *a)
void cond_param_set_type (struct XCSF *xcsf, const int a)
Detailed Description
Interface for classifier conditions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file condition.c.
Function Documentation
cond_param_defaults()
void cond_param_defaults (struct XCSF * xcsf)
Initialises default condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 224 of file condition.c.
References cond_param_defaults_dgp(), cond_param_defaults_gp(), cond_param_defaults_neural(), cond_param_set_bits(), cond_param_set_eta(), cond_param_set_max(), cond_param_set_min(), cond_param_set_p_dontcare(), cond_param_set_spread_min(), cond_param_set_type(), and COND_TYPE_HYPERRECTANGLE.
Referenced by param_init().
cond_param_defaults_dgp()
static void cond_param_defaults_dgp (struct XCSF * xcsf) static
Initialises default DGP condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 179 of file condition.c.
References XCSF::cond, ArgsCond::dargs, graph_args_init(), graph_param_set_evolve_cycles(), graph_param_set_max_k(), graph_param_set_max_t(), graph_param_set_n(), graph_param_set_n_inputs(), and XCSF::x_dim.
Referenced by cond_param_defaults().
cond_param_defaults_gp()
static void cond_param_defaults_gp (struct XCSF * xcsf) static
Initialises default tree GP condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 160 of file condition.c.
References XCSF::cond, ArgsCond::targs, tree_args_init(), tree_args_init_constants(), tree_param_set_init_depth(), tree_param_set_max(), tree_param_set_max_len(), tree_param_set_min(), tree_param_set_n_constants(), tree_param_set_n_inputs(), and XCSF::x_dim.
Referenced by cond_param_defaults().
cond_param_defaults_neural()
static void cond_param_defaults_neural (struct XCSF * xcsf) static
Initialises default neural condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 196 of file condition.c.
References XCSF::cond, CONNECTED, ArgsLayer::evolve_connect, ArgsLayer::evolve_neurons, ArgsLayer::evolve_weights, ArgsLayer::function, ArgsCond::largs, layer_args_copy(), layer_args_init(), LINEAR, LOGISTIC, ArgsLayer::max_neuron_grow, ArgsLayer::n_init, ArgsLayer::n_inputs, ArgsLayer::n_max, ArgsLayer::next, ArgsLayer::type, and XCSF::x_dim.
Referenced by cond_param_defaults().
cond_param_free()
void cond_param_free (struct XCSF * xcsf)
Frees condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 393 of file condition.c.
References XCSF::cond, ArgsCond::dargs, ArgsCond::largs, layer_args_free(), ArgsCond::targs, and tree_args_free().
Referenced by param_free().
cond_param_load()
size_t cond_param_load (struct XCSF * xcsf, FILE * fp)
Loads condition parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 372 of file condition.c.
References ArgsCond::bits, XCSF::cond, ArgsCond::dargs, ArgsCond::eta, graph_args_load(), ArgsCond::max, ArgsCond::min, ArgsCond::p_dontcare, ArgsCond::spread_min, ArgsCond::targs, tree_args_load(), and ArgsCond::type.
Referenced by param_load().
cond_param_print()
void cond_param_print (const struct XCSF * xcsf)
Prints condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 313 of file condition.c.
References XCSF::cond, cond_param_print_csr(), cond_param_print_dgp(), cond_param_print_gp(), cond_param_print_neural(), cond_param_print_ternary(), COND_TYPE_DGP, COND_TYPE_GP, COND_TYPE_HYPERELLIPSOID, COND_TYPE_HYPERRECTANGLE, COND_TYPE_NEURAL, COND_TYPE_TERNARY, condition_type_as_string(), RULE_TYPE_DGP, RULE_TYPE_NETWORK, RULE_TYPE_NEURAL, and ArgsCond::type.
Referenced by param_print().
cond_param_print_csr()
static void cond_param_print_csr (const struct XCSF * xcsf) static
Prints center-spread representation condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 255 of file condition.c.
References XCSF::cond, ArgsCond::eta, ArgsCond::max, ArgsCond::min, and ArgsCond::spread_min.
Referenced by cond_param_print().
cond_param_print_dgp()
static void cond_param_print_dgp (const struct XCSF * xcsf) static
Prints DGP graph condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 282 of file condition.c.
References XCSF::cond, ArgsCond::dargs, and graph_args_print().
Referenced by cond_param_print().
cond_param_print_gp()
static void cond_param_print_gp (const struct XCSF * xcsf) static
Prints Tree GP condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 269 of file condition.c.
References XCSF::cond, ArgsCond::targs, and tree_args_print().
Referenced by cond_param_print().
cond_param_print_neural()
static void cond_param_print_neural (const struct XCSF * xcsf) static
Prints neural network condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 295 of file condition.c.
References XCSF::cond, ArgsCond::largs, layer_args_print(), and ArgsLayer::next.
Referenced by cond_param_print().
cond_param_print_ternary()
static void cond_param_print_ternary (const struct XCSF * xcsf) static
Prints ternary condition parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 243 of file condition.c.
References ArgsCond::bits, XCSF::cond, and ArgsCond::p_dontcare.
Referenced by cond_param_print().
cond_param_save()
size_t cond_param_save (const struct XCSF * xcsf, FILE * fp)
Saves condition parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 349 of file condition.c.
References ArgsCond::bits, XCSF::cond, ArgsCond::dargs, ArgsCond::eta, graph_args_save(), ArgsCond::max, ArgsCond::min, ArgsCond::p_dontcare, ArgsCond::spread_min, ArgsCond::targs, tree_args_save(), and ArgsCond::type.
Referenced by param_save().
cond_param_set_bits()
void cond_param_set_bits (struct XCSF * xcsf, const int a)
Definition at line 457 of file condition.c.
References ArgsCond::bits, and XCSF::cond.
Referenced by cond_param_defaults(), config_cl_cond_ternary(), and XCS::unpack_cond_ternary().
cond_param_set_eta()
void cond_param_set_eta (struct XCSF * xcsf, const double a)
Definition at line 406 of file condition.c.
References XCSF::cond, and ArgsCond::eta.
Referenced by cond_param_defaults(), config_cl_cond_csr(), and XCS::unpack_cond_csr().
cond_param_set_max()
void cond_param_set_max (struct XCSF * xcsf, const double a)
Definition at line 426 of file condition.c.
References XCSF::cond, and ArgsCond::max.
Referenced by cond_param_defaults(), config_cl_cond_csr(), and XCS::unpack_cond_csr().
cond_param_set_min()
void cond_param_set_min (struct XCSF * xcsf, const double a)
Definition at line 420 of file condition.c.
References XCSF::cond, and ArgsCond::min.
Referenced by cond_param_defaults(), config_cl_cond_csr(), and XCS::unpack_cond_csr().
cond_param_set_p_dontcare()
void cond_param_set_p_dontcare (struct XCSF * xcsf, const double a)
Definition at line 432 of file condition.c.
References XCSF::cond, and ArgsCond::p_dontcare.
Referenced by cond_param_defaults(), config_cl_cond_ternary(), and XCS::unpack_cond_ternary().
cond_param_set_spread_min()
void cond_param_set_spread_min (struct XCSF * xcsf, const double a)
Definition at line 446 of file condition.c.
References XCSF::cond, and ArgsCond::spread_min.
Referenced by cond_param_defaults(), config_cl_cond_csr(), and XCS::unpack_cond_csr().
cond_param_set_type()
void cond_param_set_type (struct XCSF * xcsf, const int a)
Definition at line 474 of file condition.c.
References XCSF::cond, and ArgsCond::type.
Referenced by cond_param_defaults().
cond_param_set_type_string()
void cond_param_set_type_string (struct XCSF * xcsf, const char * a)
Definition at line 468 of file condition.c.
References XCSF::cond, condition_type_as_int(), and ArgsCond::type.
Referenced by config_cl_cond(), and XCS::set_condition().
condition_set()
void condition_set (const struct XCSF * xcsf, struct Cl * c)
Sets a classifier's condition functions to the implementations.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier to set.
Definition at line 40 of file condition.c.
References Cl::act_vptr, XCSF::cond, cond_dgp_vtbl, cond_dummy_vtbl, cond_ellipsoid_vtbl, cond_gp_vtbl, cond_neural_vtbl, cond_rectangle_vtbl, cond_ternary_vtbl, COND_TYPE_DGP, COND_TYPE_DUMMY, COND_TYPE_GP, COND_TYPE_HYPERELLIPSOID, COND_TYPE_HYPERRECTANGLE, COND_TYPE_NEURAL, COND_TYPE_TERNARY, Cl::cond_vptr, rule_dgp_act_vtbl, rule_dgp_cond_vtbl, rule_neural_act_vtbl, rule_neural_cond_vtbl, RULE_TYPE_DGP, RULE_TYPE_NEURAL, and ArgsCond::type.
Referenced by cl_load(), and cl_rand().
condition_type_as_int()
int condition_type_as_int (const char * type)
Returns the integer representation of a condition type given a name.
Parameters
[in] type String representation of a condition type.
Returns
Integer representing the condition type.
Definition at line 119 of file condition.c.
References COND_STRING_DGP, COND_STRING_DUMMY, COND_STRING_GP, COND_STRING_HYPERELLIPSOID, COND_STRING_HYPERRECTANGLE, COND_STRING_NEURAL, COND_STRING_RULE_DGP, COND_STRING_RULE_NETWORK, COND_STRING_RULE_NEURAL, COND_STRING_TERNARY, COND_TYPE_DGP, COND_TYPE_DUMMY, COND_TYPE_GP, COND_TYPE_HYPERELLIPSOID, COND_TYPE_HYPERRECTANGLE, COND_TYPE_NEURAL, COND_TYPE_TERNARY, RULE_TYPE_DGP, RULE_TYPE_NETWORK, and RULE_TYPE_NEURAL.
Referenced by cond_param_set_type_string().
condition_type_as_string()
const char* condition_type_as_string (const int type)
Returns a string representation of a condition type from an integer.
Parameters
[in] type Integer representation of a condition type.
Returns
String representing the name of the condition type.
Definition at line 84 of file condition.c.
References COND_STRING_DGP, COND_STRING_DUMMY, COND_STRING_GP, COND_STRING_HYPERELLIPSOID, COND_STRING_HYPERRECTANGLE, COND_STRING_NEURAL, COND_STRING_RULE_DGP, COND_STRING_RULE_NETWORK, COND_STRING_RULE_NEURAL, COND_STRING_TERNARY, COND_TYPE_DGP, COND_TYPE_DUMMY, COND_TYPE_GP, COND_TYPE_HYPERELLIPSOID, COND_TYPE_HYPERRECTANGLE, COND_TYPE_NEURAL, COND_TYPE_TERNARY, RULE_TYPE_DGP, RULE_TYPE_NETWORK, and RULE_TYPE_NEURAL.
Referenced by cond_param_print().