XCSF: cond_ternary.h File Reference
cond_ternary.h File Reference
Ternary condition functions.
#include "condition.h"
#include "xcsf.h"
Data Structures
struct CondTernary
Ternary condition data structure.
Functions
bool cond_ternary_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Performs uniform crossover with two ternary conditions.
bool cond_ternary_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Returns whether classifier c1 has a condition more general than c2.
bool cond_ternary_match (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Calculates whether a ternary condition matches an input.
bool cond_ternary_mutate (const struct XCSF *xcsf, const struct Cl *c)
Mutates a ternary condition.
void cond_ternary_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies a ternary condition from one classifier to another.
void cond_ternary_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Generates a ternary condition that matches the current input.
void cond_ternary_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by a ternary condition.
void cond_ternary_init (const struct XCSF *xcsf, struct Cl *c)
Creates and initialises a ternary bitstring condition.
void cond_ternary_print (const struct XCSF *xcsf, const struct Cl *c)
Prints a ternary condition.
void cond_ternary_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Dummy update function.
double cond_ternary_size (const struct XCSF *xcsf, const struct Cl *c)
Returns the size of a ternary condition.
size_t cond_ternary_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes a ternary condition to a file.
size_t cond_ternary_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads a ternary condition from a file.
const char * cond_ternary_json_export (const struct XCSF *xcsf, const struct Cl *c)
Returns a json formatted string representation of a ternary condition.
Variables
static struct CondVtbl const cond_ternary_vtbl
Ternary condition implemented functions.
Detailed Description
Ternary condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2021.
Definition in file cond_ternary.h.
Function Documentation
cond_ternary_copy()
void cond_ternary_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Copies a ternary condition from one classifier to another.
Parameters
[in] xcsf The XCSF data structure.
[in] dest The destination classifier.
[in] src The source classifier.
Definition at line 99 of file cond_ternary.c.
References ArgsCond::bits, Cl::cond, XCSF::cond, CondTernary::length, CondTernary::mu, N_MU, and CondTernary::string.
cond_ternary_cover()
void cond_ternary_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Generates a ternary condition that matches the current input.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is being covered.
[in] x The input state to cover.
Definition at line 120 of file cond_ternary.c.
References ArgsCond::bits, Cl::cond, XCSF::cond, DONT_CARE, float_to_binary(), ArgsCond::p_dontcare, rand_uniform(), CondTernary::string, CondTernary::tmp_input, and XCSF::x_dim.
cond_ternary_crossover()
bool cond_ternary_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Performs uniform crossover with two ternary conditions.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The first classifier whose condition is being crossed.
[in] c2 The second classifier whose condition is being crossed.
Returns
Whether any alterations were made.
Definition at line 185 of file cond_ternary.c.
References Cl::cond, XCSF::ea, CondTernary::length, ArgsEA::p_crossover, rand_uniform(), and CondTernary::string.
cond_ternary_free()
void cond_ternary_free (const struct XCSF * xcsf, const struct Cl * c)
Frees the memory used by a ternary condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be freed.
Definition at line 82 of file cond_ternary.c.
References Cl::cond, CondTernary::mu, CondTernary::string, and CondTernary::tmp_input.
cond_ternary_general()
bool cond_ternary_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Returns whether classifier c1 has a condition more general than c2.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The classifier whose condition is tested to be more general.
[in] c2 The classifier whose condition is tested to be more specific.
Returns
Whether the condition of c1 is more general than c2.
Definition at line 238 of file cond_ternary.c.
References Cl::cond, DONT_CARE, CondTernary::length, and CondTernary::string.
cond_ternary_init()
void cond_ternary_init (const struct XCSF * xcsf, struct Cl * c)
Creates and initialises a ternary bitstring condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be initialised.
Definition at line 64 of file cond_ternary.c.
References ArgsCond::bits, Cl::cond, XCSF::cond, cond_ternary_rand(), MU_TYPE, N_MU, sam_init(), and XCSF::x_dim.
cond_ternary_json_export()
const char* cond_ternary_json_export (const struct XCSF * xcsf, const struct Cl * c)
Returns a json formatted string representation of a ternary condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be returned.
Returns
String encoded in json format.
Definition at line 336 of file cond_ternary.c.
References Cl::cond, CondTernary::length, CondTernary::mu, N_MU, and CondTernary::string.
Referenced by cond_ternary_print().
cond_ternary_load()
size_t cond_ternary_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Reads a ternary condition from a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 309 of file cond_ternary.c.
References ArgsCond::bits, Cl::cond, XCSF::cond, and N_MU.
cond_ternary_match()
bool cond_ternary_match (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Calculates whether a ternary condition matches an input.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition to match.
[in] x The input state.
Returns
Whether the condition matches the input.
Definition at line 161 of file cond_ternary.c.
References ArgsCond::bits, Cl::cond, XCSF::cond, DONT_CARE, float_to_binary(), CondTernary::string, CondTernary::tmp_input, and XCSF::x_dim.
cond_ternary_mutate()
bool cond_ternary_mutate (const struct XCSF * xcsf, const struct Cl * c)
Mutates a ternary condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is being mutated.
Returns
Whether any alterations were made.
Definition at line 211 of file cond_ternary.c.
References Cl::cond, DONT_CARE, CondTernary::length, CondTernary::mu, MU_TYPE, N_MU, rand_uniform(), sam_adapt(), and CondTernary::string.
cond_ternary_print()
void cond_ternary_print (const struct XCSF * xcsf, const struct Cl * c)
Prints a ternary condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be printed.
Definition at line 263 of file cond_ternary.c.
References cond_ternary_json_export().
cond_ternary_save()
size_t cond_ternary_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Writes a ternary condition to a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 290 of file cond_ternary.c.
References Cl::cond, CondTernary::length, CondTernary::mu, N_MU, and CondTernary::string.
cond_ternary_size()
double cond_ternary_size (const struct XCSF * xcsf, const struct Cl * c)
Returns the size of a ternary condition.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose condition size to return.
Returns
The size of the condition.
Definition at line 275 of file cond_ternary.c.
References Cl::cond, and CondTernary::length.
cond_ternary_update()
void cond_ternary_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Dummy update function.
Parameters
[in] xcsf The XCSF data structure.
[in] c Classifier whose condition is to be updated.
[in] x Input state.
[in] y Truth/payoff value.
Definition at line 144 of file cond_ternary.c.
Variable Documentation
cond_ternary_vtbl
struct CondVtbl const cond_ternary_vtbl static
Initial value:
= {
    &cond_ternary_crossover, &cond_ternary_general,    &cond_ternary_match,
    &cond_ternary_mutate,    &cond_ternary_copy,       &cond_ternary_cover,
    &cond_ternary_free,      &cond_ternary_init,       &cond_ternary_print,
    &cond_ternary_update,    &cond_ternary_size,       &cond_ternary_save,
    &cond_ternary_load,      &cond_ternary_json_export
}
Ternary condition implemented functions.
Definition at line 90 of file cond_ternary.h.
Referenced by condition_set().