XCSF: cond_rectangle.c File Reference
cond_rectangle.c File Reference
Hyperrectangle condition functions.
#include "cond_rectangle.h"
#include "ea.h"
#include "sam.h"
#include "utils.h"
Macros
#define N_MU (1)
Number of hyperrectangle mutation rates.
Functions
void cond_rectangle_init (const struct XCSF *xcsf, struct Cl *c)
Creates and initialises a hyperrectangle condition.
void cond_rectangle_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by a hyperrectangle condition.
void cond_rectangle_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies a hyperrectangle condition from one classifier to another.
void cond_rectangle_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Generates a hyperrectangle that matches the current input.
void cond_rectangle_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Updates a hyperrectangle, sliding the centers towards the mean input.
bool cond_rectangle_match (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Calculates whether a hyperrectangle condition matches an input.
bool cond_rectangle_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Performs uniform crossover with two hyperrectangle conditions.
bool cond_rectangle_mutate (const struct XCSF *xcsf, const struct Cl *c)
Mutates a hyperrectangle condition with the self-adaptive rate.
bool cond_rectangle_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Returns whether classifier c1 has a condition more general than c2.
void cond_rectangle_print (const struct XCSF *xcsf, const struct Cl *c)
Prints a hyperrectangle condition.
double cond_rectangle_size (const struct XCSF *xcsf, const struct Cl *c)
Returns the size of a hyperrectangle condition.
size_t cond_rectangle_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes a hyperrectangle condition to a file.
size_t cond_rectangle_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads a hyperrectangle condition from a file.
char * cond_rectangle_json_export (const struct XCSF *xcsf, const struct Cl *c)
Returns a json formatted string representation of a hyperrectangle.
void cond_rectangle_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Creates a hyperrectangle from a cJSON object.
Variables
static const int MU_TYPE [(1)] = { (0) }
Self-adaptation method for mutating hyperrectangles.
Detailed Description
Hyperrectangle condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2023.
Definition in file cond_rectangle.c.
Macro Definition Documentation
N_MU
#define N_MU (1)
Number of hyperrectangle mutation rates.
Definition at line 29 of file cond_rectangle.c.
Function Documentation
cond_rectangle_copy()
void cond_rectangle_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Copies a hyperrectangle condition from one classifier to another.
Parameters
[in] xcsf XCSF data structure.
[in] dest Destination classifier.
[in] src Source classifier.
Definition at line 86 of file cond_rectangle.c.
References CondRectangle::b1, CondRectangle::b2, Cl::cond, CondRectangle::mu, and N_MU.
cond_rectangle_cover()
void cond_rectangle_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Generates a hyperrectangle that matches the current input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is being covered.
[in] x Input state to cover.
Definition at line 107 of file cond_rectangle.c.
References CondRectangle::b1, CondRectangle::b2, Cl::cond, COND_TYPE_HYPERRECTANGLE_CSR, and rand_uniform().
cond_rectangle_crossover()
bool cond_rectangle_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Performs uniform crossover with two hyperrectangle conditions.
Parameters
[in] xcsf XCSF data structure.
[in] c1 First classifier whose condition is being crossed.
[in] c2 Second classifier whose condition is being crossed.
Returns
Whether any alterations were made.
Definition at line 188 of file cond_rectangle.c.
References CondRectangle::b1, CondRectangle::b2, Cl::cond, and rand_uniform().
cond_rectangle_free()
void cond_rectangle_free (const struct XCSF * xcsf, const struct Cl * c)
Frees the memory used by a hyperrectangle condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be freed.
Definition at line 69 of file cond_rectangle.c.
References CondRectangle::b1, CondRectangle::b2, Cl::cond, and CondRectangle::mu.
cond_rectangle_general()
bool cond_rectangle_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Returns whether classifier c1 has a condition more general than c2.
Parameters
[in] xcsf XCSF data structure.
[in] c1 Classifier whose condition is tested to be more general.
[in] c2 Classifier whose condition is tested to be more specific.
Returns
Whether the hyperrectangle condition of c1 is more general than c2.
Definition at line 256 of file cond_rectangle.c.
References CondRectangle::b1, CondRectangle::b2, Cl::cond, and COND_TYPE_HYPERRECTANGLE_CSR.
cond_rectangle_init()
void cond_rectangle_init (const struct XCSF * xcsf, struct Cl * c)
Creates and initialises a hyperrectangle condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be initialised.
Definition at line 42 of file cond_rectangle.c.
References Cl::cond, COND_TYPE_HYPERRECTANGLE_CSR, MU_TYPE, N_MU, rand_uniform(), and sam_init().
cond_rectangle_json_export()
char* cond_rectangle_json_export (const struct XCSF * xcsf, const struct Cl * c)
Returns a json formatted string representation of a hyperrectangle.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be returned.
Returns
String encoded in json format.
Definition at line 358 of file cond_rectangle.c.
References CondRectangle::b1, CondRectangle::b2, Cl::cond, COND_TYPE_HYPERRECTANGLE_CSR, CondRectangle::mu, and N_MU.
Referenced by cond_rectangle_print().
cond_rectangle_json_import()
void cond_rectangle_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json)
Creates a hyperrectangle from a cJSON object.
Parameters
[in] xcsf The XCSF data structure.
[in,out] c The classifier to initialise.
[in] json cJSON object.
Definition at line 387 of file cond_rectangle.c.
References CondRectangle::b1, CondRectangle::b2, Cl::cond, COND_TYPE_HYPERRECTANGLE_CSR, CondRectangle::mu, N_MU, and sam_json_import().
cond_rectangle_load()
size_t cond_rectangle_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Reads a hyperrectangle condition from a file.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 337 of file cond_rectangle.c.
References Cl::cond, and N_MU.
cond_rectangle_match()
bool cond_rectangle_match (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Calculates whether a hyperrectangle condition matches an input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition to match.
[in] x Input state.
Returns
Whether the hyperrectangle condition matches the input.
Definition at line 156 of file cond_rectangle.c.
References CondRectangle::b1, CondRectangle::b2, Cl::cond, and COND_TYPE_HYPERRECTANGLE_CSR.
cond_rectangle_mutate()
bool cond_rectangle_mutate (const struct XCSF * xcsf, const struct Cl * c)
Mutates a hyperrectangle condition with the self-adaptive rate.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is being mutated.
Returns
Whether any alterations were made.
Definition at line 220 of file cond_rectangle.c.
References CondRectangle::b1, CondRectangle::b2, clamp(), Cl::cond, COND_TYPE_HYPERRECTANGLE_CSR, CondRectangle::mu, MU_TYPE, N_MU, rand_normal(), and sam_adapt().
cond_rectangle_print()
void cond_rectangle_print (const struct XCSF * xcsf, const struct Cl * c)
Prints a hyperrectangle condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be printed.
Definition at line 291 of file cond_rectangle.c.
References cond_rectangle_json_export().
cond_rectangle_save()
size_t cond_rectangle_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Writes a hyperrectangle condition to a file.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 319 of file cond_rectangle.c.
References CondRectangle::b1, CondRectangle::b2, Cl::cond, CondRectangle::mu, and N_MU.
cond_rectangle_size()
double cond_rectangle_size (const struct XCSF * xcsf, const struct Cl * c)
Returns the size of a hyperrectangle condition.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition size to return.
Returns
The length of the input dimension.
Definition at line 305 of file cond_rectangle.c.
cond_rectangle_update()
void cond_rectangle_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Updates a hyperrectangle, sliding the centers towards the mean input.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose condition is to be updated.
[in] x Input state.
[in] y Truth/payoff value.
Definition at line 135 of file cond_rectangle.c.
References CondRectangle::b1, Cl::cond, and COND_TYPE_HYPERRECTANGLE_CSR.
Variable Documentation
MU_TYPE
const int MU_TYPE[(1)] = { (0) } static
Self-adaptation method for mutating hyperrectangles.
Definition at line 34 of file cond_rectangle.c.
Referenced by cond_rectangle_init(), and cond_rectangle_mutate().