XCSF: config.h File Reference
config.h File Reference
Configuration file handling functions.
#include "xcsf.h"
Functions
void config_read (struct XCSF *xcsf, const char *filename)
Reads the specified configuration file.
Detailed Description
Configuration file handling functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file config.h.
Function Documentation
config_read()
void config_read (struct XCSF * xcsf, const char * filename)
Reads the specified configuration file.
Parameters
[in] xcsf The XCSF data structure.
[in] filename The name of the configuration file.
Definition at line 622 of file config.c.
References XCSF::act, XCSF::cond, config_process(), config_trim(), current_layer, ArgsAct::largs, ArgsPred::largs, ArgsCond::largs, layer_args_free(), layer_args_validate(), MAXLEN, XCSF::pred, ArgsCond::targs, and tree_args_init_constants().
Referenced by main(), and XCS::XCS().