XCSF: config.c File Reference
config.c File Reference
Configuration file handling functions.
#include "config.h"
#include "action.h"
#include "condition.h"
#include "dgp.h"
#include "ea.h"
#include "gp.h"
#include "neural_activations.h"
#include "neural_layer.h"
#include "param.h"
#include "prediction.h"
Macros
#define MAXLEN (127)
Maximum config file line length to read.
#define BASE (10)
Decimal numbers.
Functions
static void config_general (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets general XCSF parameters.
static void config_multi (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets multistep experiment parameters.
static void config_subsump (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets subsumption parameters.
static void config_ea (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets evolutionary algorithm parameters.
static void config_cl_gen (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets general classifier parameters.
static void config_layer (const char *n, const char *v, const int i, const double f)
Sets neural network layer parameters.
static void config_cl_cond_neural (struct XCSF *xcsf, const char *n, const char *v)
Sets classifier neural network condition parameters.
static void config_cl_cond_dgp (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets classifier DGP condition parameters.
static void config_cl_cond_gp (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets classifier tree GP condition parameters.
static void config_cl_cond_csr (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets classifier center-spread-representation condition parameters.
static void config_cl_cond_ternary (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets classifier ternary condition parameters.
static void config_cl_cond (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets classifier condition parameters.
static void config_cl_pred_neural (struct XCSF *xcsf, const char *n, const char *v)
Sets classifier neural network prediction parameters.
static void config_cl_pred_ls (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets classifier least squares prediction parameters.
static void config_cl_pred (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets classifier prediction parameters.
static void config_cl_act_neural (struct XCSF *xcsf, const char *n, const char *v)
Sets classifier neural network action parameters.
static void config_cl_act (struct XCSF *xcsf, const char *n, const char *v, const int i, const double f)
Sets classifier action parameters.
static void config_add_param (struct XCSF *xcsf, const char *name, const char *value)
Sets specified parameter.
static void config_trim (char *s)
Removes tabs/spaces/lf/cr.
static void config_newnvpair (struct XCSF *xcsf, const char *param)
Adds a parameter to the list.
static void config_process (struct XCSF *xcsf, const char *configline)
Parses a line of the config file and adds to the list.
void config_read (struct XCSF *xcsf, const char *filename)
Reads the specified configuration file.
Variables
struct ArgsLayer * current_layer
Current layer parameters being read.
Detailed Description
Configuration file handling functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file config.c.
Macro Definition Documentation
BASE
#define BASE (10)
Decimal numbers.
Definition at line 36 of file config.c.
MAXLEN
#define MAXLEN (127)
Maximum config file line length to read.
Definition at line 35 of file config.c.
Function Documentation
config_add_param()
static void config_add_param (struct XCSF * xcsf, const char * name, const char * value) static
Sets specified parameter.
Parameters
[in] xcsf The XCSF data structure.
[in] name Parameter name.
[in] value Parameter value.
Definition at line 517 of file config.c.
References BASE, config_cl_act(), config_cl_cond(), config_cl_gen(), config_cl_pred(), config_ea(), config_general(), config_layer(), config_multi(), config_subsump(), and current_layer.
Referenced by config_newnvpair().
config_cl_act()
static void config_cl_act (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets classifier action parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 499 of file config.c.
References action_param_set_type_string(), and config_cl_act_neural().
Referenced by config_add_param().
config_cl_act_neural()
static void config_cl_act_neural (struct XCSF * xcsf, const char * n, const char * v) static
Sets classifier neural network action parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
Definition at line 470 of file config.c.
References XCSF::act, current_layer, ArgsAct::largs, layer_args_init(), layer_args_tail(), layer_type_as_int(), XCSF::n_actions, ArgsLayer::n_init, ArgsLayer::n_inputs, ArgsLayer::next, ArgsLayer::type, and XCSF::x_dim.
Referenced by config_cl_act().
config_cl_cond()
static void config_cl_cond (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets classifier condition parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 376 of file config.c.
References cond_param_set_type_string(), config_cl_cond_csr(), config_cl_cond_dgp(), config_cl_cond_gp(), config_cl_cond_neural(), and config_cl_cond_ternary().
Referenced by config_add_param().
config_cl_cond_csr()
static void config_cl_cond_csr (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets classifier center-spread-representation condition parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 331 of file config.c.
References cond_param_set_eta(), cond_param_set_max(), cond_param_set_min(), and cond_param_set_spread_min().
Referenced by config_cl_cond().
config_cl_cond_dgp()
static void config_cl_cond_dgp (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets classifier DGP condition parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 280 of file config.c.
References XCSF::cond, ArgsCond::dargs, graph_param_set_evolve_cycles(), graph_param_set_max_k(), graph_param_set_max_t(), and graph_param_set_n().
Referenced by config_cl_cond().
config_cl_cond_gp()
static void config_cl_cond_gp (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets classifier tree GP condition parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 305 of file config.c.
References XCSF::cond, ArgsCond::targs, tree_param_set_init_depth(), tree_param_set_max(), tree_param_set_max_len(), tree_param_set_min(), and tree_param_set_n_constants().
Referenced by config_cl_cond().
config_cl_cond_neural()
static void config_cl_cond_neural (struct XCSF * xcsf, const char * n, const char * v) static
Sets classifier neural network condition parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
Definition at line 249 of file config.c.
References XCSF::cond, current_layer, ArgsCond::largs, layer_args_init(), layer_args_tail(), layer_type_as_int(), XCSF::n_actions, ArgsLayer::n_init, ArgsLayer::n_inputs, ArgsLayer::next, RULE_TYPE_NEURAL, ArgsLayer::type, ArgsCond::type, and XCSF::x_dim.
Referenced by config_cl_cond().
config_cl_cond_ternary()
static void config_cl_cond_ternary (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets classifier ternary condition parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 356 of file config.c.
References cond_param_set_bits(), and cond_param_set_p_dontcare().
Referenced by config_cl_cond().
config_cl_gen()
static void config_cl_gen (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets general classifier parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 152 of file config.c.
References param_set_alpha(), param_set_beta(), param_set_compaction(), param_set_delta(), param_set_e0(), param_set_init_error(), param_set_init_fitness(), param_set_m_probation(), param_set_nu(), param_set_stateful(), and param_set_theta_del().
Referenced by config_add_param().
config_cl_pred()
static void config_cl_pred (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets classifier prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 453 of file config.c.
References config_cl_pred_ls(), config_cl_pred_neural(), and pred_param_set_type_string().
Referenced by config_add_param().
config_cl_pred_ls()
static void config_cl_pred_ls (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets classifier least squares prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 425 of file config.c.
References pred_param_set_eta(), pred_param_set_eta_min(), pred_param_set_evolve_eta(), pred_param_set_lambda(), pred_param_set_scale_factor(), and pred_param_set_x0().
Referenced by config_cl_pred().
config_cl_pred_neural()
static void config_cl_pred_neural (struct XCSF * xcsf, const char * n, const char * v) static
Sets classifier neural network prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
Definition at line 396 of file config.c.
References current_layer, ArgsPred::largs, layer_args_init(), layer_args_tail(), layer_type_as_int(), ArgsLayer::n_init, ArgsLayer::n_inputs, ArgsLayer::next, XCSF::pred, ArgsLayer::type, XCSF::x_dim, and XCSF::y_dim.
Referenced by config_cl_pred().
config_ea()
static void config_ea (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets evolutionary algorithm parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 121 of file config.c.
References ea_param_set_err_reduc(), ea_param_set_fit_reduc(), ea_param_set_lambda(), ea_param_set_p_crossover(), ea_param_set_pred_reset(), ea_param_set_select_size(), ea_param_set_theta(), and ea_param_set_type_string().
Referenced by config_add_param().
config_general()
static void config_general (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets general XCSF parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 49 of file config.c.
References param_set_huber_delta(), param_set_loss_func_string(), param_set_max_trials(), param_set_omp_num_threads(), param_set_perf_trials(), param_set_pop_init(), and param_set_pop_size().
Referenced by config_add_param().
config_layer()
static void config_layer (const char * n, const char * v, const int i, const double f) static
Sets neural network layer parameters.
Parameters
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 189 of file config.c.
References ArgsLayer::channels, current_layer, ArgsLayer::decay, ArgsLayer::eta, ArgsLayer::eta_min, ArgsLayer::evolve_connect, ArgsLayer::evolve_eta, ArgsLayer::evolve_functions, ArgsLayer::evolve_neurons, ArgsLayer::evolve_weights, ArgsLayer::function, ArgsLayer::height, ArgsLayer::max_neuron_grow, ArgsLayer::momentum, ArgsLayer::n_init, ArgsLayer::n_inputs, ArgsLayer::n_max, neural_activation_as_int(), ArgsLayer::pad, ArgsLayer::probability, ArgsLayer::recurrent_function, ArgsLayer::scale, ArgsLayer::sgd_weights, ArgsLayer::size, ArgsLayer::stride, and ArgsLayer::width.
Referenced by config_add_param().
config_multi()
static void config_multi (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets multistep experiment parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 78 of file config.c.
References param_set_gamma(), param_set_p_explore(), and param_set_teletransportation().
Referenced by config_add_param().
config_newnvpair()
static void config_newnvpair (struct XCSF * xcsf, const char * param) static
Adds a parameter to the list.
Parameters
[in] xcsf The XCSF data structure.
[in] param The parameter to add.
Definition at line 563 of file config.c.
References config_add_param(), and MAXLEN.
Referenced by config_process().
config_process()
static void config_process (struct XCSF * xcsf, const char * configline) static
Parses a line of the config file and adds to the list.
Parameters
[in] xcsf The XCSF data structure.
[in] configline A single line of the configuration file.
Definition at line 601 of file config.c.
References config_newnvpair(), and MAXLEN.
Referenced by config_read().
config_read()
void config_read (struct XCSF * xcsf, const char * filename)
Reads the specified configuration file.
Parameters
[in] xcsf The XCSF data structure.
[in] filename The name of the configuration file.
Definition at line 622 of file config.c.
References XCSF::act, XCSF::cond, config_process(), config_trim(), current_layer, ArgsAct::largs, ArgsPred::largs, ArgsCond::largs, layer_args_free(), layer_args_validate(), MAXLEN, XCSF::pred, ArgsCond::targs, and tree_args_init_constants().
Referenced by main().
config_subsump()
static void config_subsump (struct XCSF * xcsf, const char * n, const char * v, const int i, const double f) static
Sets subsumption parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] n String representation of the parameter name.
[in] v String representation of the parameter value.
[in] i Integer representation of the parameter value.
[in] f Float representation of the parameter value.
Definition at line 100 of file config.c.
References param_set_set_subsumption(), and param_set_theta_sub().
Referenced by config_add_param().
config_trim()
static void config_trim (char * s) static
Removes tabs/spaces/lf/cr.
Parameters
[in] s The line to trim.
Definition at line 547 of file config.c.
Referenced by config_read().
Variable Documentation
current_layer
struct ArgsLayer* current_layer
Current layer parameters being read.
Definition at line 38 of file config.c.
Referenced by config_add_param(), config_cl_act_neural(), config_cl_cond_neural(), config_cl_pred_neural(), config_layer(), and config_read().