XCSF: dgp.h File Reference
dgp.h File Reference
An implementation of dynamical GP graphs with fuzzy activations.
#include "xcsf.h"
Data Structures
struct ArgsDGP
Parameters for initialising DGP graphs.
struct Graph
Dynamical GP graph data structure.
Functions
bool graph_mutate (struct Graph *dgp)
Mutates a specified DGP graph.
char * graph_json_export (const struct Graph *dgp)
Returns a json formatted string representation of a DGP graph.
void graph_json_import (struct Graph *dgp, const struct ArgsDGP *args, const cJSON *json)
Creates a DGP graph from a cJSON object.
double graph_output (const struct Graph *dgp, const int IDX)
Returns the current state of a specified node in the graph.
size_t graph_load (struct Graph *dgp, FILE *fp)
Reads DGP graph from a file.
size_t graph_save (const struct Graph *dgp, FILE *fp)
Writes DGP graph to a file.
void graph_copy (struct Graph *dest, const struct Graph *src)
Copies a DGP graph.
void graph_free (const struct Graph *dgp)
Frees a DGP graph.
void graph_init (struct Graph *dgp, const struct ArgsDGP *args)
Initialises a new DGP graph.
void graph_print (const struct Graph *dgp)
Prints a DGP graph.
void graph_rand (struct Graph *dgp)
Randomises a specified DGP graph.
void graph_reset (const struct Graph *dgp)
Resets the states to their initial state.
void graph_update (const struct Graph *dgp, const double *inputs, const bool reset)
Updates a DGP graph T cycles.
void graph_args_init (struct ArgsDGP *args)
Sets DGP parameters to default values.
char * graph_args_json_import (struct ArgsDGP *args, cJSON *json)
Sets the DGP graph parameters from a cJSON object.
char * graph_args_json_export (const struct ArgsDGP *args)
Returns a json formatted string of the DGP parameters.
size_t graph_args_save (const struct ArgsDGP *args, FILE *fp)
Saves DGP parameters.
size_t graph_args_load (struct ArgsDGP *args, FILE *fp)
Loads DGP parameters.
void graph_param_set_max_k (struct ArgsDGP *args, const int a)
void graph_param_set_max_t (struct ArgsDGP *args, const int a)
void graph_param_set_n (struct ArgsDGP *args, const int a)
void graph_param_set_n_inputs (struct ArgsDGP *args, const int a)
void graph_param_set_evolve_cycles (struct ArgsDGP *args, const bool a)
Detailed Description
An implementation of dynamical GP graphs with fuzzy activations.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2022.
Definition in file dgp.h.
Function Documentation
graph_args_init()
void graph_args_init (struct ArgsDGP * args)
Sets DGP parameters to default values.
Parameters
[in] args Parameters for initialising and operating DGP graphs.
Definition at line 621 of file dgp.c.
References ArgsDGP::evolve_cycles, ArgsDGP::max_k, ArgsDGP::max_t, ArgsDGP::n, and ArgsDGP::n_inputs.
Referenced by cond_dgp_param_defaults().
graph_args_json_export()
char* graph_args_json_export (const struct ArgsDGP * args)
Returns a json formatted string of the DGP parameters.
Parameters
[in] args Parameters for initialising and operating DGP graphs.
Returns
String encoded in json format.
Definition at line 636 of file dgp.c.
References ArgsDGP::evolve_cycles, ArgsDGP::max_k, ArgsDGP::max_t, and ArgsDGP::n.
Referenced by cond_dgp_param_json_export().
graph_args_json_import()
char* graph_args_json_import (struct ArgsDGP * args, cJSON * json)
Sets the DGP graph parameters from a cJSON object.
Parameters
[in,out] args DGP parameter data structure.
[in] json cJSON object.
Returns
NULL if successful; or the name of parameter if not found.
Definition at line 655 of file dgp.c.
References graph_param_set_evolve_cycles(), graph_param_set_max_k(), graph_param_set_max_t(), and graph_param_set_n().
Referenced by cond_dgp_param_json_import().
graph_args_load()
size_t graph_args_load (struct ArgsDGP * args, FILE * fp)
Loads DGP parameters.
Parameters
[in] args Parameters for initialising and operating DGP graphs.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 701 of file dgp.c.
References ArgsDGP::evolve_cycles, ArgsDGP::max_k, ArgsDGP::max_t, ArgsDGP::n, and ArgsDGP::n_inputs.
Referenced by cond_param_load().
graph_args_save()
size_t graph_args_save (const struct ArgsDGP * args, FILE * fp)
Saves DGP parameters.
Parameters
[in] args Parameters for initialising and operating DGP graphs.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 683 of file dgp.c.
References ArgsDGP::evolve_cycles, ArgsDGP::max_k, ArgsDGP::max_t, ArgsDGP::n, and ArgsDGP::n_inputs.
Referenced by cond_param_save().
graph_copy()
void graph_copy (struct Graph * dest, const struct Graph * src)
Copies a DGP graph.
Parameters
[in] dest The destination DGP graph.
[in] src The source DGP graph.
Definition at line 251 of file dgp.c.
References Graph::connectivity, Graph::evolve_cycles, Graph::function, Graph::initial_state, Graph::klen, Graph::max_k, Graph::max_t, Graph::mu, Graph::n, Graph::n_inputs, N_MU, Graph::state, and Graph::t.
Referenced by cond_dgp_copy(), and rule_dgp_cond_copy().
graph_free()
void graph_free (const struct Graph * dgp)
Frees a DGP graph.
Parameters
[in] dgp The DGP graph to be freed.
Definition at line 523 of file dgp.c.
References Graph::connectivity, Graph::function, Graph::initial_state, Graph::mu, Graph::state, Graph::tmp_input, and Graph::tmp_state.
Referenced by cond_dgp_free(), cond_dgp_json_import(), rule_dgp_cond_free(), and rule_dgp_cond_json_import().
graph_init()
void graph_init (struct Graph * dgp, const struct ArgsDGP * args)
Initialises a new DGP graph.
Parameters
[in] dgp The DGP graph to initialise.
[in] args Parameters for initialising a DGP graph.
Definition at line 226 of file dgp.c.
References Graph::connectivity, ArgsDGP::evolve_cycles, Graph::evolve_cycles, Graph::function, Graph::initial_state, Graph::klen, ArgsDGP::max_k, Graph::max_k, ArgsDGP::max_t, Graph::max_t, Graph::mu, MU_TYPE, ArgsDGP::n, Graph::n, ArgsDGP::n_inputs, Graph::n_inputs, N_MU, sam_init(), Graph::state, Graph::t, Graph::tmp_input, and Graph::tmp_state.
Referenced by cond_dgp_copy(), cond_dgp_init(), rule_dgp_cond_copy(), and rule_dgp_cond_init().
graph_json_export()
char* graph_json_export (const struct Graph * dgp)
Returns a json formatted string representation of a DGP graph.
Parameters
[in] dgp The DGP graph to return.
Returns
String encoded in json format.
Definition at line 346 of file dgp.c.
References Graph::connectivity, Graph::function, function_string(), Graph::initial_state, Graph::klen, Graph::mu, Graph::n, Graph::n_inputs, N_MU, Graph::state, and Graph::t.
Referenced by cond_dgp_json_export(), graph_print(), and rule_dgp_cond_json_export().
graph_json_import()
void graph_json_import (struct Graph * dgp, const struct ArgsDGP * args, const cJSON * json)
Creates a DGP graph from a cJSON object.
Parameters
[in,out] dgp The DGP to initialise.
[in] args Parameters for initialising a DGP graph.
[in] json cJSON object.
Definition at line 477 of file dgp.c.
References Graph::connectivity, ArgsDGP::evolve_cycles, Graph::evolve_cycles, Graph::function, graph_json_import_connectivity(), graph_json_import_current_state(), graph_json_import_functions(), graph_json_import_initial_state(), graph_rand(), Graph::initial_state, Graph::klen, ArgsDGP::max_k, Graph::max_k, ArgsDGP::max_t, Graph::max_t, Graph::mu, ArgsDGP::n, Graph::n, ArgsDGP::n_inputs, Graph::n_inputs, N_MU, sam_json_import(), Graph::state, Graph::t, Graph::tmp_input, and Graph::tmp_state.
Referenced by cond_dgp_json_import(), and rule_dgp_cond_json_import().
graph_load()
size_t graph_load (struct Graph * dgp, FILE * fp)
Reads DGP graph from a file.
Parameters
[in] dgp The DGP graph to load.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 587 of file dgp.c.
References Graph::connectivity, Graph::evolve_cycles, Graph::function, Graph::initial_state, Graph::klen, Graph::max_k, Graph::max_t, Graph::mu, Graph::n, N_MU, Graph::state, Graph::t, Graph::tmp_input, and Graph::tmp_state.
Referenced by cond_dgp_load(), and rule_dgp_cond_load().
graph_mutate()
bool graph_mutate (struct Graph * dgp)
Mutates a specified DGP graph.
Parameters
[in] dgp The DGP graph to be mutated.
Returns
Whether any alterations were made.
Definition at line 540 of file dgp.c.
References Graph::evolve_cycles, graph_mutate_connectivity(), graph_mutate_cycles(), graph_mutate_functions(), Graph::mu, MU_TYPE, N_MU, and sam_adapt().
Referenced by cond_dgp_mutate(), and rule_dgp_cond_mutate().
graph_output()
double graph_output (const struct Graph * dgp, const int IDX)
Returns the current state of a specified node in the graph.
Parameters
[in] dgp The DGP graph to output.
[in] IDX Which node within the graph to output.
Returns
The current state of the specified node.
Definition at line 274 of file dgp.c.
References Graph::state.
Referenced by cond_dgp_match(), rule_dgp_act_compute(), and rule_dgp_cond_match().
graph_param_set_evolve_cycles()
void graph_param_set_evolve_cycles (struct ArgsDGP * args, const bool a)
Definition at line 759 of file dgp.c.
References ArgsDGP::evolve_cycles.
Referenced by cond_dgp_param_defaults(), and graph_args_json_import().
graph_param_set_max_k()
void graph_param_set_max_k (struct ArgsDGP * args, const int a)
Definition at line 715 of file dgp.c.
References ArgsDGP::max_k.
Referenced by cond_dgp_param_defaults(), and graph_args_json_import().
graph_param_set_max_t()
void graph_param_set_max_t (struct ArgsDGP * args, const int a)
Definition at line 726 of file dgp.c.
References ArgsDGP::max_t.
Referenced by cond_dgp_param_defaults(), and graph_args_json_import().
graph_param_set_n()
void graph_param_set_n (struct ArgsDGP * args, const int a)
Definition at line 737 of file dgp.c.
References ArgsDGP::n.
Referenced by cond_dgp_param_defaults(), and graph_args_json_import().
graph_param_set_n_inputs()
void graph_param_set_n_inputs (struct ArgsDGP * args, const int a)
Definition at line 748 of file dgp.c.
References ArgsDGP::n_inputs.
Referenced by cond_dgp_param_defaults().
graph_print()
void graph_print (const struct Graph * dgp)
Prints a DGP graph.
Parameters
[in] dgp The DGP graph to print.
Definition at line 333 of file dgp.c.
References graph_json_export().
graph_rand()
void graph_rand (struct Graph * dgp)
Randomises a specified DGP graph.
Parameters
[in] dgp The DGP graph to randomise.
Definition at line 296 of file dgp.c.
References Graph::connectivity, Graph::evolve_cycles, Graph::function, Graph::initial_state, Graph::klen, Graph::max_t, Graph::n, Graph::n_inputs, NUM_FUNC, rand_uniform(), rand_uniform_int(), random_connection(), Graph::state, and Graph::t.
Referenced by cond_dgp_cover(), cond_dgp_init(), graph_json_import(), rule_dgp_act_cover(), and rule_dgp_cond_init().
graph_reset()
void graph_reset (const struct Graph * dgp)
Resets the states to their initial state.
Parameters
[in] dgp The DGP graph to reset.
Definition at line 284 of file dgp.c.
References Graph::initial_state, Graph::n, and Graph::state.
Referenced by graph_update().
graph_save()
size_t graph_save (const struct Graph * dgp, FILE * fp)
Writes DGP graph to a file.
Parameters
[in] dgp The DGP graph to save.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 563 of file dgp.c.
References Graph::connectivity, Graph::evolve_cycles, Graph::function, Graph::initial_state, Graph::klen, Graph::max_k, Graph::max_t, Graph::mu, Graph::n, N_MU, Graph::state, and Graph::t.
Referenced by cond_dgp_save(), and rule_dgp_cond_save().
graph_update()
void graph_update (const struct Graph * dgp, const double * inputs, const bool reset)
Updates a DGP graph T cycles.
Parameters
[in] dgp The DGP graph to update.
[in] inputs The inputs to the graph.
[in] reset Whether to reset states to initial values.
Definition at line 318 of file dgp.c.
References graph_reset(), synchronous_update(), and Graph::t.
Referenced by cond_dgp_match(), and rule_dgp_cond_match().