XCSF: ea.c File Reference
ea.c File Reference
Evolutionary algorithm functions.
#include "ea.h"
#include "cl.h"
#include "clset.h"
#include "utils.h"
Functions
static void ea_init_offspring (const struct XCSF *xcsf, const struct Cl *c1p, const struct Cl *c2p, struct Cl *c1, struct Cl *c2, const bool cmod)
Initialises offspring error and fitness.
static void ea_subsume (struct XCSF *xcsf, struct Cl *c, struct Cl *c1p, struct Cl *c2p, const struct Set *set)
Performs evolutionary algorithm subsumption.
static void ea_add (struct XCSF *xcsf, const struct Set *set, struct Cl *c1p, struct Cl *c2p, struct Cl *c1, const bool cmod, const bool mmod)
Adds offspring to the population.
static struct Cl * ea_select_rw (const struct XCSF *xcsf, const struct Set *set, const double fit_sum)
Selects a classifier from the set via roulette wheel.
static struct Cl * ea_select_tournament (const struct XCSF *xcsf, const struct Set *set)
Selects a classifier from the set via tournament.
static void ea_select (const struct XCSF *xcsf, const struct Set *set, struct Cl **c1p, struct Cl **c2p)
Selects two parents.
void ea (struct XCSF *xcsf, const struct Set *set)
Executes the evolutionary algorithm (EA).
void ea_param_defaults (struct XCSF *xcsf)
Initialises default evolutionary algorithm parameters.
char * ea_param_json_export (const struct XCSF *xcsf)
Returns a json formatted string representation of the EA parameters.
void ea_param_json_import (struct XCSF *xcsf, cJSON *json)
Sets the EA parameters from a cJSON object.
size_t ea_param_save (const struct XCSF *xcsf, FILE *fp)
Saves evolutionary algorithm parameters.
size_t ea_param_load (struct XCSF *xcsf, FILE *fp)
Loads evolutionary algorithm parameters.
const char * ea_type_as_string (const int type)
Returns a string representation of an EA select type from an integer.
int ea_type_as_int (const char *type)
Returns the integer representation of an EA selection type.
const char * ea_param_set_select_size (struct XCSF *xcsf, const double a)
const char * ea_param_set_theta (struct XCSF *xcsf, const double a)
const char * ea_param_set_p_crossover (struct XCSF *xcsf, const double a)
const char * ea_param_set_lambda (struct XCSF *xcsf, const int a)
const char * ea_param_set_err_reduc (struct XCSF *xcsf, const double a)
const char * ea_param_set_fit_reduc (struct XCSF *xcsf, const double a)
const char * ea_param_set_subsumption (struct XCSF *xcsf, const bool a)
const char * ea_param_set_pred_reset (struct XCSF *xcsf, const bool a)
int ea_param_set_select_type (struct XCSF *xcsf, const int a)
int ea_param_set_type_string (struct XCSF *xcsf, const char *a)
Detailed Description
Evolutionary algorithm functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2022.
Definition in file ea.c.
Function Documentation
ea()
void ea (struct XCSF * xcsf, const struct Set * set)
Executes the evolutionary algorithm (EA).
Parameters
[in] xcsf The XCSF data structure.
[in] set The set in which to run the EA.
Definition at line 199 of file ea.c.
References cl_copy(), cl_crossover(), cl_init(), cl_mutate(), clset_mean_time(), clset_pset_enforce_limit(), clset_set_times(), ea_add(), ea_init_offspring(), ea_select(), Cl::size, Set::size, and Cl::time.
Referenced by xcs_rl_update(), and xcs_supervised_trial().
ea_add()
static void ea_add (struct XCSF * xcsf, const struct Set * set, struct Cl * c1p, struct Cl * c2p, struct Cl * c1, const bool cmod, const bool mmod) static
Adds offspring to the population.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set in which the EA is being run.
[in] c1p First parent classifier.
[in] c2p Second parent classifier.
[in] c1 The offspring classifier to add.
[in] cmod Whether crossover modified the offspring.
[in] mmod Whether mutation modified the offspring.
Definition at line 113 of file ea.c.
References cl_free(), clset_add(), ea_subsume(), and Cl::num.
Referenced by ea().
ea_init_offspring()
static void ea_init_offspring (const struct XCSF * xcsf, const struct Cl * c1p, const struct Cl * c2p, struct Cl * c1, struct Cl * c2, const bool cmod) static
Initialises offspring error and fitness.
Parameters
[in] xcsf The XCSF data structure.
[in] c1p First parent classifier.
[in] c2p Second parent classifier.
[in] c1 The first offspring classifier to initialise.
[in] c2 The second offspring classifier to initialise.
[in] cmod Whether crossover modified the offspring.
Definition at line 39 of file ea.c.
References Cl::err, Cl::fit, and Cl::num.
Referenced by ea().
ea_param_defaults()
void ea_param_defaults (struct XCSF * xcsf)
Initialises default evolutionary algorithm parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 237 of file ea.c.
References ea_param_set_err_reduc(), ea_param_set_fit_reduc(), ea_param_set_lambda(), ea_param_set_p_crossover(), ea_param_set_pred_reset(), ea_param_set_select_size(), ea_param_set_select_type(), ea_param_set_subsumption(), ea_param_set_theta(), and EA_SELECT_ROULETTE.
Referenced by param_init().
ea_param_json_export()
char* ea_param_json_export (const struct XCSF * xcsf)
Returns a json formatted string representation of the EA parameters.
Parameters
[in] xcsf XCSF data structure.
Returns
String encoded in json format.
Definition at line 256 of file ea.c.
References EA_SELECT_TOURNAMENT, and ea_type_as_string().
Referenced by param_json_export().
ea_param_json_import()
void ea_param_json_import (struct XCSF * xcsf, cJSON * json)
Sets the EA parameters from a cJSON object.
Parameters
[in,out] xcsf The XCSF data structure.
[in] json cJSON object.
Definition at line 282 of file ea.c.
References catch_error(), ea_param_set_err_reduc(), ea_param_set_fit_reduc(), ea_param_set_lambda(), ea_param_set_p_crossover(), ea_param_set_pred_reset(), ea_param_set_select_size(), ea_param_set_subsumption(), ea_param_set_theta(), ea_param_set_type_string(), EA_SELECT_INVALID, and EA_SELECT_OPTIONS.
Referenced by param_json_import().
ea_param_load()
size_t ea_param_load (struct XCSF * xcsf, FILE * fp)
Loads evolutionary algorithm parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 353 of file ea.c.
Referenced by param_load().
ea_param_save()
size_t ea_param_save (const struct XCSF * xcsf, FILE * fp)
Saves evolutionary algorithm parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 331 of file ea.c.
Referenced by param_save().
ea_param_set_err_reduc()
const char* ea_param_set_err_reduc (struct XCSF * xcsf, const double a)
Definition at line 446 of file ea.c.
Referenced by ea_param_defaults(), ea_param_json_import(), and XCS::set_err_reduc().
ea_param_set_fit_reduc()
const char* ea_param_set_fit_reduc (struct XCSF * xcsf, const double a)
Definition at line 456 of file ea.c.
Referenced by ea_param_defaults(), ea_param_json_import(), and XCS::set_fit_reduc().
ea_param_set_lambda()
const char* ea_param_set_lambda (struct XCSF * xcsf, const int a)
Definition at line 436 of file ea.c.
Referenced by ea_param_defaults(), ea_param_json_import(), and XCS::set_lambda().
ea_param_set_p_crossover()
const char* ea_param_set_p_crossover (struct XCSF * xcsf, const double a)
Definition at line 426 of file ea.c.
Referenced by ea_param_defaults(), ea_param_json_import(), and XCS::set_p_crossover().
ea_param_set_pred_reset()
const char* ea_param_set_pred_reset (struct XCSF * xcsf, const bool a)
Definition at line 473 of file ea.c.
Referenced by ea_param_defaults(), ea_param_json_import(), and XCS::set_ea_pred_reset().
ea_param_set_select_size()
const char* ea_param_set_select_size (struct XCSF * xcsf, const double a)
Definition at line 406 of file ea.c.
Referenced by ea_param_defaults(), ea_param_json_import(), and XCS::set_ea_select_size().
ea_param_set_select_type()
int ea_param_set_select_type (struct XCSF * xcsf, const int a)
Definition at line 480 of file ea.c.
References EA_SELECT_INVALID, EA_SELECT_ROULETTE, and EA_SELECT_TOURNAMENT.
Referenced by ea_param_defaults().
ea_param_set_subsumption()
const char* ea_param_set_subsumption (struct XCSF * xcsf, const bool a)
Definition at line 466 of file ea.c.
Referenced by ea_param_defaults(), ea_param_json_import(), and XCS::set_ea_subsumption().
ea_param_set_theta()
const char* ea_param_set_theta (struct XCSF * xcsf, const double a)
Definition at line 416 of file ea.c.
Referenced by ea_param_defaults(), ea_param_json_import(), and XCS::set_theta_ea().
ea_param_set_type_string()
int ea_param_set_type_string (struct XCSF * xcsf, const char * a)
Definition at line 490 of file ea.c.
References EA_SELECT_INVALID, and ea_type_as_int().
Referenced by ea_param_json_import(), and XCS::set_ea_select_type().
ea_select()
static void ea_select (const struct XCSF * xcsf, const struct Set * set, struct Cl ** c1p, struct Cl ** c2p) static
Selects two parents.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set in which the EA is being run.
[out] c1p First selected parent classifier.
[out] c2p Second selected parent classifier.
Definition at line 180 of file ea.c.
References clset_total_fit(), EA_SELECT_ROULETTE, ea_select_rw(), and ea_select_tournament().
Referenced by ea().
ea_select_rw()
static struct Cl* ea_select_rw (const struct XCSF * xcsf, const struct Set * set, const double fit_sum) static
Selects a classifier from the set via roulette wheel.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to select from.
[in] fit_sum The sum of all the fitnesses in the set.
Returns
A pointer to the selected classifier.
Definition at line 135 of file ea.c.
References Clist::cl, Cl::fit, Set::list, Clist::next, and rand_uniform().
Referenced by ea_select().
ea_select_tournament()
static struct Cl* ea_select_tournament (const struct XCSF * xcsf, const struct Set * set) static
Selects a classifier from the set via tournament.
Parameters
[in] xcsf The XCSF data structure.
[in] set The set to select from.
Returns
A pointer to the selected classifier.
Definition at line 156 of file ea.c.
References Clist::cl, Cl::fit, Set::list, Clist::next, and rand_uniform().
Referenced by ea_select().
ea_subsume()
static void ea_subsume (struct XCSF * xcsf, struct Cl * c, struct Cl * c1p, struct Cl * c2p, const struct Set * set) static
Performs evolutionary algorithm subsumption.
Parameters
[in] xcsf The XCSF data structure.
[in] c The offspring classifier to attempt to subsume.
[in] c1p First parent classifier.
[in] c2p Second parent classifier.
[in] set The set in which the EA is being run.
Definition at line 67 of file ea.c.
References Clist::cl, cl_free(), cl_general(), cl_subsumer(), clset_add(), Set::list, Clist::next, Cl::num, rand_uniform_int(), and Set::size.
Referenced by ea_add().
ea_type_as_int()
int ea_type_as_int (const char * type)
Returns the integer representation of an EA selection type.
Parameters
[in] type String representation of an EA type.
Returns
Integer representing the EA type.
Definition at line 392 of file ea.c.
References EA_SELECT_INVALID, EA_SELECT_ROULETTE, EA_SELECT_TOURNAMENT, EA_STRING_ROULETTE, and EA_STRING_TOURNAMENT.
Referenced by ea_param_set_type_string().
ea_type_as_string()
const char* ea_type_as_string (const int type)
Returns a string representation of an EA select type from an integer.
Parameters
[in] type Integer representation of an EA select type.
Returns
String representing the name of the EA select type.
Definition at line 374 of file ea.c.
References EA_SELECT_ROULETTE, EA_SELECT_TOURNAMENT, EA_STRING_ROULETTE, and EA_STRING_TOURNAMENT.
Referenced by ea_param_json_export(), and XCS::get_ea_select_type().