XCSF: env_csv.h File Reference
env_csv.h File Reference
CSV input file handling functions.
#include "env.h"
#include "xcsf.h"
Data Structures
struct EnvCSV
CSV environment data structure.
Functions
bool env_csv_is_done (const struct XCSF *xcsf)
Returns whether the csv environment is in a terminal state.
bool env_csv_multistep (const struct XCSF *xcsf)
Returns whether the csv environment is a multistep problem.
double env_csv_execute (const struct XCSF *xcsf, const int action)
Dummy method since no action is executed by the csv environment.
double env_csv_maxpayoff (const struct XCSF *xcsf)
Returns the maximum payoff value possible in the csv environment.
const double * env_csv_get_state (const struct XCSF *xcsf)
Dummy method since no state is returned by the csv environment.
void env_csv_free (const struct XCSF *xcsf)
Frees the csv environment.
void env_csv_init (struct XCSF *xcsf, const char *filename)
Initialises a CSV input environment from a specified filename.
void env_csv_reset (const struct XCSF *xcsf)
Dummy method since no csv environment reset is necessary.
Variables
static struct EnvVtbl const env_csv_vtbl
csv input environment implemented functions.
Detailed Description
CSV input file handling functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file env_csv.h.
Function Documentation
env_csv_execute()
double env_csv_execute (const struct XCSF * xcsf, const int action)
Dummy method since no action is executed by the csv environment.
Parameters
[in] xcsf The XCSF data structure.
[in] action The selected action.
Returns
0.
Definition at line 230 of file env_csv.c.
env_csv_free()
void env_csv_free (const struct XCSF * xcsf)
Frees the csv environment.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 177 of file env_csv.c.
References XCSF::env, EnvCSV::test_data, EnvCSV::train_data, Input::x, and Input::y.
env_csv_get_state()
const double* env_csv_get_state (const struct XCSF * xcsf)
Dummy method since no state is returned by the csv environment.
Parameters
[in] xcsf The XCSF data structure.
Returns
0.
Definition at line 217 of file env_csv.c.
env_csv_init()
void env_csv_init (struct XCSF * xcsf, const char * filename)
Initialises a CSV input environment from a specified filename.
Parameters
[in] xcsf The XCSF data structure.
[in] filename The file name of the csv data.
Definition at line 160 of file env_csv.c.
References XCSF::env, env_csv_input_read(), param_init(), EnvCSV::test_data, EnvCSV::train_data, Input::x_dim, and Input::y_dim.
Referenced by env_init().
env_csv_is_done()
bool env_csv_is_done (const struct XCSF * xcsf)
Returns whether the csv environment is in a terminal state.
Parameters
[in] xcsf The XCSF data structure.
Returns
True.
Definition at line 205 of file env_csv.c.
env_csv_maxpayoff()
double env_csv_maxpayoff (const struct XCSF * xcsf)
Returns the maximum payoff value possible in the csv environment.
Parameters
[in] xcsf The XCSF data structure.
Returns
0.
Definition at line 255 of file env_csv.c.
env_csv_multistep()
bool env_csv_multistep (const struct XCSF * xcsf)
Returns whether the csv environment is a multistep problem.
Parameters
[in] xcsf The XCSF data structure.
Returns
False.
Definition at line 243 of file env_csv.c.
env_csv_reset()
void env_csv_reset (const struct XCSF * xcsf)
Dummy method since no csv environment reset is necessary.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 194 of file env_csv.c.
Variable Documentation
env_csv_vtbl
struct EnvVtbl const env_csv_vtbl static
Initial value:
= {
    &env_csv_is_done,   &env_csv_multistep, &env_csv_execute,
    &env_csv_maxpayoff, &env_csv_get_state, &env_csv_free,
    &env_csv_reset
}
csv input environment implemented functions.
Definition at line 64 of file env_csv.h.
Referenced by env_init().