XCSF: gp.c File Reference
gp.c File Reference
An implementation of GP trees based upon TinyGP.
#include "gp.h"
#include "sam.h"
#include "utils.h"
Macros
#define GP_NUM_FUNC (4)
Number of selectable GP functions.
#define ADD (0)
Addition function.
#define SUB (1)
Subtraction function.
#define MUL (2)
Multiplication function.
#define DIV (3)
Division function.
#define STRING_ADD ("+\0")
Addition.
#define STRING_SUB ("-\0")
Subtraction.
#define STRING_MUL ("*\0")
Multiplication.
#define STRING_DIV ("/\0")
Division.
#define N_MU (1)
Number of tree-GP mutation rates.
#define RET_MIN (-1000)
Minimum tree return value.
#define RET_MAX (1000)
Maximum tree return value.
Functions
static int tree_traverse (int *tree, int pos)
Traverses a GP tree.
static int tree_grow (const struct ArgsGPTree *args, int *tree, const int pos, const int max, const int depth)
Grows a random GP tree of specified max length and depth.
void tree_rand (struct GPTree *gp, const struct ArgsGPTree *args)
Creates a random GP tree.
void tree_free (const struct GPTree *gp)
Frees a GP tree.
double tree_eval (struct GPTree *gp, const struct ArgsGPTree *args, const double *x)
Evaluates a GP tree.
static const char * tree_function_string (const int node)
Returns a string representation of a node function.
static int tree_function_int (const char *node)
Returns an integer representation of a node function.
static int tree_string (const struct GPTree *gp, const struct ArgsGPTree *args, int pos, cJSON *json)
Returns a json formatted string representation of a GP tree.
char * tree_json_export (const struct GPTree *gp, const struct ArgsGPTree *args)
Returns a json formatted string representation of a GP tree.
void tree_json_import (struct GPTree *gp, const struct ArgsGPTree *args, const cJSON *json)
Creates a GP tree from a cJSON object.
void tree_print (const struct GPTree *gp, const struct ArgsGPTree *args)
Prints a GP tree.
void tree_copy (struct GPTree *dest, const struct GPTree *src)
Copies a GP tree.
void tree_crossover (struct GPTree *p1, struct GPTree *p2)
Performs sub-tree crossover.
bool tree_mutate (struct GPTree *gp, const struct ArgsGPTree *args)
Performs point mutation on a GP tree.
size_t tree_save (const struct GPTree *gp, FILE *fp)
Writes the GP tree to a file.
size_t tree_load (struct GPTree *gp, FILE *fp)
Reads a GP tree from a file.
void tree_args_init (struct ArgsGPTree *args)
Sets tree GP parameters to default values.
void tree_args_free (struct ArgsGPTree *args)
Frees memory used by GP tree parameters.
char * tree_args_json_export (const struct ArgsGPTree *args)
Returns a json formatted string of the GP tree parameters.
void tree_args_json_import (struct ArgsGPTree *args, cJSON *json)
Sets the GP tree parameters from a cJSON object.
size_t tree_args_save (const struct ArgsGPTree *args, FILE *fp)
Saves Tree GP parameters.
size_t tree_args_load (struct ArgsGPTree *args, FILE *fp)
Loads Tree GP parameters.
void tree_args_init_constants (struct ArgsGPTree *args)
Builds global constants used by GP trees.
void tree_param_set_max (struct ArgsGPTree *args, const double a)
void tree_param_set_min (struct ArgsGPTree *args, const double a)
void tree_param_set_n_inputs (struct ArgsGPTree *args, const int a)
void tree_param_set_n_constants (struct ArgsGPTree *args, const int a)
void tree_param_set_init_depth (struct ArgsGPTree *args, const int a)
void tree_param_set_max_len (struct ArgsGPTree *args, const int a)
Variables
static const int MU_TYPE [(1)] = { (1) }
Self-adaptation method for mutating GP trees.
Detailed Description
An implementation of GP trees based upon TinyGP.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2021.
See also
Poli, Langdon, and McPhee (2008) "A Field Guide to Genetic Programming"
Definition in file gp.c.
Macro Definition Documentation
ADD
#define ADD (0)
Addition function.
Definition at line 30 of file gp.c.
DIV
#define DIV (3)
Division function.
Definition at line 33 of file gp.c.
GP_NUM_FUNC
#define GP_NUM_FUNC (4)
Number of selectable GP functions.
Definition at line 29 of file gp.c.
MUL
#define MUL (2)
Multiplication function.
Definition at line 32 of file gp.c.
N_MU
#define N_MU (1)
Number of tree-GP mutation rates.
Definition at line 40 of file gp.c.
RET_MAX
#define RET_MAX (1000)
Maximum tree return value.
Definition at line 42 of file gp.c.
RET_MIN
#define RET_MIN (-1000)
Minimum tree return value.
Definition at line 41 of file gp.c.
STRING_ADD
#define STRING_ADD ("+\0")
Addition.
Definition at line 35 of file gp.c.
STRING_DIV
#define STRING_DIV ("/\0")
Division.
Definition at line 38 of file gp.c.
STRING_MUL
#define STRING_MUL ("*\0")
Multiplication.
Definition at line 37 of file gp.c.
STRING_SUB
#define STRING_SUB ("-\0")
Subtraction.
Definition at line 36 of file gp.c.
SUB
#define SUB (1)
Subtraction function.
Definition at line 31 of file gp.c.
Function Documentation
tree_args_free()
void tree_args_free (struct ArgsGPTree * args)
Frees memory used by GP tree parameters.
Parameters
[in] args Parameters for initialising and operating GP trees.
Definition at line 437 of file gp.c.
References ArgsGPTree::constants.
Referenced by cond_param_free().
tree_args_init()
void tree_args_init (struct ArgsGPTree * args)
Sets tree GP parameters to default values.
Parameters
[in] args Parameters for initialising and operating GP trees.
Definition at line 421 of file gp.c.
References ArgsGPTree::constants, ArgsGPTree::init_depth, ArgsGPTree::max, ArgsGPTree::max_len, ArgsGPTree::min, ArgsGPTree::n_constants, and ArgsGPTree::n_inputs.
Referenced by cond_gp_param_defaults().
tree_args_init_constants()
void tree_args_init_constants (struct ArgsGPTree * args)
Builds global constants used by GP trees.
Parameters
[in] args Parameters for initialising and operating GP trees.
Definition at line 537 of file gp.c.
References ArgsGPTree::constants, ArgsGPTree::max, ArgsGPTree::min, ArgsGPTree::n_constants, and rand_uniform().
Referenced by cond_gp_param_defaults(), and cond_gp_param_json_import().
tree_args_json_export()
char* tree_args_json_export (const struct ArgsGPTree * args)
Returns a json formatted string of the GP tree parameters.
Parameters
[in] args Parameters for initialising and operating GP trees.
Returns
String encoded in json format.
Definition at line 448 of file gp.c.
References ArgsGPTree::init_depth, ArgsGPTree::max, ArgsGPTree::max_len, ArgsGPTree::min, and ArgsGPTree::n_constants.
Referenced by cond_gp_param_json_export().
tree_args_json_import()
void tree_args_json_import (struct ArgsGPTree * args, cJSON * json)
Sets the GP tree parameters from a cJSON object.
Parameters
[in,out] args GP tree parameter data structure.
[in] json cJSON object.
Definition at line 467 of file gp.c.
References tree_param_set_init_depth(), tree_param_set_max(), tree_param_set_max_len(), tree_param_set_min(), and tree_param_set_n_constants().
Referenced by cond_gp_param_json_import().
tree_args_load()
size_t tree_args_load (struct ArgsGPTree * args, FILE * fp)
Loads Tree GP parameters.
Parameters
[in] args Parameters for initialising and operating GP trees.
[in] fp Pointer to the output file.
Returns
The total number of elements read.
Definition at line 519 of file gp.c.
References ArgsGPTree::constants, ArgsGPTree::init_depth, ArgsGPTree::max, ArgsGPTree::max_len, ArgsGPTree::min, ArgsGPTree::n_constants, and ArgsGPTree::n_inputs.
Referenced by cond_param_load().
tree_args_save()
size_t tree_args_save (const struct ArgsGPTree * args, FILE * fp)
Saves Tree GP parameters.
Parameters
[in] args Parameters for initialising and operating GP trees.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 499 of file gp.c.
References ArgsGPTree::constants, ArgsGPTree::init_depth, ArgsGPTree::max, ArgsGPTree::max_len, ArgsGPTree::min, ArgsGPTree::n_constants, and ArgsGPTree::n_inputs.
Referenced by cond_param_save().
tree_copy()
void tree_copy (struct GPTree * dest, const struct GPTree * src)
Copies a GP tree.
Parameters
[in] dest The destination GP tree.
[in] src The source GP tree.
Definition at line 302 of file gp.c.
References GPTree::len, GPTree::mu, N_MU, GPTree::pos, and GPTree::tree.
Referenced by cond_gp_copy().
tree_crossover()
void tree_crossover (struct GPTree * p1, struct GPTree * p2)
Performs sub-tree crossover.
Parameters
[in] p1 The first GP tree to perform crossover.
[in] p2 The second GP tree to perform crossover.
Definition at line 318 of file gp.c.
References GPTree::len, rand_uniform_int(), GPTree::tree, and tree_traverse().
Referenced by cond_gp_crossover().
tree_eval()
double tree_eval (struct GPTree * gp, const struct ArgsGPTree * args, const double * x)
Evaluates a GP tree.
Parameters
[in] gp The GP tree to evaluate.
[in] args Tree GP parameters.
[in] x The input state.
Returns
The result from evaluating the GP tree.
Definition at line 133 of file gp.c.
References ADD, clamp(), ArgsGPTree::constants, DIV, GP_NUM_FUNC, MUL, ArgsGPTree::n_constants, GPTree::pos, RET_MAX, RET_MIN, SUB, and GPTree::tree.
Referenced by cond_gp_match().
tree_free()
void tree_free (const struct GPTree * gp)
Frees a GP tree.
Parameters
[in] gp The GP tree to free.
Definition at line 119 of file gp.c.
References GPTree::mu, and GPTree::tree.
Referenced by cond_gp_cover(), and cond_gp_free().
tree_function_int()
static int tree_function_int (const char * node) static
Returns an integer representation of a node function.
Parameters
[in] node String representing a function.
Returns
Integer representing a function.
Definition at line 189 of file gp.c.
References ADD, DIV, MUL, STRING_ADD, STRING_DIV, STRING_MUL, STRING_SUB, and SUB.
tree_function_string()
static const char* tree_function_string (const int node) static
Returns a string representation of a node function.
Parameters
[in] node Integer representing a function.
Returns
String representing a function.
Definition at line 166 of file gp.c.
References ADD, DIV, MUL, STRING_ADD, STRING_DIV, STRING_MUL, STRING_SUB, and SUB.
Referenced by tree_string().
tree_grow()
static int tree_grow (const struct ArgsGPTree * args, int * tree, const int pos, const int max, const int depth) static
Grows a random GP tree of specified max length and depth.
Only used to create an initial tree.
Parameters
[in] args Tree GP parameters.
[in,out] tree Vector holding the flattened GP tree generated.
[in] pos The position from which to traverse (start at 0).
[in] max Maximum tree length.
[in] depth Maximum tree depth.
Returns
The position after traversal (i.e., tree length).
Definition at line 77 of file gp.c.
References GP_NUM_FUNC, ArgsGPTree::n_constants, ArgsGPTree::n_inputs, rand_uniform(), and rand_uniform_int().
Referenced by tree_rand().
tree_json_export()
char* tree_json_export (const struct GPTree * gp, const struct ArgsGPTree * args)
Returns a json formatted string representation of a GP tree.
Parameters
[in] gp The GP tree to return.
[in] args Tree GP parameters.
Returns
String encoded in json format.
Definition at line 253 of file gp.c.
References GPTree::mu, N_MU, and tree_string().
Referenced by cond_gp_json_export(), and tree_print().
tree_json_import()
void tree_json_import (struct GPTree * gp, const struct ArgsGPTree * args, const cJSON * json)
Creates a GP tree from a cJSON object.
Parameters
[in,out] gp The GP tree to initialise.
[in] args Parameters for initialising a GP tree.
[in] json cJSON object.
Definition at line 273 of file gp.c.
Referenced by cond_gp_json_import().
tree_load()
size_t tree_load (struct GPTree * gp, FILE * fp)
Reads a GP tree from a file.
Parameters
[in] gp The GP tree to load.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 400 of file gp.c.
References GPTree::len, GPTree::mu, N_MU, GPTree::pos, and GPTree::tree.
Referenced by cond_gp_load().
tree_mutate()
bool tree_mutate (struct GPTree * gp, const struct ArgsGPTree * args)
Performs point mutation on a GP tree.
Terminals are randomly replaced with other terminals and functions are randomly replaced with other functions.
Parameters
[in] gp The GP tree to be mutated.
[in] args Tree GP parameters.
Returns
Whether any alterations were made.
Definition at line 355 of file gp.c.
References GP_NUM_FUNC, GPTree::len, GPTree::mu, MU_TYPE, ArgsGPTree::n_constants, ArgsGPTree::n_inputs, N_MU, rand_uniform(), rand_uniform_int(), sam_adapt(), and GPTree::tree.
Referenced by cond_gp_mutate().
tree_param_set_init_depth()
void tree_param_set_init_depth (struct ArgsGPTree * args, const int a)
Definition at line 585 of file gp.c.
References ArgsGPTree::init_depth.
Referenced by cond_gp_param_defaults(), and tree_args_json_import().
tree_param_set_max()
void tree_param_set_max (struct ArgsGPTree * args, const double a)
Definition at line 551 of file gp.c.
References ArgsGPTree::max.
Referenced by cond_gp_param_defaults(), and tree_args_json_import().
tree_param_set_max_len()
void tree_param_set_max_len (struct ArgsGPTree * args, const int a)
Definition at line 596 of file gp.c.
References ArgsGPTree::max_len.
Referenced by cond_gp_param_defaults(), and tree_args_json_import().
tree_param_set_min()
void tree_param_set_min (struct ArgsGPTree * args, const double a)
Definition at line 557 of file gp.c.
References ArgsGPTree::min.
Referenced by cond_gp_param_defaults(), and tree_args_json_import().
tree_param_set_n_constants()
void tree_param_set_n_constants (struct ArgsGPTree * args, const int a)
Definition at line 574 of file gp.c.
References ArgsGPTree::n_constants.
Referenced by cond_gp_param_defaults(), and tree_args_json_import().
tree_param_set_n_inputs()
void tree_param_set_n_inputs (struct ArgsGPTree * args, const int a)
Definition at line 563 of file gp.c.
References ArgsGPTree::n_inputs.
Referenced by cond_gp_param_defaults().
tree_print()
void tree_print (const struct GPTree * gp, const struct ArgsGPTree * args)
Prints a GP tree.
Parameters
[in] gp The GP tree to print.
[in] args Tree GP parameters.
Definition at line 289 of file gp.c.
References tree_json_export().
tree_rand()
void tree_rand (struct GPTree * gp, const struct ArgsGPTree * args)
Creates a random GP tree.
Parameters
[in] gp The GP tree being randomised.
[in] args Tree GP parameters.
Definition at line 102 of file gp.c.
References ArgsGPTree::init_depth, GPTree::len, ArgsGPTree::max_len, GPTree::mu, MU_TYPE, N_MU, sam_init(), GPTree::tree, and tree_grow().
Referenced by cond_gp_cover(), and cond_gp_init().
tree_save()
size_t tree_save (const struct GPTree * gp, FILE * fp)
Writes the GP tree to a file.
Parameters
[in] gp The GP tree to save.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 383 of file gp.c.
References GPTree::len, GPTree::mu, N_MU, GPTree::pos, and GPTree::tree.
Referenced by cond_gp_save().
tree_string()
static int tree_string (const struct GPTree * gp, const struct ArgsGPTree * args, int pos, cJSON * json) static
Returns a json formatted string representation of a GP tree.
Parameters
[in] gp The GP tree to print.
[in] args Tree GP parameters.
[in] pos The position from which to traverse (start at 0).
[in] json cJSON object.
Returns
The position after traversal.
Definition at line 215 of file gp.c.
References ArgsGPTree::constants, GP_NUM_FUNC, ArgsGPTree::n_constants, GPTree::tree, and tree_function_string().
Referenced by tree_json_export().
tree_traverse()
static int tree_traverse (int * tree, int pos) static
Traverses a GP tree.
Parameters
[in] tree The tree to traverse.
[in] pos The position from which to traverse.
Returns
The position after traversal.
Definition at line 56 of file gp.c.
References GP_NUM_FUNC.
Referenced by tree_crossover().
Variable Documentation
MU_TYPE
const int MU_TYPE[(1)] = { (1) } static
Self-adaptation method for mutating GP trees.
Definition at line 47 of file gp.c.
Referenced by tree_mutate(), and tree_rand().