var hierarchy =
[
    [ "ActInteger", "structActInteger.html", null ],
    [ "ActNeural", "structActNeural.html", null ],
    [ "ActVtbl", "structActVtbl.html", null ],
    [ "ArgsAct", "structArgsAct.html", null ],
    [ "ArgsCond", "structArgsCond.html", null ],
    [ "ArgsDGP", "structArgsDGP.html", null ],
    [ "ArgsEA", "structArgsEA.html", null ],
    [ "ArgsGPTree", "structArgsGPTree.html", null ],
    [ "ArgsLayer", "structArgsLayer.html", null ],
    [ "ArgsPred", "structArgsPred.html", null ],
    [ "Callback", "classCallback.html", [
      [ "CheckpointCallback", "classCheckpointCallback.html", null ],
      [ "EarlyStoppingCallback", "classEarlyStoppingCallback.html", null ]
    ] ],
    [ "Cl", "structCl.html", null ],
    [ "Clist", "structClist.html", null ],
    [ "CondDGP", "structCondDGP.html", null ],
    [ "CondEllipsoid", "structCondEllipsoid.html", null ],
    [ "CondGP", "structCondGP.html", null ],
    [ "CondNeural", "structCondNeural.html", null ],
    [ "CondRectangle", "structCondRectangle.html", null ],
    [ "CondTernary", "structCondTernary.html", null ],
    [ "CondVtbl", "structCondVtbl.html", null ],
    [ "xcsf.utils.viz.DGPViz", "classxcsf_1_1utils_1_1viz_1_1DGPViz.html", null ],
    [ "EnvCSV", "structEnvCSV.html", null ],
    [ "EnvMaze", "structEnvMaze.html", null ],
    [ "EnvMux", "structEnvMux.html", null ],
    [ "EnvVtbl", "structEnvVtbl.html", null ],
    [ "GPTree", "structGPTree.html", null ],
    [ "Graph", "structGraph.html", null ],
    [ "Input", "structInput.html", null ],
    [ "Layer", "structLayer.html", null ],
    [ "LayerVtbl", "structLayerVtbl.html", null ],
    [ "Llist", "structLlist.html", null ],
    [ "Net", "structNet.html", null ],
    [ "PredNeural", "structPredNeural.html", null ],
    [ "PredNLMS", "structPredNLMS.html", null ],
    [ "PredRLS", "structPredRLS.html", null ],
    [ "PredVtbl", "structPredVtbl.html", null ],
    [ "RuleDGP", "structRuleDGP.html", null ],
    [ "RuleNeural", "structRuleNeural.html", null ],
    [ "Set", "structSet.html", null ],
    [ "xcsf.utils.viz.TreeViz", "classxcsf_1_1utils_1_1viz_1_1TreeViz.html", null ],
    [ "XCS", "classXCS.html", null ],
    [ "XCSF", "structXCSF.html", null ]
];