XCSF: image.c File Reference
image.c File Reference
Image handling functions.
Functions
static void col2im_add_pixel (double *im, const int height, const int width, int row, int col, const int channel, const int pad, const double val)
static double im2col_get_pixel (const double *im, const int height, const int width, int row, int col, const int channel, const int pad)
void col2im (const double *data_col, const int channels, const int height, const int width, const int ksize, const int stride, const int pad, double *data_im)
Transforms a column vector to an image vector.
void im2col (const double *data_im, const int channels, const int height, const int width, const int ksize, const int stride, const int pad, double *data_col)
Transforms an image vector to a column vector.
Detailed Description
Image handling functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2020.
Definition in file image.c.
Function Documentation
col2im()
void col2im (const double * data_col, const int channels, const int height, const int width, const int ksize, const int stride, const int pad, double * data_im)
Transforms a column vector to an image vector.
Used for GEMM convolutional backward propagation.
Parameters
[in] data_col Input column vector.
[in] channels Number of image channels.
[in] height Image height.
[in] width Image width.
[in] ksize Kernel size.
[in] stride Kernel stride.
[in] pad Kernel padding.
[out] data_im The resulting image vector.
Definition at line 61 of file image.c.
References col2im_add_pixel().
Referenced by neural_layer_convolutional_backward().
col2im_add_pixel()
static void col2im_add_pixel (double * im, const int height, const int width, int row, int col, const int channel, const int pad, const double val) static
Definition at line 25 of file image.c.
Referenced by col2im().
im2col()
void im2col (const double * data_im, const int channels, const int height, const int width, const int ksize, const int stride, const int pad, double * data_col)
Transforms an image vector to a column vector.
Used for GEMM convolutional forward propagation.
Parameters
[in] data_im Image vector of dimension: height × width × channels.
[in] channels Number of image channels.
[in] height Image height.
[in] width Image width.
[in] ksize Kernel size.
[in] stride Kernel stride.
[in] pad Kernel padding.
[out] data_col The resulting column vector.
Definition at line 98 of file image.c.
References im2col_get_pixel().
Referenced by neural_layer_convolutional_backward(), and neural_layer_convolutional_forward().
im2col_get_pixel()
static double im2col_get_pixel (const double * im, const int height, const int width, int row, int col, const int channel, const int pad) static
Definition at line 37 of file image.c.
Referenced by im2col().