XCSF: loss.h File Reference
loss.h File Reference
Loss functions for calculating prediction error.
#include "xcsf.h"
Macros
#define LOSS_MAE (0)
Mean absolute error.
#define LOSS_MSE (1)
Mean squared error.
#define LOSS_RMSE (2)
Root mean squared error.
#define LOSS_LOG (3)
Log loss.
#define LOSS_BINARY_LOG (4)
Binary log loss.
#define LOSS_ONEHOT (5)
One-hot encoding classification error.
#define LOSS_HUBER (6)
Huber loss.
#define LOSS_NUM (7)
Total number of selectable loss functions.
#define LOSS_STRING_MAE ("mae\0")
Mean absolute error.
#define LOSS_STRING_MSE ("mse\0")
Mean squared error.
#define LOSS_STRING_RMSE ("rmse\0")
Root mean squared error.
#define LOSS_STRING_LOG ("log\0")
Log loss.
#define LOSS_STRING_BINARY_LOG ("binary_log\0")
Binary log loss.
#define LOSS_STRING_ONEHOT ("onehot\0")
One-hot classification error.
#define LOSS_STRING_HUBER ("huber\0")
Huber loss.
Functions
double loss_huber (const struct XCSF *xcsf, const double *pred, const double *y)
Huber loss function.
double loss_mae (const struct XCSF *xcsf, const double *pred, const double *y)
Mean absolute error loss function.
double loss_mse (const struct XCSF *xcsf, const double *pred, const double *y)
Mean squared error loss function.
double loss_rmse (const struct XCSF *xcsf, const double *pred, const double *y)
Root mean squared error loss function.
double loss_log (const struct XCSF *xcsf, const double *pred, const double *y)
Logistic log loss for multi-class classification.
double loss_binary_log (const struct XCSF *xcsf, const double *pred, const double *y)
Binary logistic log loss for binary-class classification.
double loss_onehot (const struct XCSF *xcsf, const double *pred, const double *y)
One-hot classification error.
void loss_set_func (struct XCSF *xcsf)
Sets the XCSF error function to the implemented function.
const char * loss_type_as_string (const int type)
Returns a string representation of a loss type from the integer.
int loss_type_as_int (const char *type)
Returns the integer representation of a loss type given a name.
Detailed Description
Loss functions for calculating prediction error.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file loss.h.
Macro Definition Documentation
LOSS_BINARY_LOG
#define LOSS_BINARY_LOG (4)
Binary log loss.
Definition at line 32 of file loss.h.
LOSS_HUBER
#define LOSS_HUBER (6)
Huber loss.
Definition at line 34 of file loss.h.
LOSS_LOG
#define LOSS_LOG (3)
Log loss.
Definition at line 31 of file loss.h.
LOSS_MAE
#define LOSS_MAE (0)
Mean absolute error.
Definition at line 28 of file loss.h.
LOSS_MSE
#define LOSS_MSE (1)
Mean squared error.
Definition at line 29 of file loss.h.
LOSS_NUM
#define LOSS_NUM (7)
Total number of selectable loss functions.
Definition at line 35 of file loss.h.
LOSS_ONEHOT
#define LOSS_ONEHOT (5)
One-hot encoding classification error.
Definition at line 33 of file loss.h.
LOSS_RMSE
#define LOSS_RMSE (2)
Root mean squared error.
Definition at line 30 of file loss.h.
LOSS_STRING_BINARY_LOG
#define LOSS_STRING_BINARY_LOG ("binary_log\0")
Binary log loss.
Definition at line 41 of file loss.h.
LOSS_STRING_HUBER
#define LOSS_STRING_HUBER ("huber\0")
Huber loss.
Definition at line 43 of file loss.h.
LOSS_STRING_LOG
#define LOSS_STRING_LOG ("log\0")
Log loss.
Definition at line 40 of file loss.h.
LOSS_STRING_MAE
#define LOSS_STRING_MAE ("mae\0")
Mean absolute error.
Definition at line 37 of file loss.h.
LOSS_STRING_MSE
#define LOSS_STRING_MSE ("mse\0")
Mean squared error.
Definition at line 38 of file loss.h.
LOSS_STRING_ONEHOT
#define LOSS_STRING_ONEHOT ("onehot\0")
One-hot classification error.
Definition at line 42 of file loss.h.
LOSS_STRING_RMSE
#define LOSS_STRING_RMSE ("rmse\0")
Root mean squared error.
Definition at line 39 of file loss.h.
Function Documentation
loss_binary_log()
double loss_binary_log (const struct XCSF * xcsf, const double * pred, const double * y)
Binary logistic log loss for binary-class classification.
Parameters
[in] xcsf The XCSF data structure.
[in] pred The predicted values.
[in] y The true values.
Returns
The log error.
Definition at line 102 of file loss.c.
Referenced by loss_set_func().
loss_huber()
double loss_huber (const struct XCSF * xcsf, const double * pred, const double * y)
Huber loss function.
Parameters
[in] xcsf The XCSF data structure.
[in] pred The predicted values.
[in] y The true values.
Returns
The Huber loss.
Definition at line 137 of file loss.c.
Referenced by loss_set_func().
loss_log()
double loss_log (const struct XCSF * xcsf, const double * pred, const double * y)
Logistic log loss for multi-class classification.
Precondition
The sum of predictions = 1 and a single target y_i has a value of 1.
Parameters
[in] xcsf The XCSF data structure.
[in] pred The predicted values.
[in] y The true values.
Returns
The log error.
Definition at line 85 of file loss.c.
Referenced by loss_set_func().
loss_mae()
double loss_mae (const struct XCSF * xcsf, const double * pred, const double * y)
Mean absolute error loss function.
Parameters
[in] xcsf The XCSF data structure.
[in] pred The predicted values.
[in] y The true values.
Returns
The mean absolute error.
Definition at line 35 of file loss.c.
Referenced by loss_set_func().
loss_mse()
double loss_mse (const struct XCSF * xcsf, const double * pred, const double * y)
Mean squared error loss function.
Parameters
[in] xcsf The XCSF data structure.
[in] pred The predicted values.
[in] y The true values.
Returns
The mean squared error.
Definition at line 53 of file loss.c.
Referenced by loss_rmse(), and loss_set_func().
loss_onehot()
double loss_onehot (const struct XCSF * xcsf, const double * pred, const double * y)
One-hot classification error.
Parameters
[in] xcsf The XCSF data structure.
[in] pred The predicted values.
[in] y The true values.
Returns
The one-hot classification error.
Definition at line 120 of file loss.c.
References max_index().
Referenced by loss_set_func().
loss_rmse()
double loss_rmse (const struct XCSF * xcsf, const double * pred, const double * y)
Root mean squared error loss function.
Parameters
[in] xcsf The XCSF data structure.
[in] pred The predicted values.
[in] y The true values.
Returns
The root mean squared error.
Definition at line 71 of file loss.c.
References loss_mse().
Referenced by loss_set_func().
loss_set_func()
void loss_set_func (struct XCSF * xcsf)
Sets the XCSF error function to the implemented function.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 158 of file loss.c.
References LOSS_BINARY_LOG, loss_binary_log(), LOSS_HUBER, loss_huber(), LOSS_LOG, loss_log(), LOSS_MAE, loss_mae(), LOSS_MSE, loss_mse(), LOSS_ONEHOT, loss_onehot(), LOSS_RMSE, and loss_rmse().
Referenced by param_load(), param_set_loss_func(), and param_set_loss_func_string().
loss_type_as_int()
int loss_type_as_int (const char * type)
Returns the integer representation of a loss type given a name.
Parameters
[in] type String representation of a loss function type.
Returns
Integer representing the loss function type.
Definition at line 223 of file loss.c.
References LOSS_BINARY_LOG, LOSS_HUBER, LOSS_LOG, LOSS_MAE, LOSS_MSE, LOSS_ONEHOT, LOSS_RMSE, LOSS_STRING_BINARY_LOG, LOSS_STRING_HUBER, LOSS_STRING_LOG, LOSS_STRING_MAE, LOSS_STRING_MSE, LOSS_STRING_ONEHOT, and LOSS_STRING_RMSE.
Referenced by param_set_loss_func_string().
loss_type_as_string()
const char* loss_type_as_string (const int type)
Returns a string representation of a loss type from the integer.
Parameters
[in] type Integer representation of a loss function type.
Returns
String representing the name of the loss function type.
Definition at line 194 of file loss.c.
References LOSS_BINARY_LOG, LOSS_HUBER, LOSS_LOG, LOSS_MAE, LOSS_MSE, LOSS_ONEHOT, LOSS_RMSE, LOSS_STRING_BINARY_LOG, LOSS_STRING_HUBER, LOSS_STRING_LOG, LOSS_STRING_MAE, LOSS_STRING_MSE, LOSS_STRING_ONEHOT, and LOSS_STRING_RMSE.
Referenced by XCS::get_loss_func(), and param_json_export().