XCSF: neural_layer_connected.h File Reference
neural_layer_connected.h File Reference
An implementation of a fully-connected layer of perceptrons.
#include "neural_layer.h"
Functions
void neural_layer_connected_init (struct Layer *l, const struct ArgsLayer *args)
Initialises a fully-connected layer.
struct Layer * neural_layer_connected_copy (const struct Layer *src)
Initialises and creates a copy of one connected layer from another.
void neural_layer_connected_rand (struct Layer *l)
Randomises a connected layer weights.
void neural_layer_connected_forward (const struct Layer *l, const struct Net *net, const double *input)
Forward propagates a connected layer.
void neural_layer_connected_backward (const struct Layer *l, const struct Net *net, const double *input, double *delta)
Backward propagates a connected layer.
void neural_layer_connected_update (const struct Layer *l)
Updates the weights and biases of a connected layer.
void neural_layer_connected_print (const struct Layer *l, const bool print_weights)
Prints a connected layer.
bool neural_layer_connected_mutate (struct Layer *l)
Mutates a connected layer.
void neural_layer_connected_free (const struct Layer *l)
Free memory used by a connected layer.
double * neural_layer_connected_output (const struct Layer *l)
Returns the output from a connected layer.
size_t neural_layer_connected_save (const struct Layer *l, FILE *fp)
Writes a connected layer to a file.
size_t neural_layer_connected_load (struct Layer *l, FILE *fp)
Reads a connected layer from a file.
void neural_layer_connected_resize (struct Layer *l, const struct Layer *prev)
Resizes a connected layer if the previous layer has changed size.
char * neural_layer_connected_json_export (const struct Layer *l, const bool return_weights)
Returns a json formatted string representation of a connected layer.
Variables
static struct LayerVtbl const layer_connected_vtbl
Neural connected layer implemented functions.
Detailed Description
An implementation of a fully-connected layer of perceptrons.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2021.
Definition in file neural_layer_connected.h.
Function Documentation
neural_layer_connected_backward()
void neural_layer_connected_backward (const struct Layer * l, const struct Net * net, const double * input, double * delta)
Backward propagates a connected layer.
Parameters
[in] l The layer to backward propagate.
[in] net Network containing the layer.
[in] input The input to the layer.
[out] delta The previous layer's error.
Definition at line 196 of file neural_layer_connected.c.
References Layer::bias_updates, blas_axpy(), blas_gemm(), Layer::c, Layer::delta, Layer::function, LAYER_SGD_WEIGHTS, Layer::n_inputs, Layer::n_outputs, neural_gradient_array(), Layer::options, Layer::state, Layer::weight_updates, and Layer::weights.
neural_layer_connected_copy()
struct Layer* neural_layer_connected_copy (const struct Layer * src)
Initialises and creates a copy of one connected layer from another.
Parameters
[in] src The source layer.
Returns
A pointer to the new layer.
Definition at line 122 of file neural_layer_connected.c.
References Layer::biases, CONNECTED, Layer::decay, Layer::eta, Layer::eta_max, Layer::eta_min, Layer::function, layer_defaults(), Layer::layer_vptr, malloc_layer_arrays(), Layer::max_neuron_grow, Layer::max_outputs, Layer::momentum, Layer::mu, Layer::n_active, Layer::n_biases, Layer::n_inputs, N_MU, Layer::n_outputs, Layer::n_weights, Layer::options, Layer::out_c, Layer::out_h, Layer::out_w, Layer::type, Layer::weight_active, and Layer::weights.
neural_layer_connected_forward()
void neural_layer_connected_forward (const struct Layer * l, const struct Net * net, const double * input)
Forward propagates a connected layer.
Parameters
[in] l Layer to forward propagate.
[in] net Network containing the layer.
[in] input Input to the layer.
Definition at line 174 of file neural_layer_connected.c.
References Layer::biases, blas_gemm(), Layer::c, Layer::function, Layer::n_inputs, Layer::n_outputs, neural_activate_array(), Layer::output, Layer::state, and Layer::weights.
neural_layer_connected_free()
void neural_layer_connected_free (const struct Layer * l)
Free memory used by a connected layer.
Parameters
[in] l The layer to be freed.
Definition at line 103 of file neural_layer_connected.c.
References Layer::bias_updates, Layer::biases, Layer::delta, Layer::mu, Layer::output, Layer::state, Layer::weight_active, Layer::weight_updates, and Layer::weights.
neural_layer_connected_init()
void neural_layer_connected_init (struct Layer * l, const struct ArgsLayer * args)
Initialises a fully-connected layer.
Parameters
[in] l Layer to initialise.
[in] args Parameters to initialise the layer.
Definition at line 70 of file neural_layer_connected.c.
References Layer::biases, ArgsLayer::decay, Layer::decay, ArgsLayer::eta, Layer::eta_max, ArgsLayer::eta_min, Layer::eta_min, ArgsLayer::function, Layer::function, layer_args_opt(), layer_init_eta(), malloc_layer_arrays(), ArgsLayer::max_neuron_grow, Layer::max_neuron_grow, Layer::max_outputs, ArgsLayer::momentum, Layer::momentum, Layer::mu, MU_TYPE, Layer::n_active, Layer::n_biases, ArgsLayer::n_init, ArgsLayer::n_inputs, Layer::n_inputs, ArgsLayer::n_max, N_MU, Layer::n_outputs, Layer::n_weights, Layer::options, Layer::out_c, Layer::out_h, Layer::out_w, rand_normal(), sam_init(), Layer::weight_active, WEIGHT_SD_INIT, and Layer::weights.
neural_layer_connected_json_export()
char* neural_layer_connected_json_export (const struct Layer * l, const bool return_weights)
Returns a json formatted string representation of a connected layer.
Parameters
[in] l The layer to return.
[in] return_weights Whether to returnprint the values of weights and biases.
Returns
String encoded in json format.
Definition at line 354 of file neural_layer_connected.c.
References Layer::eta, Layer::function, layer_weight_json(), Layer::mu, Layer::n_inputs, N_MU, Layer::n_outputs, neural_activation_string(), and Layer::weights.
Referenced by neural_layer_connected_print().
neural_layer_connected_load()
size_t neural_layer_connected_load (struct Layer * l, FILE * fp)
Reads a connected layer from a file.
Parameters
[in] l The layer to load.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 413 of file neural_layer_connected.c.
References Layer::bias_updates, Layer::biases, Layer::decay, Layer::eta, Layer::eta_max, Layer::eta_min, Layer::function, malloc_layer_arrays(), Layer::max_neuron_grow, Layer::max_outputs, Layer::momentum, Layer::mu, Layer::n_active, Layer::n_biases, Layer::n_inputs, N_MU, Layer::n_outputs, Layer::n_weights, Layer::options, Layer::out_c, Layer::out_h, Layer::out_w, Layer::weight_active, Layer::weight_updates, and Layer::weights.
neural_layer_connected_mutate()
bool neural_layer_connected_mutate (struct Layer * l)
Mutates a connected layer.
Parameters
[in] l The layer to mutate.
Returns
Whether any alterations were made.
Definition at line 292 of file neural_layer_connected.c.
References layer_add_neurons(), layer_ensure_input_represention(), LAYER_EVOLVE_CONNECT, LAYER_EVOLVE_ETA, LAYER_EVOLVE_FUNCTIONS, LAYER_EVOLVE_NEURONS, LAYER_EVOLVE_WEIGHTS, layer_mutate_connectivity(), layer_mutate_eta(), layer_mutate_functions(), layer_mutate_neurons(), layer_mutate_weights(), Layer::mu, MU_TYPE, N_MU, Layer::options, and sam_adapt().
neural_layer_connected_output()
double* neural_layer_connected_output (const struct Layer * l)
Returns the output from a connected layer.
Parameters
[in] l The layer whose output to return.
Returns
The layer output.
Definition at line 328 of file neural_layer_connected.c.
References Layer::output.
neural_layer_connected_print()
void neural_layer_connected_print (const struct Layer * l, const bool print_weights)
Prints a connected layer.
Parameters
[in] l The layer to print.
[in] print_weights Whether to print the values of weights and biases.
Definition at line 339 of file neural_layer_connected.c.
References neural_layer_connected_json_export().
neural_layer_connected_rand()
void neural_layer_connected_rand (struct Layer * l)
Randomises a connected layer weights.
Parameters
[in] l The layer to randomise.
Definition at line 162 of file neural_layer_connected.c.
References layer_weight_rand().
neural_layer_connected_resize()
void neural_layer_connected_resize (struct Layer * l, const struct Layer * prev)
Resizes a connected layer if the previous layer has changed size.
Parameters
[in] l The layer to resize.
[in] prev The layer previous to the one being resized.
Definition at line 246 of file neural_layer_connected.c.
References Layer::i, layer_calc_n_active(), layer_ensure_input_represention(), LAYER_EVOLVE_CONNECT, layer_print(), Layer::n_inputs, Layer::n_outputs, Layer::n_weights, N_WEIGHTS_MAX, Layer::options, rand_normal(), Layer::weight_active, WEIGHT_SD, Layer::weight_updates, and Layer::weights.
neural_layer_connected_save()
size_t neural_layer_connected_save (const struct Layer * l, FILE * fp)
Writes a connected layer to a file.
Parameters
[in] l The layer to save.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 380 of file neural_layer_connected.c.
References Layer::bias_updates, Layer::biases, Layer::decay, Layer::eta, Layer::eta_max, Layer::eta_min, Layer::function, Layer::max_neuron_grow, Layer::max_outputs, Layer::momentum, Layer::mu, Layer::n_active, Layer::n_biases, Layer::n_inputs, N_MU, Layer::n_outputs, Layer::n_weights, Layer::options, Layer::weight_active, Layer::weight_updates, and Layer::weights.
neural_layer_connected_update()
void neural_layer_connected_update (const struct Layer * l)
Updates the weights and biases of a connected layer.
Parameters
[in] l The layer to update.
Definition at line 225 of file neural_layer_connected.c.
References Layer::bias_updates, Layer::biases, blas_axpy(), blas_scal(), Layer::decay, Layer::eta, LAYER_SGD_WEIGHTS, layer_weight_clamp(), Layer::momentum, Layer::n_biases, Layer::n_weights, Layer::options, Layer::weight_updates, and Layer::weights.
Variable Documentation
layer_connected_vtbl
struct LayerVtbl const layer_connected_vtbl static
Initial value:
= {
    &neural_layer_connected_init,     &neural_layer_connected_mutate,
    &neural_layer_connected_resize,   &neural_layer_connected_copy,
    &neural_layer_connected_free,     &neural_layer_connected_rand,
    &neural_layer_connected_print,    &neural_layer_connected_update,
    &neural_layer_connected_backward, &neural_layer_connected_forward,
    &neural_layer_connected_output,   &neural_layer_connected_save,
    &neural_layer_connected_load,     &neural_layer_connected_json_export
}
Neural connected layer implemented functions.
Definition at line 76 of file neural_layer_connected.h.
Referenced by layer_set_vptr().