XCSF: neural_layer_maxpool.h File Reference
neural_layer_maxpool.h File Reference
An implementation of a 2D maxpooling layer.
#include "neural_layer.h"
Functions
void neural_layer_maxpool_init (struct Layer *l, const struct ArgsLayer *args)
Initialises a 2D maxpooling layer.
struct Layer * neural_layer_maxpool_copy (const struct Layer *src)
Initialises and creates a copy of one maxpooling layer from another.
void neural_layer_maxpool_rand (struct Layer *l)
Dummy function since maxpooling layers have no weights.
void neural_layer_maxpool_forward (const struct Layer *l, const struct Net *net, const double *input)
Forward propagates a maxpooling layer.
void neural_layer_maxpool_backward (const struct Layer *l, const struct Net *net, const double *input, double *delta)
Backward propagates a maxpooling layer.
void neural_layer_maxpool_update (const struct Layer *l)
Dummy function since a maxpooling layer has no weights.
void neural_layer_maxpool_print (const struct Layer *l, const bool print_weights)
Prints a maxpooling layer.
bool neural_layer_maxpool_mutate (struct Layer *l)
Dummy function since a maxpooling layer cannot be mutated.
void neural_layer_maxpool_free (const struct Layer *l)
Free memory used by a maxpooling layer.
double * neural_layer_maxpool_output (const struct Layer *l)
Returns the output from a maxpooling layer.
size_t neural_layer_maxpool_save (const struct Layer *l, FILE *fp)
Writes a maxpooling layer to a file.
size_t neural_layer_maxpool_load (struct Layer *l, FILE *fp)
Reads a maxpooling layer from a file.
void neural_layer_maxpool_resize (struct Layer *l, const struct Layer *prev)
Resizes a maxpooling layer if the previous layer has changed size.
char * neural_layer_maxpool_json_export (const struct Layer *l, const bool return_weights)
Returns a json formatted string representation of a maxpooling layer.
Variables
static struct LayerVtbl const layer_maxpool_vtbl
Neural maxpooling layer implemented functions.
Detailed Description
An implementation of a 2D maxpooling layer.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2021.
Definition in file neural_layer_maxpool.h.
Function Documentation
neural_layer_maxpool_backward()
void neural_layer_maxpool_backward (const struct Layer * l, const struct Net * net, const double * input, double * delta)
Backward propagates a maxpooling layer.
Parameters
[in] l The layer to backward propagate.
[in] net Network containing the layer.
[in] input The input to the layer.
[out] delta The previous layer's error.
Definition at line 203 of file neural_layer_maxpool.c.
References Layer::delta, Layer::i, Layer::indexes, and Layer::n_outputs.
neural_layer_maxpool_copy()
struct Layer* neural_layer_maxpool_copy (const struct Layer * src)
Initialises and creates a copy of one maxpooling layer from another.
Parameters
[in] src The source layer.
Returns
A pointer to the new layer.
Definition at line 84 of file neural_layer_maxpool.c.
References Layer::channels, Layer::height, layer_defaults(), Layer::layer_vptr, malloc_layer_arrays(), Layer::max_outputs, MAXPOOL, Layer::n_inputs, Layer::n_outputs, Layer::out_c, Layer::out_h, Layer::out_w, Layer::pad, Layer::size, Layer::stride, Layer::type, and Layer::width.
neural_layer_maxpool_forward()
void neural_layer_maxpool_forward (const struct Layer * l, const struct Net * net, const double * input)
Forward propagates a maxpooling layer.
Parameters
[in] l Layer to forward propagate.
[in] net Network containing the layer.
[in] input Input to the layer.
Definition at line 177 of file neural_layer_maxpool.c.
References Layer::channels, Layer::i, Layer::indexes, max_index(), max_pool(), Layer::n_outputs, Layer::out_h, Layer::out_w, and Layer::output.
neural_layer_maxpool_free()
void neural_layer_maxpool_free (const struct Layer * l)
Free memory used by a maxpooling layer.
Parameters
[in] l The layer to be freed.
Definition at line 115 of file neural_layer_maxpool.c.
References Layer::delta, Layer::indexes, and Layer::output.
neural_layer_maxpool_init()
void neural_layer_maxpool_init (struct Layer * l, const struct ArgsLayer * args)
Initialises a 2D maxpooling layer.
Parameters
[in] l Layer to initialise.
[in] args Parameters to initialise the layer.
Definition at line 61 of file neural_layer_maxpool.c.
References Layer::channels, ArgsLayer::channels, Layer::height, ArgsLayer::height, malloc_layer_arrays(), Layer::max_outputs, Layer::n_inputs, Layer::n_outputs, Layer::out_c, Layer::out_h, Layer::out_w, Layer::pad, ArgsLayer::pad, Layer::size, ArgsLayer::size, Layer::stride, ArgsLayer::stride, Layer::width, and ArgsLayer::width.
neural_layer_maxpool_json_export()
char* neural_layer_maxpool_json_export (const struct Layer * l, const bool return_weights)
Returns a json formatted string representation of a maxpooling layer.
Parameters
[in] l The layer to return.
[in] return_weights Whether to return the values of weights and biases.
Returns
String encoded in json format.
Definition at line 292 of file neural_layer_maxpool.c.
References Layer::channels, Layer::height, Layer::n_inputs, Layer::n_outputs, Layer::out_c, Layer::out_h, Layer::out_w, Layer::pad, Layer::size, Layer::stride, and Layer::width.
Referenced by neural_layer_maxpool_print().
neural_layer_maxpool_load()
size_t neural_layer_maxpool_load (struct Layer * l, FILE * fp)
Reads a maxpooling layer from a file.
Parameters
[in] l The layer to load.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 346 of file neural_layer_maxpool.c.
References Layer::channels, Layer::height, malloc_layer_arrays(), Layer::max_outputs, Layer::n_inputs, Layer::n_outputs, Layer::out_c, Layer::out_h, Layer::out_w, Layer::pad, Layer::size, Layer::stride, and Layer::width.
neural_layer_maxpool_mutate()
bool neural_layer_maxpool_mutate (struct Layer * l)
Dummy function since a maxpooling layer cannot be mutated.
Parameters
[in] l A maxpooling layer.
Returns
False.
Definition at line 231 of file neural_layer_maxpool.c.
neural_layer_maxpool_output()
double* neural_layer_maxpool_output (const struct Layer * l)
Returns the output from a maxpooling layer.
Parameters
[in] l The layer whose output to return.
Returns
The layer output.
Definition at line 266 of file neural_layer_maxpool.c.
References Layer::output.
neural_layer_maxpool_print()
void neural_layer_maxpool_print (const struct Layer * l, const bool print_weights)
Prints a maxpooling layer.
Parameters
[in] l The layer to print.
[in] print_weights Whether to print the values of weights and biases.
Definition at line 277 of file neural_layer_maxpool.c.
References neural_layer_maxpool_json_export().
neural_layer_maxpool_rand()
void neural_layer_maxpool_rand (struct Layer * l)
Dummy function since maxpooling layers have no weights.
Parameters
[in] l A maxpooling layer.
Definition at line 127 of file neural_layer_maxpool.c.
neural_layer_maxpool_resize()
void neural_layer_maxpool_resize (struct Layer * l, const struct Layer * prev)
Resizes a maxpooling layer if the previous layer has changed size.
Parameters
[in] l The layer to resize.
[in] prev The layer previous to the one being resized.
Definition at line 243 of file neural_layer_maxpool.c.
References Layer::c, Layer::channels, Layer::h, Layer::height, Layer::max_outputs, Layer::n_inputs, Layer::n_outputs, Layer::out_c, Layer::out_h, Layer::out_w, Layer::pad, realloc_layer_arrays(), Layer::size, Layer::stride, and Layer::width.
neural_layer_maxpool_save()
size_t neural_layer_maxpool_save (const struct Layer * l, FILE * fp)
Writes a maxpooling layer to a file.
Parameters
[in] l The layer to save.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 321 of file neural_layer_maxpool.c.
References Layer::channels, Layer::height, Layer::max_outputs, Layer::n_inputs, Layer::n_outputs, Layer::out_c, Layer::out_h, Layer::out_w, Layer::pad, Layer::size, Layer::stride, and Layer::width.
neural_layer_maxpool_update()
void neural_layer_maxpool_update (const struct Layer * l)
Dummy function since a maxpooling layer has no weights.
Parameters
[in] l A maxpooling layer.
Definition at line 220 of file neural_layer_maxpool.c.
Variable Documentation
layer_maxpool_vtbl
struct LayerVtbl const layer_maxpool_vtbl static
Initial value:
= {
    &neural_layer_maxpool_init,     &neural_layer_maxpool_mutate,
    &neural_layer_maxpool_resize,   &neural_layer_maxpool_copy,
    &neural_layer_maxpool_free,     &neural_layer_maxpool_rand,
    &neural_layer_maxpool_print,    &neural_layer_maxpool_update,
    &neural_layer_maxpool_backward, &neural_layer_maxpool_forward,
    &neural_layer_maxpool_output,   &neural_layer_maxpool_save,
    &neural_layer_maxpool_load,     &neural_layer_maxpool_json_export
}
Neural maxpooling layer implemented functions.
Definition at line 70 of file neural_layer_maxpool.h.
Referenced by layer_set_vptr().