XCSF: neural_layer_softmax.c File Reference
neural_layer_softmax.c File Reference
An implementation of a softmax layer.
#include "neural_layer_softmax.h"
#include "neural_activations.h"
#include "utils.h"
Functions
static void malloc_layer_arrays (struct Layer *l)
Allocate memory used by a softmax layer.
static void free_layer_arrays (const struct Layer *l)
Free memory used by a softmax layer.
void neural_layer_softmax_init (struct Layer *l, const struct ArgsLayer *args)
Creates and initialises a softmax layer.
struct Layer * neural_layer_softmax_copy (const struct Layer *src)
Initialises and creates a copy of one softmax layer from another.
void neural_layer_softmax_rand (struct Layer *l)
Dummy function since softmax layers have no weights.
void neural_layer_softmax_forward (const struct Layer *l, const struct Net *net, const double *input)
Forward propagates a softmax layer.
void neural_layer_softmax_backward (const struct Layer *l, const struct Net *net, const double *input, double *delta)
Backward propagates a softmax layer.
void neural_layer_softmax_update (const struct Layer *l)
Dummy function since a softmax layer has no weights.
void neural_layer_softmax_print (const struct Layer *l, const bool print_weights)
Prints a softmax layer.
char * neural_layer_softmax_json_export (const struct Layer *l, const bool return_weights)
Returns a json formatted string representation of a softmax layer.
bool neural_layer_softmax_mutate (struct Layer *l)
Dummy function since a softmax layer cannot be mutated.
void neural_layer_softmax_resize (struct Layer *l, const struct Layer *prev)
Resizes a softmax layer if the previous layer has changed size.
void neural_layer_softmax_free (const struct Layer *l)
Free memory used by a softmax layer.
double * neural_layer_softmax_output (const struct Layer *l)
Returns the output from a softmax layer.
size_t neural_layer_softmax_save (const struct Layer *l, FILE *fp)
Writes a softmax layer to a file.
size_t neural_layer_softmax_load (struct Layer *l, FILE *fp)
Reads a softmax layer from a file.
Detailed Description
An implementation of a softmax layer.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2021.
Definition in file neural_layer_softmax.c.
Function Documentation
free_layer_arrays()
static void free_layer_arrays (const struct Layer * l) static
Free memory used by a softmax layer.
Parameters
[in] l The layer to be freed.
Definition at line 45 of file neural_layer_softmax.c.
References Layer::delta, and Layer::output.
Referenced by neural_layer_softmax_free(), and neural_layer_softmax_resize().
malloc_layer_arrays()
static void malloc_layer_arrays (struct Layer * l) static
Allocate memory used by a softmax layer.
Parameters
[in] l The layer to be allocated memory.
Definition at line 33 of file neural_layer_softmax.c.
References Layer::delta, layer_guard_outputs(), Layer::n_outputs, and Layer::output.
Referenced by neural_layer_softmax_copy(), neural_layer_softmax_init(), neural_layer_softmax_load(), and neural_layer_softmax_resize().
neural_layer_softmax_backward()
void neural_layer_softmax_backward (const struct Layer * l, const struct Net * net, const double * input, double * delta)
Backward propagates a softmax layer.
Parameters
[in] l The layer to backward propagate.
[in] net Network containing the layer.
[in] input The input to the layer.
[out] delta The previous layer's error.
Definition at line 142 of file neural_layer_softmax.c.
References Layer::delta, Layer::i, and Layer::n_inputs.
neural_layer_softmax_copy()
struct Layer* neural_layer_softmax_copy (const struct Layer * src)
Initialises and creates a copy of one softmax layer from another.
Parameters
[in] src The source layer.
Returns
A pointer to the new layer.
Definition at line 75 of file neural_layer_softmax.c.
References layer_defaults(), Layer::layer_vptr, malloc_layer_arrays(), Layer::max_outputs, Layer::n_inputs, Layer::n_outputs, Layer::out_c, Layer::out_h, Layer::out_w, Layer::scale, SOFTMAX, and Layer::type.
neural_layer_softmax_forward()
void neural_layer_softmax_forward (const struct Layer * l, const struct Net * net, const double * input)
Forward propagates a softmax layer.
Parameters
[in] l Layer to forward propagate.
[in] net Network containing the layer.
[in] input Input to the layer.
Definition at line 113 of file neural_layer_softmax.c.
References Layer::i, Layer::n_inputs, Layer::output, and Layer::scale.
neural_layer_softmax_free()
void neural_layer_softmax_free (const struct Layer * l)
Free memory used by a softmax layer.
Parameters
[in] l The layer to be freed.
Definition at line 234 of file neural_layer_softmax.c.
References free_layer_arrays().
neural_layer_softmax_init()
void neural_layer_softmax_init (struct Layer * l, const struct ArgsLayer * args)
Creates and initialises a softmax layer.
Parameters
[in] l Layer to initialise.
[in] args Parameters to initialise the layer.
Definition at line 57 of file neural_layer_softmax.c.
References malloc_layer_arrays(), Layer::max_outputs, Layer::n_inputs, ArgsLayer::n_inputs, Layer::n_outputs, Layer::out_c, Layer::out_h, Layer::out_w, Layer::scale, and ArgsLayer::scale.
neural_layer_softmax_json_export()
char* neural_layer_softmax_json_export (const struct Layer * l, const bool return_weights)
Returns a json formatted string representation of a softmax layer.
Parameters
[in] l The layer to return.
[in] return_weights Whether to return the values of weights and biases.
Returns
String encoded in json format.
Definition at line 185 of file neural_layer_softmax.c.
References Layer::n_inputs, Layer::n_outputs, and Layer::scale.
Referenced by neural_layer_softmax_print().
neural_layer_softmax_load()
size_t neural_layer_softmax_load (struct Layer * l, FILE * fp)
Reads a softmax layer from a file.
Parameters
[in] l The layer to load.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 274 of file neural_layer_softmax.c.
References malloc_layer_arrays(), Layer::max_outputs, Layer::n_inputs, Layer::n_outputs, Layer::out_c, Layer::out_h, Layer::out_w, and Layer::scale.
neural_layer_softmax_mutate()
bool neural_layer_softmax_mutate (struct Layer * l)
Dummy function since a softmax layer cannot be mutated.
Parameters
[in] l A softmax layer.
Returns
False.
Definition at line 205 of file neural_layer_softmax.c.
neural_layer_softmax_output()
double* neural_layer_softmax_output (const struct Layer * l)
Returns the output from a softmax layer.
Parameters
[in] l The layer whose output to return.
Returns
The layer output.
Definition at line 245 of file neural_layer_softmax.c.
References Layer::output.
neural_layer_softmax_print()
void neural_layer_softmax_print (const struct Layer * l, const bool print_weights)
Prints a softmax layer.
Parameters
[in] l The layer to print.
[in] print_weights Whether to print the values of weights and biases.
Definition at line 170 of file neural_layer_softmax.c.
References neural_layer_softmax_json_export().
neural_layer_softmax_rand()
void neural_layer_softmax_rand (struct Layer * l)
Dummy function since softmax layers have no weights.
Parameters
[in] l A softmax layer.
Definition at line 101 of file neural_layer_softmax.c.
neural_layer_softmax_resize()
void neural_layer_softmax_resize (struct Layer * l, const struct Layer * prev)
Resizes a softmax layer if the previous layer has changed size.
Parameters
[in] l The layer to resize.
[in] prev The layer previous to the one being resized.
Definition at line 217 of file neural_layer_softmax.c.
References free_layer_arrays(), malloc_layer_arrays(), Layer::max_outputs, Layer::n_inputs, Layer::n_outputs, Layer::out_c, Layer::out_h, and Layer::out_w.
neural_layer_softmax_save()
size_t neural_layer_softmax_save (const struct Layer * l, FILE * fp)
Writes a softmax layer to a file.
Parameters
[in] l The layer to save.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 257 of file neural_layer_softmax.c.
References Layer::max_outputs, Layer::n_inputs, Layer::n_outputs, and Layer::scale.
neural_layer_softmax_update()
void neural_layer_softmax_update (const struct Layer * l)
Dummy function since a softmax layer has no weights.
Parameters
[in] l A softmax layer.
Definition at line 159 of file neural_layer_softmax.c.