XCSF: pa.c File Reference
pa.c File Reference
Prediction array functions.
#include "pa.h"
#include "cl.h"
#include "utils.h"
Functions
static void pa_reset (const struct XCSF *xcsf)
Resets the prediction array to zero.
void pa_init (struct XCSF *xcsf)
Initialises the prediction array.
void pa_build (const struct XCSF *xcsf, const double *x)
Builds the prediction array for the specified input.
int pa_best_action (const struct XCSF *xcsf)
Returns the best action in the prediction array.
int pa_rand_action (const struct XCSF *xcsf)
Returns a random action from the prediction array.
double pa_best_val (const struct XCSF *xcsf)
Returns the highest value in the prediction array.
double pa_val (const struct XCSF *xcsf, const int action)
Returns the value of a specified action in the prediction array.
void pa_free (const struct XCSF *xcsf)
Frees the prediction array.
Detailed Description
Prediction array functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file pa.c.
Function Documentation
pa_best_action()
int pa_best_action (const struct XCSF * xcsf)
Returns the best action in the prediction array.
Parameters
[in] xcsf The XCSF data structure.
Returns
The best action.
Definition at line 118 of file pa.c.
References max_index().
Referenced by xcs_rl_decision().
pa_best_val()
double pa_best_val (const struct XCSF * xcsf)
Returns the highest value in the prediction array.
Parameters
[in] xcsf The XCSF data structure.
Returns
The highest value in the prediction array.
Definition at line 144 of file pa.c.
References max_index().
Referenced by xcs_rl_update().
pa_build()
void pa_build (const struct XCSF * xcsf, const double * x)
Builds the prediction array for the specified input.
Calculates the match set mean fitness weighted prediction for each action. For supervised learning n_actions=1; reinforcement learning y_dim=1.
Parameters
[in] xcsf The XCSF data structure.
[in] x The input state.
Definition at line 61 of file pa.c.
References Cl::action, Clist::cl, cl_predict(), Cl::fit, Set::list, Clist::next, pa_reset(), and Set::size.
Referenced by xcs_rl_decision(), xcs_rl_fit(), and xcs_supervised_trial().
pa_free()
void pa_free (const struct XCSF * xcsf)
Frees the prediction array.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 171 of file pa.c.
Referenced by main(), and xcsf_ae_to_classifier().
pa_init()
void pa_init (struct XCSF * xcsf)
Initialises the prediction array.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 46 of file pa.c.
Referenced by xcsf_ae_to_classifier(), and xcsf_init().
pa_rand_action()
int pa_rand_action (const struct XCSF * xcsf)
Returns a random action from the prediction array.
Parameters
[in] xcsf The XCSF data structure.
Returns
A random action.
Definition at line 129 of file pa.c.
References rand_uniform_int().
Referenced by xcs_rl_decision().
pa_reset()
static void pa_reset (const struct XCSF * xcsf) static
Resets the prediction array to zero.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 33 of file pa.c.
Referenced by pa_build().
pa_val()
double pa_val (const struct XCSF * xcsf, const int action)
Returns the value of a specified action in the prediction array.
Parameters
[in] xcsf The XCSF data structure.
[in] action The specified action.
Returns
The value of the action in the prediction array.
Definition at line 157 of file pa.c.
Referenced by xcs_rl_end_step(), xcs_rl_error(), and xcs_rl_fit().