XCSF: param.c File Reference
param.c File Reference
Functions for setting and printing parameters.
#include "param.h"
#include "action.h"
#include "condition.h"
#include "ea.h"
#include "prediction.h"
Functions
static void param_defaults_general (struct XCSF *xcsf)
Initialises default XCSF general parameters.
static void param_print_general (const struct XCSF *xcsf)
Prints XCSF general parameters.
static size_t param_save_general (const struct XCSF *xcsf, FILE *fp)
Saves XCSF general parameters.
static size_t param_load_general (struct XCSF *xcsf, FILE *fp)
Loads XCSF general parameters.
static void param_defaults_cl_general (struct XCSF *xcsf)
Initialises default general classifier parameters.
static void param_print_cl_general (const struct XCSF *xcsf)
Prints XCSF general classifier parameters.
static size_t param_save_cl_general (const struct XCSF *xcsf, FILE *fp)
Saves XCSF general classifier parameters.
static size_t param_load_cl_general (struct XCSF *xcsf, FILE *fp)
Loads XCSF general classifier parameters.
static void param_defaults_multistep (struct XCSF *xcsf)
Initialises default multistep parameters.
static void param_print_multistep (const struct XCSF *xcsf)
Prints XCSF multistep parameters.
static size_t param_save_multistep (const struct XCSF *xcsf, FILE *fp)
Saves multistep parameters.
static size_t param_load_multistep (struct XCSF *xcsf, FILE *fp)
Saves multistep parameters.
static void param_defaults_subsumption (struct XCSF *xcsf)
Initialises default subsumption parameters.
static void param_print_subsumption (const struct XCSF *xcsf)
Prints XCSF subsumption parameters.
static size_t param_save_subsumption (const struct XCSF *xcsf, FILE *fp)
Saves subsumption parameters.
static size_t param_load_subsumption (struct XCSF *xcsf, FILE *fp)
Loads subsumption parameters.
void param_init (struct XCSF *xcsf, const int x_dim, const int y_dim, const int n_actions)
Initialises default XCSF parameters.
void param_free (struct XCSF *xcsf)
void param_print (const struct XCSF *xcsf)
Prints all XCSF parameters.
size_t param_save (const struct XCSF *xcsf, FILE *fp)
Writes the XCSF data structure to a file.
size_t param_load (struct XCSF *xcsf, FILE *fp)
Reads the XCSF data structure from a file.
void param_set_omp_num_threads (struct XCSF *xcsf, const int a)
Sets the number of OMP threads.
void param_set_pop_init (struct XCSF *xcsf, const bool a)
void param_set_max_trials (struct XCSF *xcsf, const int a)
void param_set_perf_trials (struct XCSF *xcsf, const int a)
void param_set_pop_size (struct XCSF *xcsf, const int a)
void param_set_loss_func_string (struct XCSF *xcsf, const char *a)
void param_set_loss_func (struct XCSF *xcsf, const int a)
void param_set_stateful (struct XCSF *xcsf, const bool a)
void param_set_compaction (struct XCSF *xcsf, const bool a)
void param_set_huber_delta (struct XCSF *xcsf, const double a)
void param_set_gamma (struct XCSF *xcsf, const double a)
void param_set_teletransportation (struct XCSF *xcsf, const int a)
void param_set_p_explore (struct XCSF *xcsf, const double a)
void param_set_alpha (struct XCSF *xcsf, const double a)
void param_set_beta (struct XCSF *xcsf, const double a)
void param_set_delta (struct XCSF *xcsf, const double a)
void param_set_e0 (struct XCSF *xcsf, const double a)
void param_set_init_error (struct XCSF *xcsf, const double a)
void param_set_init_fitness (struct XCSF *xcsf, const double a)
void param_set_nu (struct XCSF *xcsf, const double a)
void param_set_theta_del (struct XCSF *xcsf, const int a)
void param_set_m_probation (struct XCSF *xcsf, const int a)
void param_set_set_subsumption (struct XCSF *xcsf, const bool a)
void param_set_theta_sub (struct XCSF *xcsf, const int a)
void param_set_x_dim (struct XCSF *xcsf, const int a)
void param_set_explore (struct XCSF *xcsf, const bool a)
void param_set_y_dim (struct XCSF *xcsf, const int a)
void param_set_n_actions (struct XCSF *xcsf, const int a)
Detailed Description
Functions for setting and printing parameters.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file param.c.
Function Documentation
param_defaults_cl_general()
static void param_defaults_cl_general (struct XCSF * xcsf) static
Initialises default general classifier parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 115 of file param.c.
References param_set_alpha(), param_set_beta(), param_set_compaction(), param_set_delta(), param_set_e0(), param_set_init_error(), param_set_init_fitness(), param_set_m_probation(), param_set_nu(), param_set_stateful(), and param_set_theta_del().
Referenced by param_init().
param_defaults_general()
static void param_defaults_general (struct XCSF * xcsf) static
Initialises default XCSF general parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 39 of file param.c.
References LOSS_MAE, param_set_huber_delta(), param_set_loss_func(), param_set_max_trials(), param_set_omp_num_threads(), param_set_perf_trials(), param_set_pop_init(), and param_set_pop_size().
Referenced by param_init().
param_defaults_multistep()
static void param_defaults_multistep (struct XCSF * xcsf) static
Initialises default multistep parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 205 of file param.c.
References param_set_gamma(), param_set_p_explore(), and param_set_teletransportation().
Referenced by param_init().
param_defaults_subsumption()
static void param_defaults_subsumption (struct XCSF * xcsf) static
Initialises default subsumption parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 261 of file param.c.
References param_set_set_subsumption(), and param_set_theta_sub().
Referenced by param_init().
param_free()
void param_free (struct XCSF * xcsf)
Definition at line 343 of file param.c.
References XCSF::act, action_param_free(), XCSF::cond, cond_param_free(), XCSF::ea, XCSF::pred, and pred_param_free().
Referenced by main().
param_init()
void param_init (struct XCSF * xcsf, const int x_dim, const int y_dim, const int n_actions)
Initialises default XCSF parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] x_dim The dimensionality of the input variables.
[in] y_dim The dimensionality of the prediction variables.
[in] n_actions The total number of possible actions.
Definition at line 317 of file param.c.
References XCSF::act, action_param_defaults(), XCSF::aset_size, XCSF::cond, cond_param_defaults(), XCSF::E0, XCSF::ea, ea_param_defaults(), XCSF::error, XCSF::mfrac, XCSF::mset_size, param_defaults_cl_general(), param_defaults_general(), param_defaults_multistep(), param_defaults_subsumption(), param_set_n_actions(), param_set_x_dim(), param_set_y_dim(), XCSF::pred, pred_param_defaults(), and XCSF::time.
Referenced by env_csv_init(), env_maze_init(), env_mux_init(), and XCS::XCS().
param_load()
size_t param_load (struct XCSF * xcsf, FILE * fp)
Reads the XCSF data structure from a file.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the input file.
Returns
The total number of elements read.
Definition at line 422 of file param.c.
References action_param_load(), XCSF::aset_size, cond_param_load(), ea_param_load(), XCSF::error, XCSF::explore, XCSF::mfrac, XCSF::mset_size, XCSF::n_actions, param_load_cl_general(), param_load_general(), param_load_multistep(), param_load_subsumption(), pred_param_load(), XCSF::time, XCSF::x_dim, and XCSF::y_dim.
Referenced by xcsf_load().
param_load_cl_general()
static size_t param_load_cl_general (struct XCSF * xcsf, FILE * fp) static
Loads XCSF general classifier parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements read.
Definition at line 183 of file param.c.
References XCSF::ALPHA, XCSF::BETA, XCSF::COMPACTION, XCSF::DELTA, XCSF::E0, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::M_PROBATION, XCSF::NU, XCSF::STATEFUL, and XCSF::THETA_DEL.
Referenced by param_load().
param_load_general()
static size_t param_load_general (struct XCSF * xcsf, FILE * fp) static
Loads XCSF general parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements read.
Definition at line 96 of file param.c.
References XCSF::HUBER_DELTA, XCSF::LOSS_FUNC, loss_set_func(), XCSF::MAX_TRIALS, XCSF::OMP_NUM_THREADS, XCSF::PERF_TRIALS, XCSF::POP_INIT, and XCSF::POP_SIZE.
Referenced by param_load().
param_load_multistep()
static size_t param_load_multistep (struct XCSF * xcsf, FILE * fp) static
Saves multistep parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements read.
Definition at line 247 of file param.c.
References XCSF::GAMMA, XCSF::P_EXPLORE, and XCSF::TELETRANSPORTATION.
Referenced by param_load().
param_load_subsumption()
static size_t param_load_subsumption (struct XCSF * xcsf, FILE * fp) static
Loads subsumption parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements read.
Definition at line 301 of file param.c.
References XCSF::SET_SUBSUMPTION, and XCSF::THETA_SUB.
Referenced by param_load().
param_print()
void param_print (const struct XCSF * xcsf)
Prints all XCSF parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 359 of file param.c.
References action_param_print(), XCSF::cond, cond_param_print(), ea_param_print(), XCSF::n_actions, param_print_cl_general(), param_print_general(), param_print_multistep(), param_print_subsumption(), pred_param_print(), RULE_TYPE_DGP, RULE_TYPE_NETWORK, RULE_TYPE_NEURAL, ArgsCond::type, VERSION_BUILD, VERSION_MAJOR, and VERSION_MINOR.
Referenced by main(), and XCS::print_params().
param_print_cl_general()
static void param_print_cl_general (const struct XCSF * xcsf) static
Prints XCSF general classifier parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 135 of file param.c.
References XCSF::ALPHA, XCSF::BETA, XCSF::COMPACTION, XCSF::DELTA, XCSF::E0, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::M_PROBATION, XCSF::NU, XCSF::STATEFUL, and XCSF::THETA_DEL.
Referenced by param_print().
param_print_general()
static void param_print_general (const struct XCSF * xcsf) static
Prints XCSF general parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 55 of file param.c.
References XCSF::HUBER_DELTA, XCSF::LOSS_FUNC, LOSS_HUBER, loss_type_as_string(), XCSF::MAX_TRIALS, XCSF::OMP_NUM_THREADS, XCSF::PERF_TRIALS, XCSF::POP_INIT, and XCSF::POP_SIZE.
Referenced by param_print().
param_print_multistep()
static void param_print_multistep (const struct XCSF * xcsf) static
Prints XCSF multistep parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 217 of file param.c.
References XCSF::GAMMA, XCSF::P_EXPLORE, and XCSF::TELETRANSPORTATION.
Referenced by param_print().
param_print_subsumption()
static void param_print_subsumption (const struct XCSF * xcsf) static
Prints XCSF subsumption parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 272 of file param.c.
References XCSF::SET_SUBSUMPTION, and XCSF::THETA_SUB.
Referenced by param_print().
param_save()
size_t param_save (const struct XCSF * xcsf, FILE * fp)
Writes the XCSF data structure to a file.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 392 of file param.c.
References action_param_save(), XCSF::aset_size, cond_param_save(), ea_param_save(), XCSF::error, XCSF::explore, XCSF::mfrac, XCSF::mset_size, XCSF::n_actions, param_save_cl_general(), param_save_general(), param_save_multistep(), param_save_subsumption(), pred_param_save(), XCSF::time, XCSF::x_dim, and XCSF::y_dim.
Referenced by xcsf_save().
param_save_cl_general()
static size_t param_save_cl_general (const struct XCSF * xcsf, FILE * fp) static
Saves XCSF general classifier parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 159 of file param.c.
References XCSF::ALPHA, XCSF::BETA, XCSF::COMPACTION, XCSF::DELTA, XCSF::E0, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::M_PROBATION, XCSF::NU, XCSF::STATEFUL, and XCSF::THETA_DEL.
Referenced by param_save().
param_save_general()
static size_t param_save_general (const struct XCSF * xcsf, FILE * fp) static
Saves XCSF general parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 76 of file param.c.
References XCSF::HUBER_DELTA, XCSF::LOSS_FUNC, XCSF::MAX_TRIALS, XCSF::OMP_NUM_THREADS, XCSF::PERF_TRIALS, XCSF::POP_INIT, and XCSF::POP_SIZE.
Referenced by param_save().
param_save_multistep()
static size_t param_save_multistep (const struct XCSF * xcsf, FILE * fp) static
Saves multistep parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 231 of file param.c.
References XCSF::GAMMA, XCSF::P_EXPLORE, and XCSF::TELETRANSPORTATION.
Referenced by param_save().
param_save_subsumption()
static size_t param_save_subsumption (const struct XCSF * xcsf, FILE * fp) static
Saves subsumption parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 286 of file param.c.
References XCSF::SET_SUBSUMPTION, and XCSF::THETA_SUB.
Referenced by param_save().
param_set_alpha()
void param_set_alpha (struct XCSF * xcsf, const double a)
Definition at line 597 of file param.c.
References XCSF::ALPHA.
Referenced by config_cl_gen(), param_defaults_cl_general(), and XCS::set_alpha().
param_set_beta()
void param_set_beta (struct XCSF * xcsf, const double a)
Definition at line 611 of file param.c.
References XCSF::BETA.
Referenced by config_cl_gen(), param_defaults_cl_general(), and XCS::set_beta().
param_set_compaction()
void param_set_compaction (struct XCSF * xcsf, const bool a)
Definition at line 541 of file param.c.
References XCSF::COMPACTION.
Referenced by config_cl_gen(), param_defaults_cl_general(), and XCS::set_compaction().
param_set_delta()
void param_set_delta (struct XCSF * xcsf, const double a)
Definition at line 625 of file param.c.
References XCSF::DELTA.
Referenced by config_cl_gen(), param_defaults_cl_general(), and XCS::set_delta().
param_set_e0()
void param_set_e0 (struct XCSF * xcsf, const double a)
Definition at line 639 of file param.c.
References XCSF::E0.
Referenced by config_cl_gen(), param_defaults_cl_general(), and XCS::set_e0().
param_set_explore()
void param_set_explore (struct XCSF * xcsf, const bool a)
Definition at line 733 of file param.c.
References XCSF::explore.
Referenced by XCS::decision(), xcs_rl_fit(), xcs_rl_trial(), xcs_supervised_fit(), xcs_supervised_predict(), xcs_supervised_score(), and xcs_supervised_score_n().
param_set_gamma()
void param_set_gamma (struct XCSF * xcsf, const double a)
Definition at line 558 of file param.c.
References XCSF::GAMMA.
Referenced by config_multi(), param_defaults_multistep(), and XCS::set_gamma().
param_set_huber_delta()
void param_set_huber_delta (struct XCSF * xcsf, const double a)
Definition at line 547 of file param.c.
References XCSF::HUBER_DELTA.
Referenced by config_general(), param_defaults_general(), and XCS::set_huber_delta().
param_set_init_error()
void param_set_init_error (struct XCSF * xcsf, const double a)
Definition at line 650 of file param.c.
References XCSF::INIT_ERROR.
Referenced by config_cl_gen(), param_defaults_cl_general(), and XCS::set_init_error().
param_set_init_fitness()
void param_set_init_fitness (struct XCSF * xcsf, const double a)
Definition at line 661 of file param.c.
References XCSF::INIT_FITNESS.
Referenced by config_cl_gen(), param_defaults_cl_general(), and XCS::set_init_fitness().
param_set_loss_func()
void param_set_loss_func (struct XCSF * xcsf, const int a)
Definition at line 520 of file param.c.
References XCSF::LOSS_FUNC, LOSS_NUM, and loss_set_func().
Referenced by param_defaults_general(), and xcsf_ae_to_classifier().
param_set_loss_func_string()
void param_set_loss_func_string (struct XCSF * xcsf, const char * a)
Definition at line 513 of file param.c.
References XCSF::LOSS_FUNC, loss_set_func(), and loss_type_as_int().
Referenced by config_general(), and XCS::set_loss_func().
param_set_m_probation()
void param_set_m_probation (struct XCSF * xcsf, const int a)
Definition at line 694 of file param.c.
References XCSF::M_PROBATION.
Referenced by config_cl_gen(), param_defaults_cl_general(), and XCS::set_m_probation().
param_set_max_trials()
void param_set_max_trials (struct XCSF * xcsf, const int a)
Definition at line 480 of file param.c.
References XCSF::MAX_TRIALS.
Referenced by config_general(), param_defaults_general(), and XCS::set_max_trials().
param_set_n_actions()
void param_set_n_actions (struct XCSF * xcsf, const int a)
Definition at line 750 of file param.c.
References XCSF::n_actions.
Referenced by param_init().
param_set_nu()
void param_set_nu (struct XCSF * xcsf, const double a)
Definition at line 672 of file param.c.
References XCSF::NU.
Referenced by config_cl_gen(), param_defaults_cl_general(), and XCS::set_nu().
param_set_omp_num_threads()
void param_set_omp_num_threads (struct XCSF * xcsf, const int a)
Sets the number of OMP threads.
Parameters
[in] xcsf The XCSF data structure.
[in] a The number of threads.
Definition at line 457 of file param.c.
References XCSF::OMP_NUM_THREADS.
Referenced by config_general(), param_defaults_general(), and XCS::set_omp_num_threads().
param_set_p_explore()
void param_set_p_explore (struct XCSF * xcsf, const double a)
Definition at line 583 of file param.c.
References XCSF::P_EXPLORE.
Referenced by config_multi(), param_defaults_multistep(), and XCS::set_p_explore().
param_set_perf_trials()
void param_set_perf_trials (struct XCSF * xcsf, const int a)
Definition at line 491 of file param.c.
References XCSF::PERF_TRIALS.
Referenced by config_general(), param_defaults_general(), and XCS::set_perf_trials().
param_set_pop_init()
void param_set_pop_init (struct XCSF * xcsf, const bool a)
Definition at line 474 of file param.c.
References XCSF::POP_INIT.
Referenced by config_general(), param_defaults_general(), and XCS::set_pop_init().
param_set_pop_size()
void param_set_pop_size (struct XCSF * xcsf, const int a)
Definition at line 502 of file param.c.
References XCSF::POP_SIZE.
Referenced by config_general(), param_defaults_general(), and XCS::set_pop_max_size().
param_set_set_subsumption()
void param_set_set_subsumption (struct XCSF * xcsf, const bool a)
Definition at line 705 of file param.c.
References XCSF::SET_SUBSUMPTION.
Referenced by config_subsump(), param_defaults_subsumption(), and XCS::set_set_subsumption().
param_set_stateful()
void param_set_stateful (struct XCSF * xcsf, const bool a)
Definition at line 535 of file param.c.
References XCSF::STATEFUL.
Referenced by config_cl_gen(), param_defaults_cl_general(), and XCS::set_stateful().
param_set_teletransportation()
void param_set_teletransportation (struct XCSF * xcsf, const int a)
Definition at line 572 of file param.c.
References XCSF::TELETRANSPORTATION.
Referenced by config_multi(), param_defaults_multistep(), and XCS::set_teletransportation().
param_set_theta_del()
void param_set_theta_del (struct XCSF * xcsf, const int a)
Definition at line 683 of file param.c.
References XCSF::THETA_DEL.
Referenced by config_cl_gen(), param_defaults_cl_general(), and XCS::set_theta_del().
param_set_theta_sub()
void param_set_theta_sub (struct XCSF * xcsf, const int a)
Definition at line 711 of file param.c.
References XCSF::THETA_SUB.
Referenced by config_subsump(), param_defaults_subsumption(), and XCS::set_theta_sub().
param_set_x_dim()
void param_set_x_dim (struct XCSF * xcsf, const int a)
Definition at line 722 of file param.c.
References XCSF::x_dim.
Referenced by param_init().
param_set_y_dim()
void param_set_y_dim (struct XCSF * xcsf, const int a)
Definition at line 739 of file param.c.
References XCSF::y_dim.
Referenced by param_init(), and xcsf_ae_to_classifier().