XCSF: param.h File Reference
param.h File Reference
Functions for setting and printing parameters.
#include "loss.h"
#include "xcsf.h"
Functions
const char * param_json_export (const struct XCSF *xcsf)
Returns a json formatted string representation of the parameters.
void param_free (struct XCSF *xcsf)
void param_print (const struct XCSF *xcsf)
Prints all XCSF parameters.
void param_init (struct XCSF *xcsf, const int x_dim, const int y_dim, const int n_actions)
Initialises default XCSF parameters.
size_t param_load (struct XCSF *xcsf, FILE *fp)
Reads the XCSF data structure from a file.
size_t param_save (const struct XCSF *xcsf, FILE *fp)
Writes the XCSF data structure to a file.
void param_set_omp_num_threads (struct XCSF *xcsf, const int a)
Sets the number of OMP threads.
void param_set_pop_init (struct XCSF *xcsf, const bool a)
void param_set_max_trials (struct XCSF *xcsf, const int a)
void param_set_perf_trials (struct XCSF *xcsf, const int a)
void param_set_pop_size (struct XCSF *xcsf, const int a)
void param_set_loss_func_string (struct XCSF *xcsf, const char *a)
void param_set_loss_func (struct XCSF *xcsf, const int a)
void param_set_stateful (struct XCSF *xcsf, const bool a)
void param_set_compaction (struct XCSF *xcsf, const bool a)
void param_set_huber_delta (struct XCSF *xcsf, const double a)
void param_set_gamma (struct XCSF *xcsf, const double a)
void param_set_teletransportation (struct XCSF *xcsf, const int a)
void param_set_p_explore (struct XCSF *xcsf, const double a)
void param_set_alpha (struct XCSF *xcsf, const double a)
void param_set_beta (struct XCSF *xcsf, const double a)
void param_set_delta (struct XCSF *xcsf, const double a)
void param_set_e0 (struct XCSF *xcsf, const double a)
void param_set_init_error (struct XCSF *xcsf, const double a)
void param_set_init_fitness (struct XCSF *xcsf, const double a)
void param_set_nu (struct XCSF *xcsf, const double a)
void param_set_theta_del (struct XCSF *xcsf, const int a)
void param_set_m_probation (struct XCSF *xcsf, const int a)
void param_set_set_subsumption (struct XCSF *xcsf, const bool a)
void param_set_theta_sub (struct XCSF *xcsf, const int a)
void param_set_x_dim (struct XCSF *xcsf, const int a)
void param_set_explore (struct XCSF *xcsf, const bool a)
void param_set_y_dim (struct XCSF *xcsf, const int a)
void param_set_n_actions (struct XCSF *xcsf, const int a)
Detailed Description
Functions for setting and printing parameters.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2021.
Definition in file param.h.
Function Documentation
param_free()
void param_free (struct XCSF * xcsf)
Definition at line 88 of file param.c.
References XCSF::act, action_param_free(), XCSF::cond, cond_param_free(), XCSF::ea, XCSF::pred, and pred_param_free().
Referenced by main().
param_init()
void param_init (struct XCSF * xcsf, const int x_dim, const int y_dim, const int n_actions)
Initialises default XCSF parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] x_dim The dimensionality of the input variables.
[in] y_dim The dimensionality of the prediction variables.
[in] n_actions The total number of possible actions.
Definition at line 43 of file param.c.
References XCSF::act, action_param_defaults(), XCSF::aset_size, XCSF::cond, cond_param_defaults(), XCSF::E0, XCSF::ea, ea_param_defaults(), XCSF::error, LOSS_MAE, XCSF::mfrac, XCSF::mset_size, param_set_alpha(), param_set_beta(), param_set_compaction(), param_set_delta(), param_set_e0(), param_set_gamma(), param_set_huber_delta(), param_set_init_error(), param_set_init_fitness(), param_set_loss_func(), param_set_m_probation(), param_set_max_trials(), param_set_n_actions(), param_set_nu(), param_set_omp_num_threads(), param_set_p_explore(), param_set_perf_trials(), param_set_pop_init(), param_set_pop_size(), param_set_set_subsumption(), param_set_stateful(), param_set_teletransportation(), param_set_theta_del(), param_set_theta_sub(), param_set_x_dim(), param_set_y_dim(), XCSF::pred, pred_param_defaults(), and XCSF::time.
Referenced by env_csv_init(), env_maze_init(), env_mux_init(), and XCS::XCS().
param_json_export()
const char* param_json_export (const struct XCSF * xcsf)
Returns a json formatted string representation of the parameters.
Parameters
[in] xcsf XCSF data structure.
Returns
String encoded in json format.
Definition at line 105 of file param.c.
References action_param_json_export(), XCSF::ALPHA, XCSF::BETA, XCSF::COMPACTION, XCSF::cond, cond_param_json_export(), XCSF::DELTA, XCSF::E0, ea_param_json_export(), XCSF::GAMMA, XCSF::HUBER_DELTA, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::LOSS_FUNC, LOSS_HUBER, loss_type_as_string(), XCSF::M_PROBATION, XCSF::MAX_TRIALS, XCSF::n_actions, XCSF::NU, XCSF::OMP_NUM_THREADS, XCSF::P_EXPLORE, XCSF::PERF_TRIALS, XCSF::POP_INIT, XCSF::POP_SIZE, pred_param_json_export(), RULE_TYPE_DGP, RULE_TYPE_NETWORK, RULE_TYPE_NEURAL, XCSF::SET_SUBSUMPTION, XCSF::STATEFUL, XCSF::TELETRANSPORTATION, XCSF::THETA_DEL, XCSF::THETA_SUB, ArgsCond::type, VERSION_BUILD, VERSION_MAJOR, VERSION_MINOR, XCSF::x_dim, and XCSF::y_dim.
Referenced by XCS::json_parameters(), and param_print().
param_load()
size_t param_load (struct XCSF * xcsf, FILE * fp)
Reads the XCSF data structure from a file.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the input file.
Returns
The total number of elements read.
Definition at line 231 of file param.c.
References action_param_load(), XCSF::ALPHA, XCSF::aset_size, XCSF::BETA, XCSF::COMPACTION, cond_param_load(), XCSF::DELTA, XCSF::E0, ea_param_load(), XCSF::error, XCSF::explore, XCSF::GAMMA, XCSF::HUBER_DELTA, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::LOSS_FUNC, loss_set_func(), XCSF::M_PROBATION, XCSF::MAX_TRIALS, XCSF::mfrac, XCSF::mset_size, XCSF::n_actions, XCSF::NU, XCSF::OMP_NUM_THREADS, XCSF::P_EXPLORE, XCSF::PERF_TRIALS, XCSF::POP_INIT, XCSF::POP_SIZE, pred_param_load(), XCSF::SET_SUBSUMPTION, XCSF::STATEFUL, XCSF::TELETRANSPORTATION, XCSF::THETA_DEL, XCSF::THETA_SUB, XCSF::time, XCSF::x_dim, and XCSF::y_dim.
Referenced by xcsf_load().
param_print()
void param_print (const struct XCSF * xcsf)
Prints all XCSF parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 170 of file param.c.
References param_json_export().
Referenced by main(), and XCS::print_params().
param_save()
size_t param_save (const struct XCSF * xcsf, FILE * fp)
Writes the XCSF data structure to a file.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 182 of file param.c.
References action_param_save(), XCSF::ALPHA, XCSF::aset_size, XCSF::BETA, XCSF::COMPACTION, cond_param_save(), XCSF::DELTA, XCSF::E0, ea_param_save(), XCSF::error, XCSF::explore, XCSF::GAMMA, XCSF::HUBER_DELTA, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::LOSS_FUNC, XCSF::M_PROBATION, XCSF::MAX_TRIALS, XCSF::mfrac, XCSF::mset_size, XCSF::n_actions, XCSF::NU, XCSF::OMP_NUM_THREADS, XCSF::P_EXPLORE, XCSF::PERF_TRIALS, XCSF::POP_INIT, XCSF::POP_SIZE, pred_param_save(), XCSF::SET_SUBSUMPTION, XCSF::STATEFUL, XCSF::TELETRANSPORTATION, XCSF::THETA_DEL, XCSF::THETA_SUB, XCSF::time, XCSF::x_dim, and XCSF::y_dim.
Referenced by xcsf_save().
param_set_alpha()
void param_set_alpha (struct XCSF * xcsf, const double a)
Definition at line 426 of file param.c.
References XCSF::ALPHA.
Referenced by config_cl_gen(), param_init(), and XCS::set_alpha().
param_set_beta()
void param_set_beta (struct XCSF * xcsf, const double a)
Definition at line 440 of file param.c.
References XCSF::BETA.
Referenced by config_cl_gen(), param_init(), and XCS::set_beta().
param_set_compaction()
void param_set_compaction (struct XCSF * xcsf, const bool a)
Definition at line 370 of file param.c.
References XCSF::COMPACTION.
Referenced by config_cl_gen(), param_init(), and XCS::set_compaction().
param_set_delta()
void param_set_delta (struct XCSF * xcsf, const double a)
Definition at line 454 of file param.c.
References XCSF::DELTA.
Referenced by config_cl_gen(), param_init(), and XCS::set_delta().
param_set_e0()
void param_set_e0 (struct XCSF * xcsf, const double a)
Definition at line 468 of file param.c.
References XCSF::E0.
Referenced by config_cl_gen(), param_init(), and XCS::set_e0().
param_set_explore()
void param_set_explore (struct XCSF * xcsf, const bool a)
Definition at line 562 of file param.c.
References XCSF::explore.
Referenced by XCS::decision(), xcs_rl_fit(), xcs_rl_trial(), xcs_supervised_fit(), xcs_supervised_predict(), xcs_supervised_score(), and xcs_supervised_score_n().
param_set_gamma()
void param_set_gamma (struct XCSF * xcsf, const double a)
Definition at line 387 of file param.c.
References XCSF::GAMMA.
Referenced by config_multi(), param_init(), and XCS::set_gamma().
param_set_huber_delta()
void param_set_huber_delta (struct XCSF * xcsf, const double a)
Definition at line 376 of file param.c.
References XCSF::HUBER_DELTA.
Referenced by config_general(), param_init(), and XCS::set_huber_delta().
param_set_init_error()
void param_set_init_error (struct XCSF * xcsf, const double a)
Definition at line 479 of file param.c.
References XCSF::INIT_ERROR.
Referenced by config_cl_gen(), param_init(), and XCS::set_init_error().
param_set_init_fitness()
void param_set_init_fitness (struct XCSF * xcsf, const double a)
Definition at line 490 of file param.c.
References XCSF::INIT_FITNESS.
Referenced by config_cl_gen(), param_init(), and XCS::set_init_fitness().
param_set_loss_func()
void param_set_loss_func (struct XCSF * xcsf, const int a)
Definition at line 349 of file param.c.
References XCSF::LOSS_FUNC, LOSS_NUM, and loss_set_func().
Referenced by param_init(), and xcsf_ae_to_classifier().
param_set_loss_func_string()
void param_set_loss_func_string (struct XCSF * xcsf, const char * a)
Definition at line 342 of file param.c.
References XCSF::LOSS_FUNC, loss_set_func(), and loss_type_as_int().
Referenced by config_general(), and XCS::set_loss_func().
param_set_m_probation()
void param_set_m_probation (struct XCSF * xcsf, const int a)
Definition at line 523 of file param.c.
References XCSF::M_PROBATION.
Referenced by config_cl_gen(), param_init(), and XCS::set_m_probation().
param_set_max_trials()
void param_set_max_trials (struct XCSF * xcsf, const int a)
Definition at line 309 of file param.c.
References XCSF::MAX_TRIALS.
Referenced by config_general(), param_init(), and XCS::set_max_trials().
param_set_n_actions()
void param_set_n_actions (struct XCSF * xcsf, const int a)
Definition at line 579 of file param.c.
References XCSF::n_actions.
Referenced by param_init().
param_set_nu()
void param_set_nu (struct XCSF * xcsf, const double a)
Definition at line 501 of file param.c.
References XCSF::NU.
Referenced by config_cl_gen(), param_init(), and XCS::set_nu().
param_set_omp_num_threads()
void param_set_omp_num_threads (struct XCSF * xcsf, const int a)
Sets the number of OMP threads.
Parameters
[in] xcsf The XCSF data structure.
[in] a The number of threads.
Definition at line 286 of file param.c.
References XCSF::OMP_NUM_THREADS.
Referenced by config_general(), param_init(), and XCS::set_omp_num_threads().
param_set_p_explore()
void param_set_p_explore (struct XCSF * xcsf, const double a)
Definition at line 412 of file param.c.
References XCSF::P_EXPLORE.
Referenced by config_multi(), param_init(), and XCS::set_p_explore().
param_set_perf_trials()
void param_set_perf_trials (struct XCSF * xcsf, const int a)
Definition at line 320 of file param.c.
References XCSF::PERF_TRIALS.
Referenced by config_general(), param_init(), and XCS::set_perf_trials().
param_set_pop_init()
void param_set_pop_init (struct XCSF * xcsf, const bool a)
Definition at line 303 of file param.c.
References XCSF::POP_INIT.
Referenced by config_general(), param_init(), and XCS::set_pop_init().
param_set_pop_size()
void param_set_pop_size (struct XCSF * xcsf, const int a)
Definition at line 331 of file param.c.
References XCSF::POP_SIZE.
Referenced by config_general(), param_init(), and XCS::set_pop_max_size().
param_set_set_subsumption()
void param_set_set_subsumption (struct XCSF * xcsf, const bool a)
Definition at line 534 of file param.c.
References XCSF::SET_SUBSUMPTION.
Referenced by config_subsump(), param_init(), and XCS::set_set_subsumption().
param_set_stateful()
void param_set_stateful (struct XCSF * xcsf, const bool a)
Definition at line 364 of file param.c.
References XCSF::STATEFUL.
Referenced by config_cl_gen(), param_init(), and XCS::set_stateful().
param_set_teletransportation()
void param_set_teletransportation (struct XCSF * xcsf, const int a)
Definition at line 401 of file param.c.
References XCSF::TELETRANSPORTATION.
Referenced by config_multi(), param_init(), and XCS::set_teletransportation().
param_set_theta_del()
void param_set_theta_del (struct XCSF * xcsf, const int a)
Definition at line 512 of file param.c.
References XCSF::THETA_DEL.
Referenced by config_cl_gen(), param_init(), and XCS::set_theta_del().
param_set_theta_sub()
void param_set_theta_sub (struct XCSF * xcsf, const int a)
Definition at line 540 of file param.c.
References XCSF::THETA_SUB.
Referenced by config_subsump(), param_init(), and XCS::set_theta_sub().
param_set_x_dim()
void param_set_x_dim (struct XCSF * xcsf, const int a)
Definition at line 551 of file param.c.
References XCSF::x_dim.
Referenced by param_init().
param_set_y_dim()
void param_set_y_dim (struct XCSF * xcsf, const int a)
Definition at line 568 of file param.c.
References XCSF::y_dim.
Referenced by param_init(), and xcsf_ae_to_classifier().