XCSF: pred_neural.h File Reference
pred_neural.h File Reference
Multi-layer perceptron neural network prediction functions.
#include "neural.h"
#include "neural_activations.h"
#include "neural_layer.h"
#include "prediction.h"
#include "xcsf.h"
Data Structures
struct PredNeural
Multi-layer perceptron neural network prediction data structure.
Functions
void pred_neural_param_defaults (struct XCSF *xcsf)
Initialises default neural prediction parameters.
void pred_neural_param_json_import (struct XCSF *xcsf, cJSON *json)
Sets the neural network parameters from a cJSON object.
bool pred_neural_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Dummy function since neural predictions do not perform crossover.
bool pred_neural_mutate (const struct XCSF *xcsf, const struct Cl *c)
Mutates a neural network prediction.
double pred_neural_eta (const struct XCSF *xcsf, const struct Cl *c, const int layer)
Returns the gradient descent rate of a neural prediction layer.
int pred_neural_connections (const struct XCSF *xcsf, const struct Cl *c, const int layer)
Returns the number of active connections in a neural prediction layer.
int pred_neural_layers (const struct XCSF *xcsf, const struct Cl *c)
Returns the number of layers within a neural network prediction.
int pred_neural_neurons (const struct XCSF *xcsf, const struct Cl *c, const int layer)
Returns the number of neurons in a neural prediction layer.
double pred_neural_size (const struct XCSF *xcsf, const struct Cl *c)
Returns the size of a neural network prediction.
size_t pred_neural_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads a neural network prediction from a file.
size_t pred_neural_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes a neural network prediction to a file.
void pred_neural_compute (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Forward propagates a neural network prediction with a provided input.
void pred_neural_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies a neural network prediction from one classifier to another.
void pred_neural_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by a neural network prediction.
void pred_neural_init (const struct XCSF *xcsf, struct Cl *c)
Creates and initialises a neural network prediction.
void pred_neural_print (const struct XCSF *xcsf, const struct Cl *c)
Prints a neural network prediction.
void pred_neural_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Backward propagates and updates a neural network prediction.
void pred_neural_expand (const struct XCSF *xcsf, const struct Cl *c)
Creates and inserts a hidden layer before the prediction output layer.
void pred_neural_ae_to_classifier (const struct XCSF *xcsf, const struct Cl *c, const int n_del)
Removes prediction (decoder) layers and inserts softmax output layer.
char * pred_neural_json_export (const struct XCSF *xcsf, const struct Cl *c)
Returns a json formatted string representation of a neural prediction.
void pred_neural_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Creates a neural prediction from a cJSON object.
Variables
static struct PredVtbl const pred_neural_vtbl
Multi-layer perceptron neural network prediction implemented functions.
Detailed Description
Multi-layer perceptron neural network prediction functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2021.
Definition in file pred_neural.h.
Function Documentation
pred_neural_ae_to_classifier()
void pred_neural_ae_to_classifier (const struct XCSF * xcsf, const struct Cl * c, const int n_del)
Removes prediction (decoder) layers and inserts softmax output layer.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier to convert from autoencoding to classification.
[in] n_del Number of (decoder) layers to remove from the network.
Definition at line 349 of file pred_neural.c.
References CONNECTED, ArgsLayer::decay, ArgsLayer::eta, ArgsLayer::eta_min, ArgsLayer::evolve_connect, ArgsLayer::evolve_eta, ArgsLayer::evolve_weights, Layer::i, layer_args_init(), layer_init(), LINEAR, ArgsLayer::momentum, Net::n_layers, Net::n_outputs, PredNeural::net, neural_pop(), neural_push(), Cl::pred, ArgsLayer::sgd_weights, and SOFTMAX.
Referenced by xcsf_ae_to_classifier().
pred_neural_compute()
void pred_neural_compute (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Forward propagates a neural network prediction with a provided input.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier calculating the prediction.
[in] x The input state.
Definition at line 106 of file pred_neural.c.
References PredNeural::net, neural_output(), neural_propagate(), Cl::pred, and Cl::prediction.
pred_neural_connections()
int pred_neural_connections (const struct XCSF * xcsf, const struct Cl * c, const int layer)
Returns the number of active connections in a neural prediction layer.
Parameters
[in] xcsf The XCSF data structure.
[in] c Classifier maintaining a neural network prediction.
[in] layer Position of a layer in the network.
Returns
The current number of active (non-zero) connections in a layer.
Definition at line 268 of file pred_neural.c.
References Llist::layer, Layer::n_active, PredNeural::net, Cl::pred, Llist::prev, and Net::tail.
Referenced by clset_mean_pred_connections().
pred_neural_copy()
void pred_neural_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Copies a neural network prediction from one classifier to another.
Parameters
[in] xcsf The XCSF data structure.
[in] dest The destination classifier.
[in] src The source classifier.
Definition at line 73 of file pred_neural.c.
References PredNeural::net, neural_copy(), and Cl::pred.
pred_neural_crossover()
bool pred_neural_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Dummy function since neural predictions do not perform crossover.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The first classifier whose prediction is being crossed.
[in] c2 The second classifier whose prediction is being crossed.
Returns
False.
Definition at line 137 of file pred_neural.c.
pred_neural_eta()
double pred_neural_eta (const struct XCSF * xcsf, const struct Cl * c, const int layer)
Returns the gradient descent rate of a neural prediction layer.
Parameters
[in] xcsf The XCSF data structure.
[in] c Classifier maintaining a neural network prediction.
[in] layer Position of a layer in the network.
Returns
The current gradient descent rate of a layer.
Definition at line 216 of file pred_neural.c.
References Layer::eta, Llist::layer, PredNeural::net, Cl::pred, Llist::prev, and Net::tail.
Referenced by clset_mean_pred_eta().
pred_neural_expand()
void pred_neural_expand (const struct XCSF * xcsf, const struct Cl * c)
Creates and inserts a hidden layer before the prediction output layer.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose neural prediction is to be expanded.
Definition at line 306 of file pred_neural.c.
References CONNECTED, ArgsLayer::decay, ArgsLayer::eta, ArgsLayer::eta_min, ArgsLayer::evolve_connect, ArgsLayer::evolve_eta, ArgsLayer::evolve_functions, ArgsLayer::evolve_weights, ArgsLayer::function, Layer::h, Net::head, Llist::layer, layer_args_init(), layer_init(), Layer::max_outputs, ArgsLayer::momentum, ArgsLayer::n_inputs, Layer::n_inputs, Net::n_layers, Layer::n_outputs, PredNeural::net, neural_insert(), neural_resize(), Llist::next, Cl::pred, and ArgsLayer::sgd_weights.
Referenced by xcsf_pred_expand().
pred_neural_free()
void pred_neural_free (const struct XCSF * xcsf, const struct Cl * c)
Frees the memory used by a neural network prediction.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is to be freed.
Definition at line 58 of file pred_neural.c.
References PredNeural::net, neural_free(), and Cl::pred.
pred_neural_init()
void pred_neural_init (const struct XCSF * xcsf, struct Cl * c)
Creates and initialises a neural network prediction.
Uses fully-connected layers.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is to be initialised.
Definition at line 45 of file pred_neural.c.
References neural_create(), and Cl::pred.
pred_neural_json_export()
char* pred_neural_json_export (const struct XCSF * xcsf, const struct Cl * c)
Returns a json formatted string representation of a neural prediction.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose prediction is to be returned.
Returns
String encoded in json format.
Definition at line 392 of file pred_neural.c.
References PredNeural::net, neural_json_export(), and Cl::pred.
Referenced by pred_neural_print().
pred_neural_json_import()
void pred_neural_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json)
Creates a neural prediction from a cJSON object.
Parameters
[in] xcsf The XCSF data structure.
[in,out] c The classifier to initialise.
[in] json cJSON object.
Definition at line 412 of file pred_neural.c.
References PredNeural::net, neural_json_import(), and Cl::pred.
pred_neural_layers()
int pred_neural_layers (const struct XCSF * xcsf, const struct Cl * c)
Returns the number of layers within a neural network prediction.
Parameters
[in] xcsf The XCSF data structure.
[in] c Classifier maintaining a neural network prediction.
Returns
The number of layers.
Definition at line 292 of file pred_neural.c.
References Net::n_layers, PredNeural::net, and Cl::pred.
Referenced by clset_mean_pred_layers().
pred_neural_load()
size_t pred_neural_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Reads a neural network prediction from a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 199 of file pred_neural.c.
References neural_load(), and Cl::pred.
pred_neural_mutate()
bool pred_neural_mutate (const struct XCSF * xcsf, const struct Cl * c)
Mutates a neural network prediction.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is being mutated.
Returns
Whether any alterations were made.
Definition at line 153 of file pred_neural.c.
References PredNeural::net, neural_mutate(), and Cl::pred.
pred_neural_neurons()
int pred_neural_neurons (const struct XCSF * xcsf, const struct Cl * c, const int layer)
Returns the number of neurons in a neural prediction layer.
Parameters
[in] xcsf The XCSF data structure.
[in] c Classifier maintaining a neural network prediction.
[in] layer Position of a layer in the network.
Returns
The current number of neurons in a layer.
Definition at line 240 of file pred_neural.c.
References CONVOLUTIONAL, Llist::layer, Layer::n_filters, Layer::n_outputs, PredNeural::net, Cl::pred, Llist::prev, Net::tail, and Layer::type.
Referenced by clset_mean_pred_neurons().
pred_neural_param_defaults()
void pred_neural_param_defaults (struct XCSF * xcsf)
Initialises default neural prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 429 of file pred_neural.c.
References CONNECTED, ArgsLayer::eta, ArgsLayer::evolve_connect, ArgsLayer::evolve_eta, ArgsLayer::evolve_neurons, ArgsLayer::evolve_weights, ArgsLayer::function, layer_args_copy(), layer_args_init(), LOGISTIC, ArgsLayer::max_neuron_grow, ArgsLayer::momentum, ArgsLayer::n_init, ArgsLayer::n_inputs, ArgsLayer::n_max, ArgsLayer::next, ArgsLayer::sgd_weights, and ArgsLayer::type.
Referenced by pred_param_defaults().
pred_neural_param_json_import()
void pred_neural_param_json_import (struct XCSF * xcsf, cJSON * json)
Sets the neural network parameters from a cJSON object.
Parameters
[in,out] xcsf The XCSF data structure.
[in] json cJSON object.
Definition at line 462 of file pred_neural.c.
References layer_args_free(), layer_args_init(), layer_args_json_import(), layer_args_validate(), ArgsLayer::n_inputs, and ArgsLayer::next.
Referenced by pred_param_json_import().
pred_neural_print()
void pred_neural_print (const struct XCSF * xcsf, const struct Cl * c)
Prints a neural network prediction.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is to be printed.
Definition at line 122 of file pred_neural.c.
References pred_neural_json_export().
pred_neural_save()
size_t pred_neural_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Writes a neural network prediction to a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 183 of file pred_neural.c.
References PredNeural::net, neural_save(), and Cl::pred.
pred_neural_size()
double pred_neural_size (const struct XCSF * xcsf, const struct Cl * c)
Returns the size of a neural network prediction.
See also
neural_size()
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction size to return.
Returns
The network size.
Definition at line 168 of file pred_neural.c.
References PredNeural::net, neural_size(), and Cl::pred.
pred_neural_update()
void pred_neural_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Backward propagates and updates a neural network prediction.
Precondition
The prediction has been forward propagated for the current state.
Parameters
[in] xcsf The XCSF data structure.
[in] c Classifier whose prediction is to be updated.
[in] x Input state.
[in] y Truth/payoff value.
Definition at line 91 of file pred_neural.c.
References PredNeural::net, neural_learn(), and Cl::pred.
Variable Documentation
pred_neural_vtbl
struct PredVtbl const pred_neural_vtbl static
Initial value:
= {
    &pred_neural_crossover,  &pred_neural_mutate, &pred_neural_compute,
    &pred_neural_copy,       &pred_neural_free,   &pred_neural_init,
    &pred_neural_print,      &pred_neural_update, &pred_neural_size,
    &pred_neural_save,       &pred_neural_load,   &pred_neural_json_export,
    &pred_neural_json_import
}
Multi-layer perceptron neural network prediction implemented functions.
Definition at line 114 of file pred_neural.h.
Referenced by prediction_set().