XCSF: prediction.c File Reference
prediction.c File Reference
Interface for classifier predictions.
#include "pred_constant.h"
#include "pred_neural.h"
#include "pred_nlms.h"
#include "pred_rls.h"
Functions
void prediction_set (const struct XCSF *xcsf, struct Cl *c)
Sets a classifier's prediction functions to the implementations.
const char * prediction_type_as_string (const int type)
Returns a string representation of a prediction type from the integer.
int prediction_type_as_int (const char *type)
Returns the integer representation of a prediction type given a name.
static void pred_param_defaults_neural (struct XCSF *xcsf)
Initialises default neural prediction parameters.
void pred_param_defaults (struct XCSF *xcsf)
Initialises default prediction parameters.
static void pred_param_print_nlms (const struct XCSF *xcsf)
Prints least mean squres prediction parameters.
static void pred_param_print_rls (const struct XCSF *xcsf)
Prints recursive least mean squres prediction parameters.
static void pred_param_print_neural (const struct XCSF *xcsf)
Prints neural network prediction parameters.
void pred_param_print (const struct XCSF *xcsf)
Prints prediction parameters.
size_t pred_param_save (const struct XCSF *xcsf, FILE *fp)
Saves prediction parameters.
size_t pred_param_load (struct XCSF *xcsf, FILE *fp)
Loads prediction parameters.
void pred_param_free (struct XCSF *xcsf)
Frees prediction parameters.
void pred_transform_input (const struct XCSF *xcsf, const double *x, const double X0, double *tmp_input)
Prepares the input state for least squares computation.
void pred_param_set_eta (struct XCSF *xcsf, const double a)
void pred_param_set_eta_min (struct XCSF *xcsf, const double a)
void pred_param_set_lambda (struct XCSF *xcsf, const double a)
void pred_param_set_scale_factor (struct XCSF *xcsf, const double a)
void pred_param_set_x0 (struct XCSF *xcsf, const double a)
void pred_param_set_evolve_eta (struct XCSF *xcsf, const bool a)
void pred_param_set_type (struct XCSF *xcsf, const int a)
void pred_param_set_type_string (struct XCSF *xcsf, const char *a)
Detailed Description
Interface for classifier predictions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file prediction.c.
Function Documentation
pred_param_defaults()
void pred_param_defaults (struct XCSF * xcsf)
Initialises default prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 152 of file prediction.c.
References pred_param_defaults_neural(), pred_param_set_eta(), pred_param_set_eta_min(), pred_param_set_evolve_eta(), pred_param_set_lambda(), pred_param_set_scale_factor(), pred_param_set_type(), pred_param_set_x0(), and PRED_TYPE_NLMS_LINEAR.
Referenced by param_init().
pred_param_defaults_neural()
static void pred_param_defaults_neural (struct XCSF * xcsf) static
Initialises default neural prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 120 of file prediction.c.
References CONNECTED, ArgsLayer::eta, ArgsLayer::evolve_connect, ArgsLayer::evolve_eta, ArgsLayer::evolve_neurons, ArgsLayer::evolve_weights, ArgsLayer::function, ArgsPred::largs, layer_args_copy(), layer_args_init(), LOGISTIC, ArgsLayer::max_neuron_grow, ArgsLayer::momentum, ArgsLayer::n_init, ArgsLayer::n_inputs, ArgsLayer::n_max, ArgsLayer::next, XCSF::pred, ArgsLayer::sgd_weights, ArgsLayer::type, XCSF::x_dim, and XCSF::y_dim.
Referenced by pred_param_defaults().
pred_param_free()
void pred_param_free (struct XCSF * xcsf)
Frees prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 284 of file prediction.c.
References ArgsPred::largs, layer_args_free(), and XCSF::pred.
Referenced by param_free().
pred_param_load()
size_t pred_param_load (struct XCSF * xcsf, FILE * fp)
Loads prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 265 of file prediction.c.
References ArgsPred::eta, ArgsPred::eta_min, ArgsPred::evolve_eta, ArgsPred::lambda, XCSF::pred, ArgsPred::scale_factor, ArgsPred::type, and ArgsPred::x0.
Referenced by param_load().
pred_param_print()
void pred_param_print (const struct XCSF * xcsf)
Prints prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 216 of file prediction.c.
References XCSF::pred, pred_param_print_neural(), pred_param_print_nlms(), pred_param_print_rls(), PRED_TYPE_NEURAL, PRED_TYPE_NLMS_LINEAR, PRED_TYPE_NLMS_QUADRATIC, PRED_TYPE_RLS_LINEAR, PRED_TYPE_RLS_QUADRATIC, prediction_type_as_string(), and ArgsPred::type.
Referenced by param_print().
pred_param_print_neural()
static void pred_param_print_neural (const struct XCSF * xcsf) static
Prints neural network prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 198 of file prediction.c.
References ArgsPred::largs, layer_args_print(), ArgsLayer::next, and XCSF::pred.
Referenced by pred_param_print().
pred_param_print_nlms()
static void pred_param_print_nlms (const struct XCSF * xcsf) static
Prints least mean squres prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 169 of file prediction.c.
References ArgsPred::eta, ArgsPred::eta_min, ArgsPred::evolve_eta, XCSF::pred, and ArgsPred::x0.
Referenced by pred_param_print().
pred_param_print_rls()
static void pred_param_print_rls (const struct XCSF * xcsf) static
Prints recursive least mean squres prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 185 of file prediction.c.
References ArgsPred::lambda, XCSF::pred, ArgsPred::scale_factor, and ArgsPred::x0.
Referenced by pred_param_print().
pred_param_save()
size_t pred_param_save (const struct XCSF * xcsf, FILE * fp)
Saves prediction parameters.
Parameters
[in] xcsf The XCSF data structure.
[in] fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 244 of file prediction.c.
References ArgsPred::eta, ArgsPred::eta_min, ArgsPred::evolve_eta, ArgsPred::lambda, XCSF::pred, ArgsPred::scale_factor, ArgsPred::type, and ArgsPred::x0.
Referenced by param_save().
pred_param_set_eta()
void pred_param_set_eta (struct XCSF * xcsf, const double a)
Definition at line 323 of file prediction.c.
References ArgsPred::eta, and XCSF::pred.
Referenced by config_cl_pred_ls(), pred_param_defaults(), and XCS::unpack_pred_nlms().
pred_param_set_eta_min()
void pred_param_set_eta_min (struct XCSF * xcsf, const double a)
Definition at line 337 of file prediction.c.
References ArgsPred::eta_min, and XCSF::pred.
Referenced by config_cl_pred_ls(), pred_param_defaults(), and XCS::unpack_pred_nlms().
pred_param_set_evolve_eta()
void pred_param_set_evolve_eta (struct XCSF * xcsf, const bool a)
Definition at line 369 of file prediction.c.
References ArgsPred::evolve_eta, and XCSF::pred.
Referenced by config_cl_pred_ls(), pred_param_defaults(), and XCS::unpack_pred_nlms().
pred_param_set_lambda()
void pred_param_set_lambda (struct XCSF * xcsf, const double a)
Definition at line 351 of file prediction.c.
References ArgsPred::lambda, and XCSF::pred.
Referenced by config_cl_pred_ls(), pred_param_defaults(), and XCS::unpack_pred_rls().
pred_param_set_scale_factor()
void pred_param_set_scale_factor (struct XCSF * xcsf, const double a)
Definition at line 357 of file prediction.c.
References XCSF::pred, and ArgsPred::scale_factor.
Referenced by config_cl_pred_ls(), pred_param_defaults(), and XCS::unpack_pred_rls().
pred_param_set_type()
void pred_param_set_type (struct XCSF * xcsf, const int a)
Definition at line 375 of file prediction.c.
References XCSF::pred, and ArgsPred::type.
Referenced by pred_param_defaults().
pred_param_set_type_string()
void pred_param_set_type_string (struct XCSF * xcsf, const char * a)
Definition at line 386 of file prediction.c.
References XCSF::pred, prediction_type_as_int(), and ArgsPred::type.
Referenced by config_cl_pred(), and XCS::set_prediction().
pred_param_set_x0()
void pred_param_set_x0 (struct XCSF * xcsf, const double a)
Definition at line 363 of file prediction.c.
References XCSF::pred, and ArgsPred::x0.
Referenced by config_cl_pred_ls(), pred_param_defaults(), XCS::unpack_pred_nlms(), and XCS::unpack_pred_rls().
pred_transform_input()
void pred_transform_input (const struct XCSF * xcsf, const double * x, const double X0, double * tmp_input)
Prepares the input state for least squares computation.
Parameters
[in] xcsf The XCSF data structure.
[in] x The input state.
[in] X0 Bias term.
[out] tmp_input The transformed input.
Definition at line 297 of file prediction.c.
References XCSF::pred, PRED_TYPE_NLMS_QUADRATIC, PRED_TYPE_RLS_QUADRATIC, ArgsPred::type, and XCSF::x_dim.
Referenced by pred_nlms_compute(), and pred_rls_compute().
prediction_set()
void prediction_set (const struct XCSF * xcsf, struct Cl * c)
Sets a classifier's prediction functions to the implementations.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier to set.
Definition at line 35 of file prediction.c.
References XCSF::pred, pred_constant_vtbl, pred_neural_vtbl, pred_nlms_vtbl, pred_rls_vtbl, PRED_TYPE_CONSTANT, PRED_TYPE_NEURAL, PRED_TYPE_NLMS_LINEAR, PRED_TYPE_NLMS_QUADRATIC, PRED_TYPE_RLS_LINEAR, PRED_TYPE_RLS_QUADRATIC, Cl::pred_vptr, and ArgsPred::type.
Referenced by cl_load(), and cl_rand().
prediction_type_as_int()
int prediction_type_as_int (const char * type)
Returns the integer representation of a prediction type given a name.
Parameters
[in] type String representation of a prediction type.
Returns
Integer representing the prediction type.
Definition at line 91 of file prediction.c.
References PRED_STRING_CONSTANT, PRED_STRING_NEURAL, PRED_STRING_NLMS_LINEAR, PRED_STRING_NLMS_QUADRATIC, PRED_STRING_RLS_LINEAR, PRED_STRING_RLS_QUADRATIC, PRED_TYPE_CONSTANT, PRED_TYPE_NEURAL, PRED_TYPE_NLMS_LINEAR, PRED_TYPE_NLMS_QUADRATIC, PRED_TYPE_RLS_LINEAR, and PRED_TYPE_RLS_QUADRATIC.
Referenced by pred_param_set_type_string().
prediction_type_as_string()
const char* prediction_type_as_string (const int type)
Returns a string representation of a prediction type from the integer.
Parameters
[in] type Integer representation of a prediction type.
Returns
String representing the name of the prediction type.
Definition at line 64 of file prediction.c.
References PRED_STRING_CONSTANT, PRED_STRING_NEURAL, PRED_STRING_NLMS_LINEAR, PRED_STRING_NLMS_QUADRATIC, PRED_STRING_RLS_LINEAR, PRED_STRING_RLS_QUADRATIC, PRED_TYPE_CONSTANT, PRED_TYPE_NEURAL, PRED_TYPE_NLMS_LINEAR, PRED_TYPE_NLMS_QUADRATIC, PRED_TYPE_RLS_LINEAR, and PRED_TYPE_RLS_QUADRATIC.
Referenced by pred_param_print().