XCSF: pred_nlms.c File Reference
pred_nlms.c File Reference
Normalised least mean squares prediction functions.
#include "pred_nlms.h"
#include "blas.h"
#include "sam.h"
#include "utils.h"
Macros
#define N_MU (1)
Number of self-adaptive mutation rates.
Functions
void pred_nlms_init (const struct XCSF *xcsf, struct Cl *c)
Initialises an NLMS prediction.
void pred_nlms_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Copies an NLMS prediction from one classifier to another.
void pred_nlms_free (const struct XCSF *xcsf, const struct Cl *c)
Frees the memory used by an NLMS prediction.
void pred_nlms_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Updates an NLMS prediction for a given input and truth sample.
void pred_nlms_compute (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Computes the current NLMS prediction for a provided input.
void pred_nlms_print (const struct XCSF *xcsf, const struct Cl *c)
Prints an NLMS prediction.
bool pred_nlms_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Dummy function since NLMS predictions do not perform crossover.
bool pred_nlms_mutate (const struct XCSF *xcsf, const struct Cl *c)
Mutates the gradient descent rate used to update an NLMS prediction.
double pred_nlms_size (const struct XCSF *xcsf, const struct Cl *c)
Returns the size of an NLMS prediction.
size_t pred_nlms_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Writes an NLMS prediction to a file.
size_t pred_nlms_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Reads an NLMS prediction from a file.
char * pred_nlms_json_export (const struct XCSF *xcsf, const struct Cl *c)
Returns a json formatted string representation of an NLMS prediction.
void pred_nlms_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Creates an NLMS prediction from a cJSON object.
char * pred_nlms_param_json_export (const struct XCSF *xcsf)
Returns a json formatted string of the NLMS parameters.
char * pred_nlms_param_json_import (struct XCSF *xcsf, cJSON *json)
Sets the NLMS parameters from a cJSON object.
Variables
static const int MU_TYPE [(1)]
Self-adaptation method for mutating NLMS predictions.
Detailed Description
Normalised least mean squares prediction functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2022.
Definition in file pred_nlms.c.
Macro Definition Documentation
N_MU
#define N_MU (1)
Number of self-adaptive mutation rates.
Definition at line 29 of file pred_nlms.c.
Function Documentation
pred_nlms_compute()
void pred_nlms_compute (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Computes the current NLMS prediction for a provided input.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier calculating the prediction.
[in] x The input state.
Definition at line 138 of file pred_nlms.c.
References blas_dot(), PredNLMS::n, Cl::pred, pred_transform_input(), Cl::prediction, PredNLMS::tmp_input, and PredNLMS::weights.
pred_nlms_copy()
void pred_nlms_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Copies an NLMS prediction from one classifier to another.
Parameters
[in] xcsf The XCSF data structure.
[in] dest The destination classifier.
[in] src The source classifier.
Definition at line 79 of file pred_nlms.c.
References PredNLMS::eta, PredNLMS::mu, N_MU, PredNLMS::n_weights, Cl::pred, pred_nlms_init(), and PredNLMS::weights.
pred_nlms_crossover()
bool pred_nlms_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Dummy function since NLMS predictions do not perform crossover.
Parameters
[in] xcsf The XCSF data structure.
[in] c1 The first classifier whose prediction is being crossed.
[in] c2 The second classifier whose prediction is being crossed.
Returns
False.
Definition at line 170 of file pred_nlms.c.
pred_nlms_free()
void pred_nlms_free (const struct XCSF * xcsf, const struct Cl * c)
Frees the memory used by an NLMS prediction.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is to be freed.
Definition at line 96 of file pred_nlms.c.
References PredNLMS::mu, Cl::pred, PredNLMS::tmp_input, and PredNLMS::weights.
pred_nlms_init()
void pred_nlms_init (const struct XCSF * xcsf, struct Cl * c)
Initialises an NLMS prediction.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is to be initialised.
Definition at line 44 of file pred_nlms.c.
References blas_fill(), PredNLMS::eta, PredNLMS::mu, MU_TYPE, PredNLMS::n, N_MU, PredNLMS::n_weights, Cl::pred, PRED_TYPE_NLMS_QUADRATIC, rand_uniform(), sam_init(), PredNLMS::tmp_input, and PredNLMS::weights.
Referenced by pred_nlms_copy(), and pred_nlms_load().
pred_nlms_json_export()
char* pred_nlms_json_export (const struct XCSF * xcsf, const struct Cl * c)
Returns a json formatted string representation of an NLMS prediction.
Parameters
[in] xcsf XCSF data structure.
[in] c Classifier whose prediction is to be returned.
Returns
String encoded in json format.
Definition at line 264 of file pred_nlms.c.
References PredNLMS::eta, PredNLMS::mu, N_MU, PredNLMS::n_weights, Cl::pred, PRED_TYPE_NLMS_QUADRATIC, and PredNLMS::weights.
Referenced by pred_nlms_print().
pred_nlms_json_import()
void pred_nlms_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json)
Creates an NLMS prediction from a cJSON object.
Parameters
[in] xcsf The XCSF data structure.
[in,out] c The classifier to initialise.
[in] json cJSON object.
Definition at line 290 of file pred_nlms.c.
References PredNLMS::eta, PredNLMS::mu, N_MU, PredNLMS::n_weights, Cl::pred, sam_json_import(), and PredNLMS::weights.
pred_nlms_load()
size_t pred_nlms_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Reads an NLMS prediction from a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is to be read.
[in] fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 244 of file pred_nlms.c.
References PredNLMS::eta, PredNLMS::mu, PredNLMS::n, N_MU, PredNLMS::n_weights, Cl::pred, pred_nlms_init(), and PredNLMS::weights.
pred_nlms_mutate()
bool pred_nlms_mutate (const struct XCSF * xcsf, const struct Cl * c)
Mutates the gradient descent rate used to update an NLMS prediction.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is being mutated.
Returns
Whether any alterations were made.
Definition at line 186 of file pred_nlms.c.
References clamp(), PredNLMS::eta, PredNLMS::mu, MU_TYPE, N_MU, Cl::pred, rand_normal(), and sam_adapt().
pred_nlms_param_json_export()
char* pred_nlms_param_json_export (const struct XCSF * xcsf)
Returns a json formatted string of the NLMS parameters.
Parameters
[in] xcsf The XCSF data structure.
Returns
String encoded in json format.
Definition at line 319 of file pred_nlms.c.
References ArgsPred::eta, ArgsPred::eta_min, ArgsPred::evolve_eta, and ArgsPred::x0.
Referenced by pred_param_json_export().
pred_nlms_param_json_import()
char* pred_nlms_param_json_import (struct XCSF * xcsf, cJSON * json)
Sets the NLMS parameters from a cJSON object.
Parameters
[in,out] xcsf The XCSF data structure.
[in] json cJSON object.
Returns
NULL if successful; or the name of parameter if not found.
Definition at line 341 of file pred_nlms.c.
References pred_param_set_eta(), pred_param_set_eta_min(), pred_param_set_evolve_eta(), and pred_param_set_x0().
Referenced by pred_param_json_import().
pred_nlms_print()
void pred_nlms_print (const struct XCSF * xcsf, const struct Cl * c)
Prints an NLMS prediction.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is to be printed.
Definition at line 155 of file pred_nlms.c.
References pred_nlms_json_export().
pred_nlms_save()
size_t pred_nlms_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Writes an NLMS prediction to a file.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction is to be written.
[in] fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 223 of file pred_nlms.c.
References PredNLMS::eta, PredNLMS::mu, PredNLMS::n, N_MU, PredNLMS::n_weights, Cl::pred, and PredNLMS::weights.
pred_nlms_size()
double pred_nlms_size (const struct XCSF * xcsf, const struct Cl * c)
Returns the size of an NLMS prediction.
Parameters
[in] xcsf The XCSF data structure.
[in] c The classifier whose prediction size to return.
Returns
The number of weights.
Definition at line 208 of file pred_nlms.c.
References PredNLMS::n_weights, and Cl::pred.
pred_nlms_update()
void pred_nlms_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Updates an NLMS prediction for a given input and truth sample.
Precondition
The prediction has been computed for the current state.
Parameters
[in] xcsf The XCSF data structure.
[in] c Classifier whose prediction is to be updated.
[in] x Input state.
[in] y Truth/payoff value.
Definition at line 115 of file pred_nlms.c.
References blas_axpy(), blas_dot(), PredNLMS::eta, PredNLMS::n, Cl::pred, Cl::prediction, PredNLMS::tmp_input, and PredNLMS::weights.
Variable Documentation
MU_TYPE
const int MU_TYPE[(1)] static
Initial value:
= {
     (0)
}
Self-adaptation method for mutating NLMS predictions.
Definition at line 34 of file pred_nlms.c.
Referenced by pred_nlms_init(), and pred_nlms_mutate().