XCSF: pybind_wrapper.cpp File Reference
pybind_wrapper.cpp File Reference
Python library wrapper functions.
#include "../lib/pybind11/include/pybind11/numpy.h"
#include "../lib/pybind11/include/pybind11/pybind11.h"
#include "action.h"
#include "clset.h"
#include "clset_neural.h"
#include "condition.h"
#include "config.h"
#include "dgp.h"
#include "ea.h"
#include "gp.h"
#include "neural_activations.h"
#include "neural_layer.h"
#include "pa.h"
#include "param.h"
#include "prediction.h"
#include "utils.h"
#include "xcs_rl.h"
#include "xcs_supervised.h"
Data Structures
class XCS
Python XCSF class data structure.
Functions
::pybind11::module_::module_def pybind11_module_def_xcsf __attribute__ ((__unused__))
static PYBIND11_MAYBE_UNUSED void pybind11_init_xcsf (::pybind11::module_ &)
static PyObject * pybind11_init_wrapper ()
C PYBIND11_MAYBE_UNUSED __attribute__ ((visibility("default"))) void initxcsf()
C PYBIND11_EXPORT void initxcsf ()
void PYBIND11_CONCAT (pybind11_init_, xcsf)(
Detailed Description
Python library wrapper functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
David Pätzel
Copyright
The Authors.
Date
2020–2021.
Definition in file pybind_wrapper.cpp.
Function Documentation
__attribute__() [1/2]
::pybind11::module_::module_def pybind11_module_def_xcsf __attribute__ ((__unused__)) static
__attribute__() [2/2]
C PYBIND11_MAYBE_UNUSED __attribute__ ((visibility("default")))
initxcsf()
C PYBIND11_EXPORT void initxcsf ()
Definition at line 1384 of file pybind_wrapper.cpp.
PYBIND11_CONCAT()
void PYBIND11_CONCAT (pybind11_init_ , xcsf)
Definition at line 1384 of file pybind_wrapper.cpp.
pybind11_init_wrapper()
PyObject * pybind11_init_wrapper () static
Definition at line 1384 of file pybind_wrapper.cpp.
References XCS::ae_to_classifier(), XCS::decision(), XCS::end_step(), XCS::end_trial(), XCS::error(), XCS::fit(), XCS::get_alpha(), XCS::get_aset_size(), XCS::get_beta(), XCS::get_compaction(), XCS::get_delta(), XCS::get_e0(), XCS::get_ea_pred_reset(), XCS::get_ea_select_size(), XCS::get_ea_select_type(), XCS::get_ea_subsumption(), XCS::get_err_reduc(), XCS::get_fit_reduc(), XCS::get_gamma(), XCS::get_huber_delta(), XCS::get_init_error(), XCS::get_init_fitness(), XCS::get_lambda(), XCS::get_loss_func(), XCS::get_m_probation(), XCS::get_max_trials(), XCS::get_mfrac(), XCS::get_mset_size(), XCS::get_n_actions(), XCS::get_nu(), XCS::get_omp_num_threads(), XCS::get_p_crossover(), XCS::get_p_explore(), XCS::get_perf_trials(), XCS::get_pop_init(), XCS::get_pop_max_size(), XCS::get_pset_mean_cond_connections(), XCS::get_pset_mean_cond_layers(), XCS::get_pset_mean_cond_neurons(), XCS::get_pset_mean_cond_size(), XCS::get_pset_mean_pred_connections(), XCS::get_pset_mean_pred_eta(), XCS::get_pset_mean_pred_layers(), XCS::get_pset_mean_pred_neurons(), XCS::get_pset_mean_pred_size(), XCS::get_pset_num(), XCS::get_pset_size(), XCS::get_set_subsumption(), XCS::get_stateful(), XCS::get_teletransportation(), XCS::get_theta_del(), XCS::get_theta_ea(), XCS::get_theta_sub(), XCS::get_time(), XCS::get_x_dim(), XCS::get_y_dim(), XCS::init_step(), XCS::init_trial(), XCS::load(), XCS::pred_expand(), XCS::predict(), XCS::print_params(), XCS::print_pset(), rand_init(), XCS::retrieve(), XCS::save(), XCS::score(), XCS::seed(), XCS::set_action(), XCS::set_alpha(), XCS::set_beta(), XCS::set_compaction(), XCS::set_condition(), XCS::set_delta(), XCS::set_e0(), XCS::set_ea_pred_reset(), XCS::set_ea_select_size(), XCS::set_ea_select_type(), XCS::set_ea_subsumption(), XCS::set_err_reduc(), XCS::set_fit_reduc(), XCS::set_gamma(), XCS::set_huber_delta(), XCS::set_init_error(), XCS::set_init_fitness(), XCS::set_lambda(), XCS::set_loss_func(), XCS::set_m_probation(), XCS::set_max_trials(), XCS::set_nu(), XCS::set_omp_num_threads(), XCS::set_p_crossover(), XCS::set_p_explore(), XCS::set_perf_trials(), XCS::set_pop_init(), XCS::set_pop_max_size(), XCS::set_prediction(), XCS::set_set_subsumption(), XCS::set_stateful(), XCS::set_teletransportation(), XCS::set_theta_del(), XCS::set_theta_ea(), XCS::set_theta_sub(), XCS::store(), XCS::update(), XCS::version_build(), XCS::version_major(), and XCS::version_minor().
pybind11_init_xcsf()
static PYBIND11_MAYBE_UNUSED void pybind11_init_xcsf (::pybind11::module_ &) static