XCSF: rule_neural.h File Reference
rule_neural.h File Reference
Neural network rule (condition + action) functions.
#include "action.h"
#include "condition.h"
#include "neural.h"
#include "xcsf.h"
Data Structures
struct RuleNeural
Neural network rule data structure.
Functions
bool rule_neural_cond_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool rule_neural_cond_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool rule_neural_cond_match (const struct XCSF *xcsf, const struct Cl *c, const double *x)
bool rule_neural_cond_mutate (const struct XCSF *xcsf, const struct Cl *c)
void rule_neural_cond_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
void rule_neural_cond_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x)
void rule_neural_cond_free (const struct XCSF *xcsf, const struct Cl *c)
void rule_neural_cond_init (const struct XCSF *xcsf, struct Cl *c)
void rule_neural_cond_print (const struct XCSF *xcsf, const struct Cl *c)
void rule_neural_cond_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
double rule_neural_cond_size (const struct XCSF *xcsf, const struct Cl *c)
size_t rule_neural_cond_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
size_t rule_neural_cond_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
char * rule_neural_cond_json_export (const struct XCSF *xcsf, const struct Cl *c)
void rule_neural_cond_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
bool rule_neural_act_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool rule_neural_act_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool rule_neural_act_mutate (const struct XCSF *xcsf, const struct Cl *c)
int rule_neural_act_compute (const struct XCSF *xcsf, const struct Cl *c, const double *x)
void rule_neural_act_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
void rule_neural_act_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x, const int action)
void rule_neural_act_free (const struct XCSF *xcsf, const struct Cl *c)
void rule_neural_act_init (const struct XCSF *xcsf, struct Cl *c)
void rule_neural_act_print (const struct XCSF *xcsf, const struct Cl *c)
void rule_neural_act_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
size_t rule_neural_act_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
size_t rule_neural_act_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
char * rule_neural_act_json_export (const struct XCSF *xcsf, const struct Cl *c)
void rule_neural_act_json_import (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Variables
static struct CondVtbl const rule_neural_cond_vtbl
Neural network rule condition implemented functions.
static struct ActVtbl const rule_neural_act_vtbl
Neural network rule action implemented functions.
Detailed Description
Neural network rule (condition + action) functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2021.
Definition in file rule_neural.h.
Function Documentation
rule_neural_act_compute()
int rule_neural_act_compute (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Definition at line 236 of file rule_neural.c.
References clamp_int(), Cl::cond, Net::n_outputs, RuleNeural::net, and neural_output().
Referenced by rule_neural_act_cover().
rule_neural_act_copy()
void rule_neural_act_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Definition at line 208 of file rule_neural.c.
rule_neural_act_cover()
void rule_neural_act_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x, const int action)
Definition at line 225 of file rule_neural.c.
References Cl::cond, RuleNeural::net, neural_rand(), rule_neural_act_compute(), and rule_neural_cond_match().
rule_neural_act_crossover()
bool rule_neural_act_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Definition at line 263 of file rule_neural.c.
rule_neural_act_free()
void rule_neural_act_free (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 201 of file rule_neural.c.
rule_neural_act_general()
bool rule_neural_act_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Definition at line 273 of file rule_neural.c.
rule_neural_act_init()
void rule_neural_act_init (const struct XCSF * xcsf, struct Cl * c)
Definition at line 194 of file rule_neural.c.
rule_neural_act_json_export()
char* rule_neural_act_json_export (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 309 of file rule_neural.c.
Referenced by rule_neural_act_print().
rule_neural_act_json_import()
void rule_neural_act_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json)
Definition at line 321 of file rule_neural.c.
rule_neural_act_load()
size_t rule_neural_act_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Definition at line 300 of file rule_neural.c.
rule_neural_act_mutate()
bool rule_neural_act_mutate (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 283 of file rule_neural.c.
rule_neural_act_print()
void rule_neural_act_print (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 217 of file rule_neural.c.
References rule_neural_act_json_export().
rule_neural_act_save()
size_t rule_neural_act_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Definition at line 291 of file rule_neural.c.
rule_neural_act_update()
void rule_neural_act_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Definition at line 253 of file rule_neural.c.
rule_neural_cond_copy()
void rule_neural_cond_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Definition at line 59 of file rule_neural.c.
References Cl::cond, RuleNeural::net, and neural_copy().
rule_neural_cond_cover()
void rule_neural_cond_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Definition at line 70 of file rule_neural.c.
rule_neural_cond_crossover()
bool rule_neural_cond_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Definition at line 109 of file rule_neural.c.
rule_neural_cond_free()
void rule_neural_cond_free (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 50 of file rule_neural.c.
References Cl::cond, RuleNeural::net, and neural_free().
rule_neural_cond_general()
bool rule_neural_cond_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Definition at line 119 of file rule_neural.c.
rule_neural_cond_init()
void rule_neural_cond_init (const struct XCSF * xcsf, struct Cl * c)
Definition at line 35 of file rule_neural.c.
References Cl::cond, and neural_create().
rule_neural_cond_json_export()
char* rule_neural_cond_json_export (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 164 of file rule_neural.c.
References Cl::cond, RuleNeural::net, and neural_json_export().
Referenced by rule_neural_cond_print().
rule_neural_cond_json_import()
void rule_neural_cond_json_import (const struct XCSF * xcsf, struct Cl * c, const cJSON * json)
Definition at line 179 of file rule_neural.c.
References Cl::cond, RuleNeural::net, and neural_json_import().
rule_neural_cond_load()
size_t rule_neural_cond_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Definition at line 154 of file rule_neural.c.
References Cl::cond, and neural_load().
rule_neural_cond_match()
bool rule_neural_cond_match (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Definition at line 89 of file rule_neural.c.
References Cl::cond, RuleNeural::net, neural_output(), and neural_propagate().
Referenced by rule_neural_act_cover().
rule_neural_cond_mutate()
bool rule_neural_cond_mutate (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 101 of file rule_neural.c.
References Cl::cond, RuleNeural::net, and neural_mutate().
rule_neural_cond_print()
void rule_neural_cond_print (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 129 of file rule_neural.c.
References rule_neural_cond_json_export().
rule_neural_cond_save()
size_t rule_neural_cond_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Definition at line 145 of file rule_neural.c.
References Cl::cond, RuleNeural::net, and neural_save().
rule_neural_cond_size()
double rule_neural_cond_size (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 137 of file rule_neural.c.
References Cl::cond, RuleNeural::net, and neural_size().
rule_neural_cond_update()
void rule_neural_cond_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Definition at line 79 of file rule_neural.c.
Variable Documentation
rule_neural_act_vtbl
struct ActVtbl const rule_neural_act_vtbl static
Initial value:
= {
    &rule_neural_act_general,     &rule_neural_act_crossover,
    &rule_neural_act_mutate,      &rule_neural_act_compute,
    &rule_neural_act_copy,        &rule_neural_act_cover,
    &rule_neural_act_free,        &rule_neural_act_init,
    &rule_neural_act_print,       &rule_neural_act_update,
    &rule_neural_act_save,        &rule_neural_act_load,
    &rule_neural_act_json_export, &rule_neural_act_json_import
}
Neural network rule action implemented functions.
Definition at line 150 of file rule_neural.h.
Referenced by condition_set().
rule_neural_cond_vtbl
struct CondVtbl const rule_neural_cond_vtbl static
Initial value:
= {
    &rule_neural_cond_crossover,  &rule_neural_cond_general,
    &rule_neural_cond_match,      &rule_neural_cond_mutate,
    &rule_neural_cond_copy,       &rule_neural_cond_cover,
    &rule_neural_cond_free,       &rule_neural_cond_init,
    &rule_neural_cond_print,      &rule_neural_cond_update,
    &rule_neural_cond_size,       &rule_neural_cond_save,
    &rule_neural_cond_load,       &rule_neural_cond_json_export,
    &rule_neural_cond_json_import
}
Neural network rule condition implemented functions.
Definition at line 87 of file rule_neural.h.
Referenced by condition_set().