XCSF: rule_dgp.h File Reference
rule_dgp.h File Reference
Dynamical GP graph rule (condition + action) functions.
#include "action.h"
#include "condition.h"
#include "dgp.h"
#include "xcsf.h"
Data Structures
struct RuleDGP
Dynamical GP graph rule data structure.
Functions
bool rule_dgp_cond_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool rule_dgp_cond_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool rule_dgp_cond_match (const struct XCSF *xcsf, const struct Cl *c, const double *x)
bool rule_dgp_cond_mutate (const struct XCSF *xcsf, const struct Cl *c)
void rule_dgp_cond_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
void rule_dgp_cond_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x)
void rule_dgp_cond_free (const struct XCSF *xcsf, const struct Cl *c)
void rule_dgp_cond_init (const struct XCSF *xcsf, struct Cl *c)
void rule_dgp_cond_print (const struct XCSF *xcsf, const struct Cl *c)
void rule_dgp_cond_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
double rule_dgp_cond_size (const struct XCSF *xcsf, const struct Cl *c)
size_t rule_dgp_cond_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
size_t rule_dgp_cond_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
const char * rule_dgp_cond_json_export (const struct XCSF *xcsf, const struct Cl *c)
bool rule_dgp_act_crossover (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool rule_dgp_act_general (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool rule_dgp_act_mutate (const struct XCSF *xcsf, const struct Cl *c)
int rule_dgp_act_compute (const struct XCSF *xcsf, const struct Cl *c, const double *x)
void rule_dgp_act_copy (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
void rule_dgp_act_cover (const struct XCSF *xcsf, const struct Cl *c, const double *x, const int action)
void rule_dgp_act_free (const struct XCSF *xcsf, const struct Cl *c)
void rule_dgp_act_init (const struct XCSF *xcsf, struct Cl *c)
void rule_dgp_act_print (const struct XCSF *xcsf, const struct Cl *c)
void rule_dgp_act_update (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
size_t rule_dgp_act_save (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
size_t rule_dgp_act_load (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
const char * rule_dgp_act_json_export (const struct XCSF *xcsf, const struct Cl *c)
Variables
static struct CondVtbl const rule_dgp_cond_vtbl
Dynamical GP rule condition implemented functions.
static struct ActVtbl const rule_dgp_act_vtbl
Dynamical GP rule action implemented functions.
Detailed Description
Dynamical GP graph rule (condition + action) functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2021.
Definition in file rule_dgp.h.
Function Documentation
rule_dgp_act_compute()
int rule_dgp_act_compute (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Definition at line 209 of file rule_dgp.c.
References clamp_int(), Cl::cond, RuleDGP::dgp, graph_output(), XCSF::n_actions, and RuleDGP::n_outputs.
Referenced by rule_dgp_act_cover().
rule_dgp_act_copy()
void rule_dgp_act_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Definition at line 183 of file rule_dgp.c.
rule_dgp_act_cover()
void rule_dgp_act_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x, const int action)
Definition at line 198 of file rule_dgp.c.
References Cl::cond, RuleDGP::dgp, graph_rand(), rule_dgp_act_compute(), and rule_dgp_cond_match().
rule_dgp_act_crossover()
bool rule_dgp_act_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Definition at line 236 of file rule_dgp.c.
rule_dgp_act_free()
void rule_dgp_act_free (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 176 of file rule_dgp.c.
rule_dgp_act_general()
bool rule_dgp_act_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Definition at line 246 of file rule_dgp.c.
rule_dgp_act_init()
void rule_dgp_act_init (const struct XCSF * xcsf, struct Cl * c)
Definition at line 169 of file rule_dgp.c.
rule_dgp_act_json_export()
const char* rule_dgp_act_json_export (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 282 of file rule_dgp.c.
Referenced by rule_dgp_act_print().
rule_dgp_act_load()
size_t rule_dgp_act_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Definition at line 273 of file rule_dgp.c.
rule_dgp_act_mutate()
bool rule_dgp_act_mutate (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 256 of file rule_dgp.c.
rule_dgp_act_print()
void rule_dgp_act_print (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 192 of file rule_dgp.c.
References rule_dgp_act_json_export().
rule_dgp_act_save()
size_t rule_dgp_act_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Definition at line 264 of file rule_dgp.c.
rule_dgp_act_update()
void rule_dgp_act_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Definition at line 226 of file rule_dgp.c.
rule_dgp_cond_copy()
void rule_dgp_cond_copy (const struct XCSF * xcsf, struct Cl * dest, const struct Cl * src)
Definition at line 49 of file rule_dgp.c.
References Cl::cond, XCSF::cond, ArgsCond::dargs, RuleDGP::dgp, graph_copy(), graph_init(), and RuleDGP::n_outputs.
rule_dgp_cond_cover()
void rule_dgp_cond_cover (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Definition at line 61 of file rule_dgp.c.
rule_dgp_cond_crossover()
bool rule_dgp_cond_crossover (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Definition at line 100 of file rule_dgp.c.
rule_dgp_cond_free()
void rule_dgp_cond_free (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 40 of file rule_dgp.c.
References Cl::cond, RuleDGP::dgp, and graph_free().
rule_dgp_cond_general()
bool rule_dgp_cond_general (const struct XCSF * xcsf, const struct Cl * c1, const struct Cl * c2)
Definition at line 110 of file rule_dgp.c.
rule_dgp_cond_init()
void rule_dgp_cond_init (const struct XCSF * xcsf, struct Cl * c)
Definition at line 30 of file rule_dgp.c.
References Cl::cond, XCSF::cond, ArgsCond::dargs, graph_init(), graph_rand(), and XCSF::n_actions.
rule_dgp_cond_json_export()
const char* rule_dgp_cond_json_export (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 153 of file rule_dgp.c.
References Cl::cond, RuleDGP::dgp, and graph_json_export().
Referenced by rule_dgp_cond_print().
rule_dgp_cond_load()
size_t rule_dgp_cond_load (const struct XCSF * xcsf, struct Cl * c, FILE * fp)
Definition at line 143 of file rule_dgp.c.
References Cl::cond, graph_load(), and XCSF::n_actions.
rule_dgp_cond_match()
bool rule_dgp_cond_match (const struct XCSF * xcsf, const struct Cl * c, const double * x)
Definition at line 80 of file rule_dgp.c.
References Cl::cond, RuleDGP::dgp, graph_output(), graph_update(), and XCSF::STATEFUL.
Referenced by rule_dgp_act_cover().
rule_dgp_cond_mutate()
bool rule_dgp_cond_mutate (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 92 of file rule_dgp.c.
References Cl::cond, RuleDGP::dgp, and graph_mutate().
rule_dgp_cond_print()
void rule_dgp_cond_print (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 120 of file rule_dgp.c.
References rule_dgp_cond_json_export().
rule_dgp_cond_save()
size_t rule_dgp_cond_save (const struct XCSF * xcsf, const struct Cl * c, FILE * fp)
Definition at line 134 of file rule_dgp.c.
References Cl::cond, RuleDGP::dgp, and graph_save().
rule_dgp_cond_size()
double rule_dgp_cond_size (const struct XCSF * xcsf, const struct Cl * c)
Definition at line 126 of file rule_dgp.c.
References Cl::cond, RuleDGP::dgp, and Graph::n.
rule_dgp_cond_update()
void rule_dgp_cond_update (const struct XCSF * xcsf, const struct Cl * c, const double * x, const double * y)
Definition at line 70 of file rule_dgp.c.
Variable Documentation
rule_dgp_act_vtbl
struct ActVtbl const rule_dgp_act_vtbl static
Initial value:
= {
    &rule_dgp_act_general,    &rule_dgp_act_crossover, &rule_dgp_act_mutate,
    &rule_dgp_act_compute,    &rule_dgp_act_copy,      &rule_dgp_act_cover,
    &rule_dgp_act_free,       &rule_dgp_act_init,      &rule_dgp_act_print,
    &rule_dgp_act_update,     &rule_dgp_act_save,      &rule_dgp_act_load,
    &rule_dgp_act_json_export
}
Dynamical GP rule action implemented functions.
Definition at line 146 of file rule_dgp.h.
Referenced by condition_set().
rule_dgp_cond_vtbl
struct CondVtbl const rule_dgp_cond_vtbl static
Initial value:
= {
    &rule_dgp_cond_crossover, &rule_dgp_cond_general,    &rule_dgp_cond_match,
    &rule_dgp_cond_mutate,    &rule_dgp_cond_copy,       &rule_dgp_cond_cover,
    &rule_dgp_cond_free,      &rule_dgp_cond_init,       &rule_dgp_cond_print,
    &rule_dgp_cond_update,    &rule_dgp_cond_size,       &rule_dgp_cond_save,
    &rule_dgp_cond_load,      &rule_dgp_cond_json_export
}
Dynamical GP rule condition implemented functions.
Definition at line 90 of file rule_dgp.h.
Referenced by condition_set().