XCSF: LayerVtbl Struct Reference
LayerVtbl Struct Reference
Neural network layer interface data structure.
#include <neural_layer.h>
Data Fields
void(* layer_impl_init)(struct Layer *l, const struct ArgsLayer *args)
bool(* layer_impl_mutate)(struct Layer *l)
void(* layer_impl_resize)(struct Layer *l, const struct Layer *prev)
struct Layer *(* layer_impl_copy)(const struct Layer *src)
void(* layer_impl_free)(const struct Layer *l)
void(* layer_impl_rand)(struct Layer *l)
void(* layer_impl_print)(const struct Layer *l, const bool print_weights)
void(* layer_impl_update)(const struct Layer *l)
void(* layer_impl_backward)(const struct Layer *l, const struct Net *net, const double *input, double *delta)
void(* layer_impl_forward)(const struct Layer *l, const struct Net *net, const double *input)
double *(* layer_impl_output)(const struct Layer *l)
size_t(* layer_impl_save)(const struct Layer *l, FILE *fp)
size_t(* layer_impl_load)(struct Layer *l, FILE *fp)
char *(* layer_impl_json_export)(const struct Layer *l, const bool return_weights)
Detailed Description
Neural network layer interface data structure.
Neural network layer implementations must implement these functions.
Definition at line 143 of file neural_layer.h.
Field Documentation
layer_impl_backward
void(* LayerVtbl::layer_impl_backward) (const struct Layer *l, const struct Net *net, const double *input, double *delta)
Definition at line 152 of file neural_layer.h.
Referenced by layer_backward().
layer_impl_copy
struct Layer *(* LayerVtbl::layer_impl_copy) (const struct Layer *src)
Definition at line 146 of file neural_layer.h.
Referenced by layer_copy().
layer_impl_forward
void(* LayerVtbl::layer_impl_forward) (const struct Layer *l, const struct Net *net, const double *input)
Definition at line 154 of file neural_layer.h.
Referenced by layer_forward().
layer_impl_free
void(* LayerVtbl::layer_impl_free) (const struct Layer *l)
Definition at line 148 of file neural_layer.h.
Referenced by layer_free().
layer_impl_init
void(* LayerVtbl::layer_impl_init) (struct Layer *l, const struct ArgsLayer *args)
Definition at line 144 of file neural_layer.h.
Referenced by layer_init().
layer_impl_json_export
char *(* LayerVtbl::layer_impl_json_export) (const struct Layer *l, const bool return_weights)
Definition at line 159 of file neural_layer.h.
Referenced by layer_json_export().
layer_impl_load
size_t(* LayerVtbl::layer_impl_load) (struct Layer *l, FILE *fp)
Definition at line 158 of file neural_layer.h.
Referenced by layer_load().
layer_impl_mutate
bool(* LayerVtbl::layer_impl_mutate) (struct Layer *l)
Definition at line 145 of file neural_layer.h.
Referenced by layer_mutate().
layer_impl_output
double *(* LayerVtbl::layer_impl_output) (const struct Layer *l)
Definition at line 156 of file neural_layer.h.
Referenced by layer_output().
layer_impl_print
void(* LayerVtbl::layer_impl_print) (const struct Layer *l, const bool print_weights)
Definition at line 150 of file neural_layer.h.
Referenced by layer_print().
layer_impl_rand
void(* LayerVtbl::layer_impl_rand) (struct Layer *l)
Definition at line 149 of file neural_layer.h.
Referenced by layer_rand().
layer_impl_resize
void(* LayerVtbl::layer_impl_resize) (struct Layer *l, const struct Layer *prev)
Definition at line 146 of file neural_layer.h.
Referenced by layer_resize().
layer_impl_save
size_t(* LayerVtbl::layer_impl_save) (const struct Layer *l, FILE *fp)
Definition at line 157 of file neural_layer.h.
Referenced by layer_save().
layer_impl_update
void(* LayerVtbl::layer_impl_update) (const struct Layer *l)
Definition at line 151 of file neural_layer.h.
Referenced by layer_update().
The documentation for this struct was generated from the following file:
neural_layer.h