XCSF: ActVtbl Struct Reference
ActVtbl Struct Reference
Action interface data structure.
#include <action.h>
Data Fields
bool(* act_impl_general)(const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool(* act_impl_crossover)(const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool(* act_impl_mutate)(const struct XCSF *xcsf, const struct Cl *c)
int(* act_impl_compute)(const struct XCSF *xcsf, const struct Cl *c, const double *x)
void(* act_impl_copy)(const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
void(* act_impl_cover)(const struct XCSF *xcsf, const struct Cl *c, const double *x, const int action)
void(* act_impl_free)(const struct XCSF *xcsf, const struct Cl *c)
void(* act_impl_init)(const struct XCSF *xcsf, struct Cl *c)
void(* act_impl_print)(const struct XCSF *xcsf, const struct Cl *c)
void(* act_impl_update)(const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
size_t(* act_impl_save)(const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
size_t(* act_impl_load)(const struct XCSF *xcsf, struct Cl *c, FILE *fp)
char *(* act_impl_json_export)(const struct XCSF *xcsf, const struct Cl *c)
Detailed Description
Action interface data structure.
Action implementations must implement these functions.
Definition at line 73 of file action.h.
Field Documentation
act_impl_compute
int(* ActVtbl::act_impl_compute) (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Definition at line 79 of file action.h.
Referenced by act_compute().
act_impl_copy
void(* ActVtbl::act_impl_copy) (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Definition at line 81 of file action.h.
Referenced by act_copy().
act_impl_cover
void(* ActVtbl::act_impl_cover) (const struct XCSF *xcsf, const struct Cl *c, const double *x, const int action)
Definition at line 83 of file action.h.
Referenced by act_cover().
act_impl_crossover
bool(* ActVtbl::act_impl_crossover) (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Definition at line 76 of file action.h.
Referenced by act_crossover().
act_impl_free
void(* ActVtbl::act_impl_free) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 85 of file action.h.
Referenced by act_free().
act_impl_general
bool(* ActVtbl::act_impl_general) (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Definition at line 74 of file action.h.
Referenced by act_general().
act_impl_init
void(* ActVtbl::act_impl_init) (const struct XCSF *xcsf, struct Cl *c)
Definition at line 86 of file action.h.
Referenced by act_init().
act_impl_json_export
char*(* ActVtbl::act_impl_json_export) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 93 of file action.h.
Referenced by act_json_export().
act_impl_load
size_t(* ActVtbl::act_impl_load) (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Definition at line 92 of file action.h.
Referenced by act_load().
act_impl_mutate
bool(* ActVtbl::act_impl_mutate) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 78 of file action.h.
Referenced by act_mutate().
act_impl_print
void(* ActVtbl::act_impl_print) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 87 of file action.h.
Referenced by act_print().
act_impl_save
size_t(* ActVtbl::act_impl_save) (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Definition at line 90 of file action.h.
Referenced by act_save().
act_impl_update
void(* ActVtbl::act_impl_update) (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Definition at line 88 of file action.h.
Referenced by act_update().
The documentation for this struct was generated from the following file:
action.h