XCSF: PredVtbl Struct Reference
PredVtbl Struct Reference
Prediction interface data structure.
#include <prediction.h>
Data Fields
bool(* pred_impl_crossover)(const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool(* pred_impl_mutate)(const struct XCSF *xcsf, const struct Cl *c)
void(* pred_impl_compute)(const struct XCSF *xcsf, const struct Cl *c, const double *x)
void(* pred_impl_copy)(const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
void(* pred_impl_free)(const struct XCSF *xcsf, const struct Cl *c)
void(* pred_impl_init)(const struct XCSF *xcsf, struct Cl *c)
void(* pred_impl_print)(const struct XCSF *xcsf, const struct Cl *c)
void(* pred_impl_update)(const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
double(* pred_impl_size)(const struct XCSF *xcsf, const struct Cl *c)
size_t(* pred_impl_save)(const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
size_t(* pred_impl_load)(const struct XCSF *xcsf, struct Cl *c, FILE *fp)
char *(* pred_impl_json_export)(const struct XCSF *xcsf, const struct Cl *c)
void(* pred_impl_json_import)(const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Detailed Description
Prediction interface data structure.
Prediction implementations must implement these functions.
Definition at line 91 of file prediction.h.
Field Documentation
pred_impl_compute
void(* PredVtbl::pred_impl_compute) (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Definition at line 95 of file prediction.h.
Referenced by pred_compute().
pred_impl_copy
void(* PredVtbl::pred_impl_copy) (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Definition at line 97 of file prediction.h.
Referenced by pred_copy().
pred_impl_crossover
bool(* PredVtbl::pred_impl_crossover) (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Definition at line 92 of file prediction.h.
Referenced by pred_crossover().
pred_impl_free
void(* PredVtbl::pred_impl_free) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 99 of file prediction.h.
Referenced by pred_free().
pred_impl_init
void(* PredVtbl::pred_impl_init) (const struct XCSF *xcsf, struct Cl *c)
Definition at line 100 of file prediction.h.
Referenced by pred_init().
pred_impl_json_export
char*(* PredVtbl::pred_impl_json_export) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 108 of file prediction.h.
Referenced by pred_json_export().
pred_impl_json_import
void(* PredVtbl::pred_impl_json_import) (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Definition at line 109 of file prediction.h.
Referenced by pred_json_import().
pred_impl_load
size_t(* PredVtbl::pred_impl_load) (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Definition at line 107 of file prediction.h.
Referenced by pred_load().
pred_impl_mutate
bool(* PredVtbl::pred_impl_mutate) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 94 of file prediction.h.
Referenced by pred_mutate().
pred_impl_print
void(* PredVtbl::pred_impl_print) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 101 of file prediction.h.
Referenced by pred_print().
pred_impl_save
size_t(* PredVtbl::pred_impl_save) (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Definition at line 105 of file prediction.h.
Referenced by pred_save().
pred_impl_size
double(* PredVtbl::pred_impl_size) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 104 of file prediction.h.
Referenced by pred_size().
pred_impl_update
void(* PredVtbl::pred_impl_update) (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Definition at line 102 of file prediction.h.
Referenced by pred_update().
The documentation for this struct was generated from the following file:
prediction.h