XCSF: CondVtbl Struct Reference
CondVtbl Struct Reference
Condition interface data structure.
#include <condition.h>
Data Fields
bool(* cond_impl_crossover)(const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool(* cond_impl_general)(const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
bool(* cond_impl_match)(const struct XCSF *xcsf, const struct Cl *c, const double *x)
bool(* cond_impl_mutate)(const struct XCSF *xcsf, const struct Cl *c)
void(* cond_impl_copy)(const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
void(* cond_impl_cover)(const struct XCSF *xcsf, const struct Cl *c, const double *x)
void(* cond_impl_free)(const struct XCSF *xcsf, const struct Cl *c)
void(* cond_impl_init)(const struct XCSF *xcsf, struct Cl *c)
void(* cond_impl_print)(const struct XCSF *xcsf, const struct Cl *c)
void(* cond_impl_update)(const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
double(* cond_impl_size)(const struct XCSF *xcsf, const struct Cl *c)
size_t(* cond_impl_save)(const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
size_t(* cond_impl_load)(const struct XCSF *xcsf, struct Cl *c, FILE *fp)
char *(* cond_impl_json_export)(const struct XCSF *xcsf, const struct Cl *c)
void(* cond_impl_json_import)(const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Detailed Description
Condition interface data structure.
Condition implementations must implement these functions.
Definition at line 99 of file condition.h.
Field Documentation
cond_impl_copy
void(* CondVtbl::cond_impl_copy) (const struct XCSF *xcsf, struct Cl *dest, const struct Cl *src)
Definition at line 107 of file condition.h.
Referenced by cond_copy().
cond_impl_cover
void(* CondVtbl::cond_impl_cover) (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Definition at line 109 of file condition.h.
Referenced by cond_cover().
cond_impl_crossover
bool(* CondVtbl::cond_impl_crossover) (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Definition at line 100 of file condition.h.
Referenced by cond_crossover().
cond_impl_free
void(* CondVtbl::cond_impl_free) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 111 of file condition.h.
Referenced by cond_free().
cond_impl_general
bool(* CondVtbl::cond_impl_general) (const struct XCSF *xcsf, const struct Cl *c1, const struct Cl *c2)
Definition at line 102 of file condition.h.
Referenced by cond_general().
cond_impl_init
void(* CondVtbl::cond_impl_init) (const struct XCSF *xcsf, struct Cl *c)
Definition at line 112 of file condition.h.
Referenced by cond_init().
cond_impl_json_export
char*(* CondVtbl::cond_impl_json_export) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 120 of file condition.h.
Referenced by cond_json_export().
cond_impl_json_import
void(* CondVtbl::cond_impl_json_import) (const struct XCSF *xcsf, struct Cl *c, const cJSON *json)
Definition at line 121 of file condition.h.
Referenced by cond_json_import().
cond_impl_load
size_t(* CondVtbl::cond_impl_load) (const struct XCSF *xcsf, struct Cl *c, FILE *fp)
Definition at line 119 of file condition.h.
Referenced by cond_load().
cond_impl_match
bool(* CondVtbl::cond_impl_match) (const struct XCSF *xcsf, const struct Cl *c, const double *x)
Definition at line 104 of file condition.h.
Referenced by cond_match().
cond_impl_mutate
bool(* CondVtbl::cond_impl_mutate) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 106 of file condition.h.
Referenced by cond_mutate().
cond_impl_print
void(* CondVtbl::cond_impl_print) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 113 of file condition.h.
Referenced by cond_print().
cond_impl_save
size_t(* CondVtbl::cond_impl_save) (const struct XCSF *xcsf, const struct Cl *c, FILE *fp)
Definition at line 117 of file condition.h.
Referenced by cond_save().
cond_impl_size
double(* CondVtbl::cond_impl_size) (const struct XCSF *xcsf, const struct Cl *c)
Definition at line 116 of file condition.h.
Referenced by cond_size().
cond_impl_update
void(* CondVtbl::cond_impl_update) (const struct XCSF *xcsf, const struct Cl *c, const double *x, const double *y)
Definition at line 114 of file condition.h.
Referenced by cond_update().
The documentation for this struct was generated from the following file:
condition.h