XCSF: xcs_supervised.h File Reference
xcs_supervised.h File Reference
Supervised regression learning functions.
#include "xcsf.h"
Functions
double xcs_supervised_fit (struct XCSF *xcsf, const struct Input *train_data, const struct Input *test_data, const bool shuffle, const int trials)
Executes MAX_TRIALS number of XCSF learning iterations using the training data and test iterations using the test data.
double xcs_supervised_score (struct XCSF *xcsf, const struct Input *data, const double *cover)
Calculates the XCSF error for the input data.
double xcs_supervised_score_n (struct XCSF *xcsf, const struct Input *data, const int N, const double *cover)
Calculates the XCSF error for a subsample of the input data.
void xcs_supervised_predict (struct XCSF *xcsf, const double *x, double *pred, const int n_samples, const double *cover)
Calculates the XCSF predictions for the provided input.
Detailed Description
Supervised regression learning functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2023.
Definition in file xcs_supervised.h.
Function Documentation
xcs_supervised_fit()
double xcs_supervised_fit (struct XCSF * xcsf, const struct Input * train_data, const struct Input * test_data, const bool shuffle, const int trials)
Executes MAX_TRIALS number of XCSF learning iterations using the training data and test iterations using the test data.
Parameters
[in] xcsf The XCSF data structure.
[in] train_data The input data to use for training.
[in] test_data The input data to use for testing.
[in] shuffle Whether to randomise the instances during training.
[in] trials Number of trials to execute.
Returns
The average XCSF training error using the loss function.
Definition at line 98 of file xcs_supervised.c.
References param_set_explore(), perf_print(), Input::x, Input::x_dim, xcs_supervised_sample(), xcs_supervised_trial(), Input::y, and Input::y_dim.
Referenced by XCS::fit(), and main().
xcs_supervised_predict()
void xcs_supervised_predict (struct XCSF * xcsf, const double * x, double * pred, const int n_samples, const double * cover)
Calculates the XCSF predictions for the provided input.
Parameters
[in] xcsf The XCSF data structure.
[in] x The input feature variables.
[out] pred The calculated XCSF predictions.
[in] n_samples The number of instances.
[in] cover If cover is not NULL and the match set is empty, the prediction array will be set to this value instead of covering.
Definition at line 140 of file xcs_supervised.c.
References param_set_explore(), and xcs_supervised_trial().
Referenced by XCS::predict().
xcs_supervised_score()
double xcs_supervised_score (struct XCSF * xcsf, const struct Input * data, const double * cover)
Calculates the XCSF error for the input data.
Parameters
[in] xcsf The XCSF data structure.
[in] data The input data to calculate the error.
[in] cover If cover is not NULL and the match set is empty, the prediction array will be set to this value instead of covering.
Returns
The average XCSF error using the loss function.
Definition at line 160 of file xcs_supervised.c.
References Input::n_samples, param_set_explore(), Input::x, Input::x_dim, xcs_supervised_trial(), Input::y, and Input::y_dim.
Referenced by XCS::fit(), XCS::score(), and xcs_supervised_score_n().
xcs_supervised_score_n()
double xcs_supervised_score_n (struct XCSF * xcsf, const struct Input * data, const int N, const double * cover)
Calculates the XCSF error for a subsample of the input data.
Parameters
[in] xcsf The XCSF data structure.
[in] data The input data to calculate the error.
[in] N The maximum number of samples to draw randomly for scoring.
[in] cover If cover is not NULL and the match set is empty, the prediction array will be set to this value instead of covering.
Returns
The average XCSF error using the loss function.
Definition at line 184 of file xcs_supervised.c.
References Input::n_samples, param_set_explore(), Input::x, Input::x_dim, xcs_supervised_sample(), xcs_supervised_score(), xcs_supervised_trial(), Input::y, and Input::y_dim.
Referenced by XCS::score().