XCSF: xcsf.h File Reference
xcsf.h File Reference
XCSF data structures.
#include <errno.h>
#include <float.h>
#include <inttypes.h>
#include <limits.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct Cl
Classifier data structure.
struct Clist
Classifier linked list.
struct Set
Classifier set.
struct XCSF
XCSF data structure.
struct Input
Input data structure.
Functions
size_t xcsf_load (struct XCSF *xcsf, const char *filename)
Reads the state of XCSF from a file.
size_t xcsf_save (const struct XCSF *xcsf, const char *filename)
Writes the current state of XCSF to a file.
void xcsf_free (struct XCSF *xcsf)
Frees XCSF population sets.
void xcsf_init (struct XCSF *xcsf)
Initialises XCSF with an empty population.
void xcsf_print_pset (const struct XCSF *xcsf, const bool print_cond, const bool print_act, const bool print_pred)
Prints the current XCSF population.
void xcsf_ae_to_classifier (struct XCSF *xcsf, const int y_dim, const int n_del)
Switches from autoencoding to classification.
void xcsf_pred_expand (const struct XCSF *xcsf)
Inserts a new hidden layer before the output layer within all prediction neural networks in the population.
void xcsf_retrieve_pset (struct XCSF *xcsf)
Retrieves the previously stored population.
void xcsf_store_pset (struct XCSF *xcsf)
Stores the current population.
Variables
static const int VERSION_MAJOR = 1
XCSF major version number.
static const int VERSION_MINOR = 1
XCSF minor version number.
static const int VERSION_BUILD = 2
XCSF build version number.
Detailed Description
XCSF data structures.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file xcsf.h.
Function Documentation
xcsf_ae_to_classifier()
void xcsf_ae_to_classifier (struct XCSF * xcsf, const int y_dim, const int n_del)
Switches from autoencoding to classification.
Parameters
[in] xcsf The XCSF data structure.
[in] y_dim The output dimension (i.e., the number of classes).
[in] n_del The number of hidden layers to remove.
Definition at line 166 of file xcsf.c.
References Clist::cl, Cl::err, Cl::exp, Cl::fit, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, Set::list, LOSS_ONEHOT, Clist::next, pa_free(), pa_init(), param_set_loss_func(), param_set_y_dim(), pred_neural_ae_to_classifier(), Cl::prediction, XCSF::pset, Cl::time, XCSF::time, and XCSF::y_dim.
Referenced by XCS::ae_to_classifier().
xcsf_free()
void xcsf_free (struct XCSF * xcsf)
Frees XCSF population sets.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 53 of file xcsf.c.
References XCSF::aset_size, clset_kill(), XCSF::E0, XCSF::error, XCSF::mfrac, XCSF::mset_size, XCSF::prev_pset, XCSF::pset, and XCSF::time.
Referenced by main().
xcsf_init()
void xcsf_init (struct XCSF * xcsf)
Initialises XCSF with an empty population.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 37 of file xcsf.c.
References XCSF::aset_size, clset_init(), XCSF::E0, XCSF::error, XCSF::mfrac, XCSF::mset_size, XCSF::prev_pset, XCSF::pset, and XCSF::time.
Referenced by main(), and XCS::XCS().
xcsf_load()
size_t xcsf_load (struct XCSF * xcsf, const char * filename)
Reads the state of XCSF from a file.
Parameters
[in] xcsf The XCSF data structure.
[in] filename The name of the input file.
Returns
The total number of elements read.
Definition at line 109 of file xcsf.c.
References clset_init(), clset_kill(), clset_pset_load(), param_load(), XCSF::pset, Set::size, VERSION_MAJOR, and VERSION_MINOR.
Referenced by XCS::load(), and main().
xcsf_pred_expand()
void xcsf_pred_expand (const struct XCSF * xcsf)
Inserts a new hidden layer before the output layer within all prediction neural networks in the population.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 146 of file xcsf.c.
References Clist::cl, Cl::err, Cl::exp, Cl::fit, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, Set::list, Clist::next, pred_neural_expand(), XCSF::pset, Cl::time, and XCSF::time.
Referenced by XCS::pred_expand().
xcsf_print_pset()
void xcsf_print_pset (const struct XCSF * xcsf, const bool print_cond, const bool print_act, const bool print_pred)
Prints the current XCSF population.
Parameters
[in] xcsf The XCSF data structure.
[in] print_cond Whether to print condition structures.
[in] print_act Whether to print action structures.
[in] print_pred Whether to print prediction structures.
Definition at line 72 of file xcsf.c.
References clset_print(), and XCSF::pset.
Referenced by XCS::print_pset().
xcsf_retrieve_pset()
void xcsf_retrieve_pset (struct XCSF * xcsf)
Retrieves the previously stored population.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 208 of file xcsf.c.
References clset_init(), clset_kill(), XCSF::prev_pset, XCSF::pset, and Set::size.
Referenced by XCS::retrieve().
xcsf_save()
size_t xcsf_save (const struct XCSF * xcsf, const char * filename)
Writes the current state of XCSF to a file.
Parameters
[in] xcsf The XCSF data structure.
[in] filename The name of the output file.
Returns
The total number of elements written.
Definition at line 85 of file xcsf.c.
References clset_pset_save(), param_save(), VERSION_BUILD, VERSION_MAJOR, and VERSION_MINOR.
Referenced by XCS::save().
xcsf_store_pset()
void xcsf_store_pset (struct XCSF * xcsf)
Stores the current population.
Parameters
[in] xcsf The XCSF data structure.
Definition at line 190 of file xcsf.c.
References Clist::cl, cl_init_copy(), clset_add(), clset_kill(), Set::list, Clist::next, XCSF::prev_pset, and XCSF::pset.
Referenced by XCS::store().
Variable Documentation
VERSION_BUILD
const int VERSION_BUILD = 2 static
XCSF build version number.
Definition at line 39 of file xcsf.h.
Referenced by param_print(), XCS::version_build(), and xcsf_save().
VERSION_MAJOR
const int VERSION_MAJOR = 1 static
XCSF major version number.
Definition at line 37 of file xcsf.h.
Referenced by param_print(), XCS::version_major(), xcsf_load(), and xcsf_save().
VERSION_MINOR
const int VERSION_MINOR = 1 static
XCSF minor version number.
Definition at line 38 of file xcsf.h.
Referenced by param_print(), XCS::version_minor(), xcsf_load(), and xcsf_save().